### ISSUE TITLE
Continually redirecting?

### ISSUE THREAD

**Issue by ADOrigin** [Microsoft/mattercenter#101]
I've deployed this using the powershell script. One issue I encountered was that the Publish-SiteOnAzure function in PublishOnAzure.ps1 seemed to cause an issue.  I had the 2 web apps created in Azure to publish the UI and service to, but as soon as this function called Publish-AzureWebsiteProject, any attempt to communicate with the web apps would return a 403 error from then on.  In the end I had to delete and recreate the web apps and publish the ProviderService and SharePointAppWeb projects directly to their respective Azure web apps from Visual Studio.

Other than that, the Powershell script seems to indicate that it has deployed successfully.  However, when I go to my SharePoint Online site and try to go into Matter Center it seems to get stuck on this page:

https://XXXX.sharepoint.com/sites/XXXX/_layouts/15/appredirect.aspx?client_id=XXXXX&redirect_uri=https://XXXX.azurewebsites.net/pages/Home.aspx?{StandardTokens}?appType=#SPVisited=1

It displays "Working on it", but never seems to actually go anywhere or do anything.  I can't seem to figure out why - have I possibly set an incorrect configuration value somewhere?

**Comment by amitabhm21** [comment]
Have you double checked that the client secrets are configured accurately?

**Comment by ADOrigin** [comment]
Thanks very much for your reply, @amitabhm21.

I *thought* I had these configured correctly, but after your suggestion I went back and generated new client id / secret and updated the configuration files and redeployed.  That seems to have fixed this particular issue and the Home.aspx page is now loading instead of just getting stuck on the "Working on it message".

One issue it is having now is that when it loads the Home.aspx page, it displays an error: 

```
An unexpected error has occured while performing your last action. Please try again. If this issue persist, please contact your administrator.

Error Code: 2000

Timestamp: 03-15-2016 01:48:15:2262687
```
If I just close this error by clicking on the "x" in the top corner, it doesn't seem to have any negative effects that I can see (although I still need to test some more).  If I click on a link on the Home.aspx page (e.g. "Create a new matter"), that page then loads OK, but displays the same error again.  Once again, it seems to work ok after I close the error message.

I'm not sure what error code 2000 indicates or how to get rid of this message.  It's more of an annoyance than a showstopper at this stage, but still something I need to get rid of.

**Comment by ADOrigin** [comment]
I think this Error Code 2000 may be related to the logging.  I'll close this issue and raise a separate one.
