### ISSUE TITLE
Support for on-premises Sharepoint 2013 Enterprise + installed Office 2013 .

### ISSUE THREAD

**Issue by davegould** [Microsoft/mattercenter#102]
From Microsoft's description of Matter Center, I understand it can work with on-premises Sharepoint server.  I see from the scripts and Deployment Guide for this github project that the scripts are tailored to the cloud based services--which I don't have and don't want. 

I am a lawyer with a small practice.  I am very interested in this project and have joined github to put this question to you.  I have basic knowledge of Sharepoint, but little knowledge of powershell, github or matter center.  I think seriously to hire a Sharepoint/powershell freelancer to modify the scripts for me so I can give it a try.   

Please estimate how much work is involved in tweaking these powershell installation scripts to make this project work with on-premises Sharepoint and installed office 2013 apps on workstations?  Is it even possible, or am I misunderstanding?

Can anyone recommend someone fit for the job?

Thank you for any information or advice you have.

David Gould

**Comment by anneclairelatham** [comment]
Hi David, 
We deploy Matter Center for small law firms but with regards to completely on prem..what version of SharePoint do you have?
As for the mattercenter apps - where will you have IIS web server working?
To determine who could help you out - what are your plans for matter center?
Claire Latham
Or email me at claire.latham@ubiquitywave.com

**Comment by DaveyDoo** [comment]
I'm trying to get my head around how this would work with on-prem SharePoint.  Obviously the service and UI web app can be deployed to run on IIS locally and the SharePoint app can (I suppose) be installed on-prem with some modification.  
What would SharePoint's site structure look like?  Since Matter Center creates a new site collection for each client, it seems like you would need to set up a separate on-prem web app for each client?
Dave

**Comment by stefvanhooijdonk** [comment]
On Premises there would be a site collection for each customer also.
Stef

**Comment by tgarmon** [comment]
Claire, are you available to hire? Please email me at tgarmon@wcwpllc.com if you are or can refer someone, We are a small firm. We have azure and E5 office 365 and have published Matter Center web application, but have a couple of issues that need analyzing and resolving.
