### ISSUE TITLE
Compatibility of the outlook addins

### ISSUE THREAD

**Issue by alfallouji** [Microsoft/mattercenter#105]
Hi, 

I have looked at the different documentation available but couldn't find it (sorry If I missed that).

What version of Outlook is needed for the Outlook addins ? Would it work with Outlook 2007 ?

**Comment by DaveyDoo** [comment]
I haven't tried but my understanding is Matter Center works with Office 365 (online only), not on-prem.  If someone has gotten it work with with on-prem, I'd like to hear how they pulled it off.

**Comment by alfallouji** [comment]
Hi, I have seen a video demo showing outlook thick client with a Matter Center addin. Also, based on what I read on the doc, there are addins for outlook and word thick clients. However, it is unclear what version of outlook or word can run the addin.

**Comment by amitabhm21** [comment]
The requirements for running office add-ins are detailed in the article here: https://msdn.microsoft.com/en-us/library/office/dn833104.aspx

Some features of Matter Center that will be released in near future will be supported only on office 365 and Office 2016 (and above).

**Comment by amitabhm21** [comment]
Closing this assuming the last comment answered your questions @alfallouji
