### ISSUE TITLE
Keep getting this error An error has occurred and the matter was not created. Error Code: -2146233088

### ISSUE THREAD

**Issue by shak3800** [Microsoft/mattercenter#106]
Hello everyone!

I 've read every single post and I have found that the site columns of the matter center content types need to be specified with the taxonomy terms.

I 've changes the AreaOfLaw column to Litegation and SubAreaofLow to Intellectual Property. This hasn't fixed my issue. When I republish the content type I get some errors that the are conflicts with basically each column of the matter center content types. 

Anyone knows how to fix this?

**Comment by DaveyDoo** [comment]
Can you give more details about the errors you get when republishing the content types?

**Comment by shak3800** [comment]
@DaveyDoo  in the catalog site collection if I click on site settings , content type publishing and content type publishing error log I get a lot of errors in this form : 

Ttile
Proxy Taxonomy_4BLQTxDzt3+F9JB2YxRRiQ== error

Syndication Item
Medical Device 

Syndication Failure Stage
Pre-import check 

Syndication Failure Message
Content type name 'Medical Device' conflict  

I get this error message for a number of 12 content types 

Any ideas please? I don't want to start over again with new SharePoint environment .

Thanks !

**Comment by shak3800** [comment]
solution was to delete the site content types from site catalog , delete related site columns , empty the recycle bin and then republish the content types.
