### ISSUE TITLE
Deployment script fails at step 6: URI scheme is not valid

### ISSUE THREAD

**Issue by cnb1991** [Microsoft/mattercenter#109]
`3/16/2016 5:24:07 PM - Completed updating search configuration file
3/16/2016 5:24:07 PM - Step 6: Update resource and config files in build
Updating resource files
Updating Constants.resx file
Message: Invalid URI: The URI scheme is not valid.
Stacktrace:    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Microsoft.Legal.MatterCenter.UpdateAppConfig.UpdateConfig.UpdateResourceConstants(Dictionary'2 updateList, String constantElement, String constantAttribute, List'1 manifestFile)
   at Microsoft.Legal.MatterCenter.UpdateAppConfig.UpdateConfig.UpdateConstants(Dictionary'2 updateList, String folderName)
Message: Failed to update app schema files
Failed to update resource files`

In the Constraints.resx file under Microsoft.Legal.MatterCenter.ProviderService, I have changed the **Common_CSS_File_Location** to **/sites/catalog/SiteAssets/common/Styles/spCommon.css**, and the **Common_JS_File_Location** to **/sites/catalog/SiteAssets/common/Styles/spCommon.css**. I am not sure what else could be causing the deployment to fail.

**Comment by shak3800** [comment]
@cnb1991  Have you figured out a way to fix this ?

**Comment by cnb1991** [comment]
I believe once I removed multi-factor authentication from my account I was able to get past step 6.

**Comment by shak3800** [comment]
Problem was some incorrect values.
