### ISSUE TITLE
Missing Pages?

### ISSUE THREAD

**Issue by ADOrigin** [Microsoft/mattercenter#110]
Appendix A in the deployment documentation refers to a "WebDashboardSP" page in the Site Pages folder.  I've deployed "successfully" using the Powershell script, but this page does not seem to be there.  Looking at the screenshot in Appendix A, that seems to indicate that there should be 6 pages in Site Pages, but I only have 3.  The 3 pages I've got are:

documentDetails.aspx
Home.aspx
How To Use This Library.aspx.

I don't have WebDashboardSP or the other 2 missing pages (what are they supposed to be?).  Where are these pages?

**Comment by WilsonReddy** [comment]
Are you referring latest deployment document. The document says create new page with any name and 'webdashboard' given as an example. can you provide page no and line that has reference to "WebDashboardSP".

I see "webdashboardsp.html" is referred as "WebDashboardSPTemplate.html".   

Also, follow complete Appendix A to create settings and dashboard pages.

**Comment by ADOrigin** [comment]
Yeah, Appendix A is what I'm trying to work my way through, but it doesn't seem to make sense.  It feels like there are some steps missing or something.

WebDashboardSP is referred to in Appendix A on page 33 of the deployment doc. It says "Navigate to 'site pages'", then "Update web dashboard URL in 'WebDashboardSP' HTML.  It also says "Location for 'WebDashbaordSP' = '<solution location>/Html Chunk/webdashbaordsptemplate.html', but I can't seem to find that .../Html Chunk/... path anywhere, either.

**Comment by amitabhm21** [comment]
@ADOrigin Is this still an open issue ?

**Comment by ADOrigin** [comment]
No, sorry - I forgot I'd opened this!

Those files were actually in deployments\Static Content\HTML.
