### ISSUE TITLE
Step 10 Script Failure: Publish-AzureWebsiteProject : Website xxx.azurewebsites.net was not found

### ISSUE THREAD

**Issue by cnb1991** [Microsoft/mattercenter#111]
![capture](https://cloud.githubusercontent.com/assets/11984849/13868373/f6fd7c7c-ec84-11e5-9b89-97e9495a2be5.PNG)

I have not been able to get past this issue all day, and I have made sure all of the fields in the deployment config are correct. I have tried the other remedies from prior issues regarding step 10, and have not had any luck. Any help would be greatly appreciated.

**Comment by cnb1991** [comment]
P.S.
I solved my prior issue of **Publish-AzureWebsiteProject : value cannot be null** by changing my Azure PowerShell version from 1.2.2. to the technical preview build 1.2.1. and this error occurred.

**Comment by WilsonReddy** [comment]
what values do you have in MSDeploymentConfg excel file config sheet for UISSiteURL and ServiceSiteURL? it should be **https://**yoursitename.azurewebsites.net for UISiteURL and **https://**yourservicename.azurewebsites.net for serviceurl.

**Comment by cnb1991** [comment]
Yes, mine are both https:// and the AzureWebsiteName & AzureWebServiceName are both in the format xxxxxxxxx.azurewebsites.net.

**Comment by cnb1991** [comment]
I just remembered, I did not set this up with ssl, so my site urls on the Azure admin read http://, do you think this could be the issue?

**Comment by shak3800** [comment]
Azure websites have by default ssl certificate. You can check that by accessing them using https

**Comment by WillTab** [comment]
I think this is related to Issue: ASM vs ARM for web-sites #144.  

Still patiently waiting for a response in that thread.

**Comment by amitabhm21** [comment]
This issue is not resolved. Please look at the new deployment project in the latest merge.
