### ISSUE TITLE
An error has occurred and the matter was not created. Error Code: -2146233088

### ISSUE THREAD

**Issue by mateuszradny** [Microsoft/mattercenter#114]
When I try create a new matter I get error message: "An error has occurred and the matter was not created. Error Code: -2146233088".

In Azure storage account I have a few entries:
![capture](https://cloud.githubusercontent.com/assets/11389995/13915276/fcce5398-ef53-11e5-8358-b6f5c5e8dfc5.PNG)

I get this same message as body of response when I click "Create and notify" button:
`{ \"code\": \"-2146233088#|#03-21-2016 09:52:47:6852817\", \"value\": \"File Not Found.\" }`

Any suggestions?

**Comment by shak3800** [comment]
This error was posted again before. It probably has to do with the fact that the content type columns AreaOfLaw and SubAreaOfLaw are not mapped correctly to the taxonomy terms.

Go to the contentypehub find the matter center content type and change the mapping of AreaOfLaw from Practice Group to Litigation and SubAreaOfLaw to Intellectual Property and then republish all the content types of the Matter Center group. Wait for some minutes for the content types to appear to the app catalog and try again to create a matter

**Comment by mateuszradny** [comment]
Thank you for your answer. Unfortunately this not working for me. I have changed type of AreaOfLaw and SubAreaOfLaw columns and still I get this same error.

**Comment by shak3800** [comment]
This is what worked for me : Go to the contentypehub go to site settings, site columns , change the AreaOfLaw from Practice Group to Litigation and SubAreaOfLaw to Intellectual Property and then republish all the content types of the Matter Center group. Wait for some minutes for the content types to appear to the app catalog and try again to create a matter. 

Sometimes I had to delete the content types and site columns from the app catalog site , empty the recycle bin of stage 2 , and then repupblish all the content types of matter center group from the contenttypehub

**Comment by mateuszradny** [comment]
I did exactly the same steps, but still this not working for me. Any other ideas? I'm working on this for over a week...

**Comment by shak3800** [comment]
Have you fixed some lines of code that needed fixing ? There are syntax errors with the azurewbesites in some cases is azurewebsite (without the s) . Check my other posts and all closed ones and try what users suggest.

**Comment by mateuszradny** [comment]
I checked your other posts. I also tried to redeploy the solution from scratch but stil I have this problem. I have no idea what could be causing.

**Comment by sunnymistry** [comment]
I assume that you are having the English O365 tenant. In this case can you check if Site Pages library is present in the Site Collection where you are trying to create the Project? 

Another thing to check if the Site collection URL in the term store is actually valid.

**Comment by sramangit** [comment]
Was this resolved? I'm running into the same error.

**Comment by ctrulove** [comment]
Can you verify that you completed the steps in Appendix C of the deployment guide and that the content types are available in the Client site collection?

**Comment by amitabhm21** [comment]
Closing this issue as there seems to be no response on this.
