### ISSUE TITLE
Build and Deployment Guide Steps 7 and 8 Need Clarification

### ISSUE THREAD

**Issue by DaveyDoo** [Microsoft/mattercenter#122]
Step 7, [Optional] item 3 contains the text: Create a folder called SharePoint App under deployments folder and copy both app files created to the newly created folder
then, Step 8, item 11 contains the text: Create a folder called SharePoint App and copy the file(s) created in Step 7 to the newly created folder
This is confusing.  Is the SharePoint App in Step 7 the same as the one in Step 8?  If you create the SharePoint App folder in Step 7, can you skip the one in Step 8?

**Comment by shak3800** [comment]
Also there is a sentence that is unfinished . To build and copy all exe files and config (of helper utilities) into ... and it finishes there. Although is pretty obvious where to copy them

**Comment by muradhaider5** [comment]
@shak3800 where to copy these exe and config files?

**Comment by amitabhm21** [comment]
The document is now simplified. Feedback welcome. Closing this issue.
