### ISSUE TITLE
Step 10 Error: Requested value 'VS2015' was not found

### ISSUE THREAD

**Issue by DaveyDoo** [Microsoft/mattercenter#123]
I am redeploying Matter Center with the latest code and reaching the following error in Step 10:
Get-AzureWebsite : Requested value 'VS2015' was not found.
At C:\mc\v20160321\src\deployments\Scripts\PublishOnAzure.ps1:50 char:13
+     $Website = Get-AzureWebsite -Name $ExcelValues[0]
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureWebsite], ArgumentException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Websites.GetAzureWebsiteCommand
Cannot index into a null array.
False
3/22/2016 12:58:11 PM - Publishing files to Azure or creating Azure Redis cache failed 

If I comment out the code in PublishOnAzure.ps1:
    Show-Message -Message "Updating App settings for website"
	$Website = Get-AzureWebsite -Name $ExcelValues[0] 
	$Website.AppSettings["Old_Encryption_Key"]= $Guid
	$Website.AppSettings["Encryption_Key"]= $Guid
	Set-AzureWebsite -Name $ExcelValues[0] -AppSettings $Website.AppSettings

	Show-Message -Message "Updating App settings for web service"
	$WebService = Get-AzureWebsite -Name $ExcelValues[1]

	# Accept MailCart username and Password
	
	if($null -eq $ExchangeCredential) {
	    $ExchangeCredential = Get-Credential -Message "Enter credentials to connect with Exchange server."	
	}
    $WebService.AppSettings["Mail_Cart_Mail_User_Name"]= $ExchangeCredential.UserName
	$WebService.AppSettings["Mail_Cart_Mail_Password"]= $ExchangeCredential.GetNetworkCredential().Password
	$WebService.AppSettings["Old_Encryption_Key"]= $Guid
	$WebService.AppSettings["Encryption_Key"]= $Guid
	Set-AzureWebsite -Name $ExcelValues[1] -AppSettings $WebService.AppSettings

I get a similar error further in the script.  If I comment out the following code:
            $WebService = Get-AzureWebsite -Name $ExcelValues[1]	        
            
            $WebService.AppSettings["Cache_Primary_Key"]= $MatterCenterCache.PrimaryKey
            $WebService.AppSettings["Cache_Host_Name"]= $MatterCenterCache.HostName

	        Set-AzureWebsite -Name $ExcelValues[1] -AppSettings $WebService.AppSettings   

The script completes successfully.
The AppSettings for Old_Encryption_Key and Encryption_Key match in my deployed sites, and the Cache_Primary_Key and Cache_Host_Name values appear to be correct.
I can't find any reference to 'VS2015' in the code or on Azure.

**Comment by shak3800** [comment]
In azure change the visual studio debugging from 2015 or 2012 to off

**Comment by DaveyDoo** [comment]
In Azure, I verified that, for both the ui and service web apps, the remote debugging is set to Off.  I re-ran the deployment and got a slightly different error:

3/23/2016 10:50:05 AM - Updating App settings for website
Get-AzureWebsite : Requested value 'VS2015' was not found.
At C:\mc\v20160321\src\deployments\Scripts\PublishOnAzure.ps1:51 char:13
+     $Website = Get-AzureWebsite -Name $ExcelValues[0]
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureWebsite], ArgumentException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Websites.GetAzureWebsiteCommand
 
Cannot index into a null array.
False
3/23/2016 10:50:08 AM - Publishing files to Azure or creating Azure Redis cache failed
3/23/2016 10:50:08 AM -

**Comment by shak3800** [comment]
Even if it is off , make sure that vs 2012 is selected . I know its strange but it worked for me

**Comment by DaveyDoo** [comment]
How about that!  I had to turn Remote Debugging on so I could select 2012 (2015, curiously, is not an option), save it, then turn it off with 2012 still selected.
Thanks!

**Comment by shak3800** [comment]
@DaveyDoo  this can be closed now ;)
