### ISSUE TITLE
Can't upload documents to matters

### ISSUE THREAD

**Issue by shak3800** [Microsoft/mattercenter#128]
Hi everyone!

I have finally after managed to create my first matter and now I'm facing with another issue.

When I send emails with attachment I can't upload those attachments to matters. How can this be fixed?

Thanks a lot !

**Comment by WilsonReddy** [comment]
@shak3800 This issue happening due to office API change and it fixed in latest checkin. Taking latest website code and redeploying only website or redeploying whole solution using deployment script will fix this issue.

Sent from my Windows Phone
________________________________

**Comment by shak3800** [comment]
@WilsonReddy  it works by changing the Upload.js of the app service on azure. But when I choose the My Documents I can't see the documents and I can only see the emails listed there.

Any ideas ?

**Comment by shak3800** [comment]
Never mind . It just takes some time for the documents to appear. I wish there was a way to add attachments to emails from matter libraries
