### ISSUE TITLE
Error in deployment Step 12:  Unknown parameter OrganizationApp

### ISSUE THREAD

**Issue by JohnLeeNJ** [Microsoft/mattercenter#129]
When running the deployment script I receive an error when the app is deployed to Exchange.  (screen shot attached).  During the "Adding Microsoft.Legal.MatterCenter_Outlook.xml App to Exchange" step, the error says that a parameter named "OrganizationApp" cannot be found.  The fully-qualified error message is "NamedParameterNotFound, New-App".

After the error it says that the Outlook app was successfully added to Exchange.  However, when I access Outlook I do not have the Matter Center App available for installation.

Can anyone provide any insight or suggestions?

Thanks.

![exchange app error](https://cloud.githubusercontent.com/assets/17253132/14062183/08fcaae0-f36c-11e5-8ddb-632ddcdee439.png)

**Comment by sunnymistry** [comment]
If the app is not uploaded successfully via the scripts, you can also upload the App manually using the Exchange Admin Center. You can refer the steps about the same over here: (https://dev.office.com/docs/add-ins/outlook/testing-and-tips)
