### ISSUE TITLE
Access denied errors when trying to access pages in Azure

### ISSUE THREAD

**Issue by JohnLeeNJ** [Microsoft/mattercenter#130]
After installing matter center I can get to the Azure Home.aspx page, but none of the other pages (My Matters, My Documents, New Matter, or MatterCenterHome).  I get messages that access to the page is denied, or that the Azure site is not found in the Access-Control-Allow-Origin header.  I have attached screenshots.

I have tried all the suggestions in thread #45 without success.  All entries in the web.config file are correct and clearing cookies made no difference. 

What do I need to do to resolve this?

Thanks.

![access denied error 1](https://cloud.githubusercontent.com/assets/17253132/14062347/e8f993e2-f371-11e5-9d74-f246ccf2f49f.png)
![access denied error 2](https://cloud.githubusercontent.com/assets/17253132/14062348/e8fd3c04-f371-11e5-997f-1f8f6195d887.png)

**Comment by sunnymistry** [comment]
Looking at the error message it seems that the Access-Control-Allow-Origin Header in web.config of ProviderService project is not correctly set. Can you check if the value of following setting is correctly set for your azure web UI site? 

        <add name="Access-Control-Allow-Origin" value="https://_yourazurewebsite_.azurewebsites.net" />

**Comment by JohnLeeNJ** [comment]
@sunnymistry thank you for your response.  But I have already checked this.  The URL returned in the access denied error is identical to the URL that is already in the web.config file.  I had previously made changes to errors in the web.config, and it appears that the new version did not get deployed to Azure when I redeployed the application.  Is that a possibility?  If so, how do I fix it?

**Comment by sunnymistry** [comment]
Yes that can be a possibility. To confirm this theory you can open the Web.Config of your Azure Web site via Visual Studio or by using Azure FTP location. Once it is confirm that the web.config is indeed not updated, you can republish just the config file and validate.

**Comment by JohnLeeNJ** [comment]
@sunnymistry: I have checked the web.config that is on my Azure site and the entry is correct.  What else might be the cause of this error?

**Comment by sunnymistry** [comment]
@JohnLeeNJ there is no other place because of which you should get this error. Can you check the web.config of service as well if not already done. This is CORS error where the Service will simple disregard any request coming from a site which is not in the Access Control Allow Origin attribute.

**Comment by JohnLeeNJ** [comment]
@sunnymistry - I have finally resolved this problem.  The URL in the webconfig contained mixed case alpha characters.  As soon as I changed it to all lower case, the error was resolved and I can now access the pages on the Matter Center.  Issue closed.
