### ISSUE TITLE
small firm implementation of Matter Center

### ISSUE THREAD

**Issue by jrgonzalez1974** [Microsoft/mattercenter#131]
I'm a small 6 person law firm focusing on three major areas of law.  I am interested in using all the capabilities offered by Office 365.  I stumbled across Matter Center and believe that It might be a good fit for the work that we do in our firm. I could serve to increase our efficiency and productivity in the office by leveraging all the capabilities of Office 365.  However, I found the implementation of Matter Center somewhat time consuming and not necessarily simple for a small firm like mine to implement.  Matter Center has the possibility of becoming a necessary tool for small firms if its possible to make the implementation of the system less consuming or more economical.  Can anyone help me in assessing whether Matter Center would be a fit for my firm or the steps, cost and maintenance of such an implementation?

**Comment by anneclairelatham** [comment]
Hi! 
I work with UbiquityWave, a small DC area tech advisory firm. Here is our website: http://www.ubiquitywave.com/. Our founder, Carol Corneby, was one of Matter Center's original Architects. I agree with you, it can be tricky to deploy, we have had some struggles but our admin and developers are able to stand it up well now. It can definitely be a good fit for a small firm, especially if everyone is already on Office 365 and it's not too complex, an office can be pick it up pretty fast.  If you'd like we can walk you through some of the feature sets in a demo if you'd like and give you some thoughts on implementation too.

**Comment by wgrizzle** [comment]
Hi 

My name is Wayne Grizzle, i am a Solution Architect at ProjectLeadership Associate. Our main office is in Chicago, with offices throughout the US. We have implemented Matter Center in a number of clients and presented on ILTA. We can certainly assist you with piloting and production implementation of Matter Center. Our website is www.projectleadership.net and i can be reached at wgrizzle@projectleadership.net.

**Comment by amitabhm21** [comment]
closing this issue based on responses. Please feel to re-open if needed.
