### ISSUE TITLE
Not able to load upload popup in Outlook when using an email with attachment(s)

### ISSUE THREAD

**Issue by ajmeradivyesh** [Microsoft/mattercenter#132]
When using Matter Center in Outlook, we are not able to load upload popup. Following are steps we followed:
	1. Open Outlook and use an email which contains attachment(s)
	2. Open Matter Center app
	3. Click on Matters, Matters page will load with list of Matters
	4. For any Matter, click on ECB menu (…) and select 'Upload to this Matter'. Nothing will happen, instead upload popup should open with list of email and attachments.
        5. If these steps are followed with an email without attachments, upload popup loads properly.

**Comment by WilsonReddy** [comment]
Can you take latest code for website and deploy it. This issue fixed in latest checkin of upload.js file.
________________________________

**Comment by ajmeradivyesh** [comment]
Hello Wilson,
Thanks for the reply.
Yes, this change is working fine. Observed that in the Matter Center code there is another reference of $0_0 property of email item. This reference if present in SearchDocument.js

101       if (oCurrentEmailItem && oCurrentEmailItem.$0_0) { 
102             var sEmailCreatedTime = oCurrentEmailItem.$0_0.dateTimeCreated 
103                 , sEmailModifiedTime = oCurrentEmailItem.$0_0.dateTimeModified; 

This feature is being used for attaching document to email in Compose mode.

Can we update this reference as well?

**Comment by WilsonReddy** [comment]
Good finding. Please submit pull request.

Sent from my Windows Phone
________________________________

**Comment by WilsonReddy** [comment]
@ajmeradivyesh  this issue is fixed with below checkin https://github.com/Microsoft/mattercenter/commit/8d14aeca2d568f14dc250f0e2300d9798cf76c26 
Thank you for bringing up this issue.
