### ISSUE TITLE
Information Missing - Copying exe and config files after building helper utilites

### ISSUE THREAD

**Issue by muradhaider5** [Microsoft/mattercenter#133]
Information in deployment documentation is missing as it says (in bullet 12 of step-8) 

> 12.	Create build of helper utilities
> a.	Navigate to src\Helper Utilities and open Helper Utilities solution in Visual Studio and build the solution
> b.	This will build all deployment utilities and copy all EXE and Config files into 
> 

so where exactly these files are to be copied?

**Comment by shak3800** [comment]
In helper utilities in deployment folder . You can other exe files and config files in there too

**Comment by muradhaider5** [comment]
Do we have to create a new folder there? as i don't find existing 'helper utilities' folder under 'deployment', but there is one under 'Src'.

**Comment by shak3800** [comment]
@muradhaider5 here is where you need to place the files 

\tree\master\cloud\src\deployments\Scripts\Helper Utilities

**Comment by muradhaider5** [comment]
Thanks for clarification, but its a little bit confusing as config and exe files for helper utilities are already there in the folder you mentioned.
