### ISSUE TITLE
Deployment script execution - step 11 getting failed

### ISSUE THREAD

**Issue by muradhaider5** [Microsoft/mattercenter#134]
I am running the deployment script (Deployment.ps1). At step 11, execution fails saying " 
Failed to add an app System.Management.Automation.MethodInvocationException: Exception calling ".ctor" with "2" argument(s): "Access to the path 'C:\mattercentermaster\tree\master\cloud\src\deployments\SharePoint App\App_GlobalResources' is denied." ---> System.UnauthorizedAccessException: Access to the path 'C:\mattercenter-master\tree\master\cloud\src\deployments\SharePoint App\App_GlobalResources' is denied.

i have tried setting permissions as 'Full Control' for 'Everyone'

**Comment by sunnymistry** [comment]
Can you check if the same set of permission is applied to parent folders as well? Generally users will not have access on C: drive at all. Possible workarounds are following:
a. Grant everyone control on entire C: 
b. Move your local repo to a separate drive where scripts are able to make changes in files

**Comment by muradhaider5** [comment]
Actually there is some ambiguity in deployment documentation at step -8 (sub-bullet 11) where it says: 

> Create a folder called SharePoint App and copy the file(s) created in Step 7 to the newly created folder
so i was copying files in SharePoint App folder which were created in sub bullet 7 of step 8 (i.e. the content of Service Publish folder) where in reality  it was asking to copy the files (2 package (APP) files) created in major step 7 (not sub bullet 7 of step 8). So, having step -7 written in documentation, sub bullet 11 of step 8 is not needed at all.
i hope it may help someone.
