### ISSUE TITLE
error in step 6 in updating the resource files

### ISSUE THREAD

**Issue by acumor** [Microsoft/mattercenter#135]
hello, I have updated the excel spreadsheet and running the Deploy.ps1 script and getting following error in step 6.  please help!

4/4/2016 8:47:55 AM - Step 6: Update resource and config files in build
Updating resource files
Message: Object reference not set to an instance of an object.
Stacktrace:    at Microsoft.Legal.MatterCenter.UpdateAppConfig.UpdateConfig.UpdateConstants(Dictionary`2 updateList, String folderName)
Message: Failed to update app schema files
Failed to update resource files
Message: Object reference not set to an instance of an object.
Stacktrace:    at Microsoft.Legal.MatterCenter.UpdateAppConfig.UpdateConfig.UpdateConstants(Dictionary`2 updateList, String folderName)
Message: Failed to update app schema files
Failed to update resource files
Updated Web.config
4/4/2016 8:47:55 AM - Updating resource and config files in solution failed
4/4/2016 8:47:55 AM -

**Comment by muradhaider5** [comment]
just try copying helper utilities exe and config files in Sharepoint App folder under deployments folder

**Comment by acumor** [comment]
hi, thank you for your prompt response.  under deployments folder, I only have Scripts and Static Content folder.  Could you please specify which folder?  Also do you want me to copy the "helper utilities" folder?

**Comment by muradhaider5** [comment]
No, you should be having the folders like 'Sharepoint App', 'Service Publish' and 'Web Publish'( in/under 'deployments' folder)that you would have created, following steps 7 and 8 mentioned in "Matter Center Build and Deployment Guide.docx"
and once you will create 'Sharepoint App' folder, you will need to copy helper utilities' exe and config files in that folder. But i would suggest you to confirm if you are correctly following the deployment step mentioned in deployment guide.

**Comment by acumor** [comment]
thank you for the info.  I was directly using step 9 and 10 - for automated process.  It seems, I need to follow step 5 - manually update all the files, then build the solution and publish it (step 6,7,8)....  I assumed that automated process will read the excel file and take care of everything...  will do steps 6,7,8 and try again.  thank you!
