### ISSUE TITLE
Is there a way to drag and drop Matter documents in emails?

### ISSUE THREAD

**Issue by shak3800** [Microsoft/mattercenter#137]
Hello everyone!

I like the fact that users can easily drag and drop documents into matters from emails. 

There is a way to add documents into emails from matter by going to matter details which opens a new window with the matter details . 

Is there a way to do this easily for the users? The same way you can drag and drop documents into matters?

Thanks a lot!

**Comment by sunnymistry** [comment]
This use case is already handled in current implementation. You can attached documents from Matter Center to email which are currently composing. Following is the way how this user scenarios works:
1. You are composing/writing an email to one of your colleague
2. During this you realize that you want to attach documents from Matter Center
3. While in the email itself (which you are writing), you open Matter Center from Office Add-ins 
4. Once Matter Center load in the right pane of the email, you navigate to Documents view
5. From this documents view, you can select the documents which you want to attached in current email

Hope this helps.

**Comment by amitabhm21** [comment]
The latest version of the solution will let you do this. Please get the latest version,
