### ISSUE TITLE
Business Process of Matters?

### ISSUE THREAD

**Issue by shak3800** [Microsoft/mattercenter#138]
Hello!

I understand that matter center was created based on specific business process regarding lawyers and matters.

Is there a way you could provide a document regarding this? For example regarding the conflict check , the roles etc

Thanks!

**Comment by SwapnilM92** [comment]
You can find the required details in [technical specification document](https://github.com/Microsoft/mattercenter/blob/mattercenter1.0/tree/master/cloud/docs/Matter%20Center%20Technical%20Specification.docx).

**Comment by premchandpl** [comment]
@shak3800 Closing this as information is there in the link provided above. Let us know if more information is required
