### ISSUE TITLE
Matter Center Addin for Office 365

### ISSUE THREAD

**Issue by muradhaider5** [Microsoft/mattercenter#140]
is someone experiencing the issue in loading matter center add-in for word online?
Mine is not getting loaded and it shows
![image](https://cloud.githubusercontent.com/assets/7326775/14320852/157e47fc-fc30-11e5-9917-a254dd66b020.png)
As i click on start, sometimes it gets loaded but still after some time, this error appears.
Please tell how to get rid of this.

**Comment by sunnymistry** [comment]
This is one of open/known issue of Matter Center add-in with Word/Excel/PowerPoint Online and Outlook Web Access. We are actively working to resolve this issue by using new Azure Active Directory Authentication library (ADAL). More details about this implementation is present in this [WIKI](https://github.com/Microsoft/mattercenter/wiki/Matter-Center-Web-Site-Re-architecture-Documentation)

**Comment by darkocolak** [comment]
What is the issue with online access? How can one fix it?
