### ISSUE TITLE
deploy.ps1 fails at step 6:  Invalid URI: The format of the URI could not be determined

### ISSUE THREAD

**Issue by dsorav** [Microsoft/mattercenter#141]
Trying to deploy MatterCenter, but continue to have a problem at Step 6: with an Invalid URI error.
Need help figuring out where the issue is so I can correct and get past this error.

Here is the PS error:

4/7/2016 9:22:00 AM - Step 6: Update resource and config files in build
Updating resource files
Updating Constants.resx file
Message: Invalid URI: The format of the URI could not be determined.
Stacktrace:    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Microsoft.Legal.MatterCenter.UpdateAppConfig.UpdateConfig.UpdateResourceConstants(Dictionary`2 updateList, String constantElement, String constantAttribute, List`1 manifestFile)
   at Microsoft.Legal.MatterCenter.UpdateAppConfig.UpdateConfig.UpdateConstants(Dictionary`2 updateList, String folderName)
Message: Failed to update app schema files
Failed to update resource files
Updating Constants.resx file
Successfully updated Constants.resx file
Updating Constants.resx file
Successfully updated Constants.resx file
Updating Log.resx file
Successfully updated Log.resx file
Successfully updated resource files
Updated Web.config
4/7/2016 9:22:02 AM - Updating resource and config files in solution failed

Thanks for the assistance

**Comment by premchandpl** [comment]
@dsorav  I assume in the constant.resx file, in one of the matter center source code project, you haven't update one of the URL. The URL in the constant.resx file is not in a valid format. Can you check all your resx files and check all the url's are valid in those resx files

**Comment by amitabhm21** [comment]
There have been significant improvements made to the deployment project, This scenario is  now obsolete.
Please take a look at the new code merged in master branch.
