### ISSUE TITLE
400 (Invalid instrumentation key)

### ISSUE THREAD

**Issue by rohitjadhav999** [Microsoft/mattercenter#142]
400 (Invalid instrumentation key)
The above error is appearing on the home page of matter center. Anyone have idea about it?

**Comment by sunnymistry** [comment]
@rohitjadhav999 this issue is because of that fact that Application Insights (AI) Instrumentation key used in the solution is incorrect. Because of this AI is not able to log usage information in it. If you are not leverage usage tracking, then we would encourage your to use the Key as "NA"

**Comment by ccorneby** [comment]
@sunnymistry helped, we have put in the NA and it works.
