### ISSUE TITLE
Deploy Step 5 Fails if there are more than 30 initial clients

### ISSUE THREAD

**Issue by DaveyDoo** [Microsoft/mattercenter#143]
Step 5: Update Search Configuration files and upload to SharePoint fails if MCDeploymentConfig.xlsx Client_Config tab contains more than 30 clients.
The helper utility UpdateAppConfig.exe builds a Search Configuration Xml and attempts to upload it with a CSOM call to ImportSearchConfiguration.
If there are more than 30 (or so) clients, the QueryTemplate value is (apparently) too long and the call fails and throws an exception with the message "There was an exception in the Database."
If you take the same Xml file generated by UpdateAppConfig.exe and attempt to import into SharePoint online, the import fails with "There was an error deserializing the object of type Microsoft.Office.Server.Search.Portability.SearchConfigurationSettings. Data at the root level is invalid. Line 1, position 1"
As a result, Matter Center searches can't find any matters.
Not sure if this is a Matter Center or SharePoint online bug.

**Comment by shilberry** [comment]
Were you able to solve this?  I edited the .xml files so that they would upload, and it created the ResultScope of 'Matter Center'.  However, matter center searches still don't function.  are there additional steps to configure search to show matters?

**Comment by premchandpl** [comment]
@DaveyDoo Closing this. Also the matter center has been upgraded to new version. Download the latest one and you can reopen this issue if this still persists
