### ISSUE TITLE
ASM vs ARM for web-sites

### ISSUE THREAD

**Issue by sramangit** [Microsoft/mattercenter#144]
Hello,

For the Matter Center setup, should we be using ASM (v1) or ARM (v2) to create the two web-sites. I tried it with ARM and the installation kept failing repeatedly with a message that the site doesn't exist. I heard ASM will be being deprecated, so I'd like to know what others have been experiencing/using.

Also, is there a specific version of Azure PowerShell to use for the install?

Thanks.

**Comment by WillTab** [comment]
I am having the same issue.  Azure resources are deployed in ARM.  Deploy script fails on step 10.

4/18/2016 7:51:17 AM - Step 10: Publishing files to Azure/IIS
4/18/2016 7:51:18 AM - Please enter your Azure credentials for Azure Resource Management
4/18/2016 7:51:36 AM - Creating Redis cache
4/18/2016 7:51:40 AM - Please enter your Azure credentials for Azure service management
4/18/2016 7:51:57 AM - Publishing web service on Azure
Publish-AzureWebsiteProject : The website mattercenterdpdemo was not found. Please specify a valid website name.
At C:\MatterCenter\mattercenter-master\tree\master\cloud\src\deployments\Scripts\PublishOnAzure.ps1:45 char:2
+     Publish-AzureWebsiteProject -Name mattercenterdpdemo -Package $Se ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Publish-AzureWebsiteProject], CloudException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Websites.PublishAzureWebsiteProject

4/18/2016 7:51:58 AM - Publishing web site on Azure
Publish-AzureWebsiteProject : The website mattercenterdpdemo was not found. Please specify a valid website name.
At C:\MatterCenter\mattercenter-master\tree\master\cloud\src\deployments\Scripts\PublishOnAzure.ps1:47 char:2
+     Publish-AzureWebsiteProject -Name mattercenterdpdemo -Package $We ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Publish-AzureWebsiteProject], CloudException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Websites.PublishAzureWebsiteProject

**Comment by WillTab** [comment]
It looks like Publish-AzureWebsiteProject is an ASM PowerShell command.  I believe the ARM equivalent is Publish-WebApplicationWebSite (https://azure.microsoft.com/en-us/documentation/articles/vs-azure-tools-publish-webapplicationwebsite-windows-powershell-script/) 

The PublishOnAzure.ps1 script is responsible for step 10.   Lines 45 & 47 reference the Publish-AzureWebsiteProject PS Commandlets.  If anyone has the skillset to update this appropriately, your help would be greatly appreciated.

**Comment by amitabhm21** [comment]
Any help from the community for this is greatly appreciated,

**Comment by ctrulove** [comment]
I can take this. I ran into a similar issue during my original install and ended up publishing to Azure using Visual Studio but I will fork and get a scripted solution in place.

**Comment by amitabhm21** [comment]
Thanks Craig ! It's so exciting to see the community maturing. Appreciate your help.

**Comment by NelsonLamprecht** [comment]
Hitting this block today...anyone resolve this yet before I get to? :)
