### ISSUE TITLE
website not found error message

### ISSUE THREAD

**Issue by acumor** [Microsoft/mattercenter#145]
hello,  i'm getting following errors.  please help!

4/17/2016 12:46:44 AM - Creating Redis cache
4/17/2016 12:46:45 AM - Matter Center Redis cache doesn't exist, creating redis cache for Matter Center
New-AzureRmRedisCache : ResourceGroupNotFound: Resource group 'Default-Web-WestUS' could not be found.
At C:\mattercenter-master\mattercenter-master\tree\master\cloud\src\deployments\Scripts\PublishOnAzure.ps1:119 char:27
+ ... CacheInfo = New-AzureRmRedisCache -Location $CacheLocation -Name $Cac ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmRedisCache], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.RedisCache.NewAzureRedisCache

4/17/2016 12:46:47 AM - Redis cache is in process of creation, it will take sometime to complete! Continuing with the rest of the process
4/17/2016 12:46:47 AM - Primary Key:
4/17/2016 12:46:47 AM - Host name:
4/17/2016 12:46:47 AM - Please enter your Azure credentials for Azure service management
4/17/2016 12:46:59 AM - Publishing web service on Azure
Publish-AzureWebsiteProject : The website acu-matterapi.azurewebsites.net was not found. Please specify a valid
website name.
At C:\mattercenter-master\mattercenter-master\tree\master\cloud\src\deployments\Scripts\PublishOnAzure.ps1:45 char:2
+     Publish-AzureWebsiteProject -Name $ExcelValues[1] -Package $Servi ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Publish-AzureWebsiteProject], CloudException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Websites.PublishAzureWebsiteProject

4/17/2016 12:47:00 AM - Publishing web site on Azure
Publish-AzureWebsiteProject : The website acu-matter.azurewebsites.net was not found. Please specify a valid website
name.
At C:\mattercenter-master\mattercenter-master\tree\master\cloud\src\deployments\Scripts\PublishOnAzure.ps1:47 char:2
+     Publish-AzureWebsiteProject -Name $ExcelValues[0] -Package $Websi ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Publish-AzureWebsiteProject], CloudException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Websites.PublishAzureWebsiteProject

4/17/2016 12:47:00 AM - Updating App settings for website
Cannot index into a null array.
False
4/17/2016 12:47:01 AM - Publishing files to Azure or creating Azure Redis cache failed
4/17/2016 12:47:01 AM -
4/17/2016 12:47:01 AM - Reverting till step 9
4/17/2016 12:47:01 AM - Clearing all the previous logs...
4/17/2016 12:47:01 AM - All previous logs cleared

**Comment by ctrulove** [comment]
I ran into this issue as well. If I remember correctly it had to do with have multiple azure subscriptions associated to my account. I made two changes to my [PublishOnAzure.ps1](https://github.com/Microsoft/mattercenter/blob/master/tree/master/cloud/src/deployments/Scripts/PublishOnAzure.ps1) file.

First, I updated the default values specified on lines 37-39. If you do not have multiple subscriptions associated to your account this may be your root cause.

Second, I added the line below directly above line 147:
`Get-AzureRmSubscription -SubscriptionName "My subscription name" | Select-AzureRmSubscription`

I hope this helps.

**Comment by amitabhm21** [comment]
This is due to misconfiguration (Bad configuration values in the config excel).  Please refer to the following issues for resolution.
https://github.com/Microsoft/mattercenter/issues/145 or https://github.com/Microsoft/mattercenter/issues/71
