### ISSUE TITLE
Deployment Step 6 Error: Message: Invalid URI: The URI scheme is not valid.

### ISSUE THREAD

**Issue by fdyn** [Microsoft/mattercenter#146]
Hello,

I am receiving the following error at step 6 when trying to deploy matter center. I have verified the contents of the MCDeploymentConfig.xlxs file are correct, where else should I be looking for an incorrect value?

Thanks,

Ed

20/04/2016 12:43:16 - Step 6: Update resource and config files in build
Updating resource files
Updating Constants.resx file
Message: Invalid URI: The URI scheme is not valid.
Stacktrace:    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Microsoft.Legal.MatterCenter.UpdateAppConfig.UpdateConfig.CheckValueAndReplace(Dictionary`2 updateList, String constantElement, String constantAttribute, List`1 UpdateHardCoded, String tenant, String catalog, String catalogSiteName, String serviceURL, String delveLink, String contentTypeGroupName, String replace, String emptyPlaceHolder, XDocument document)
   at Microsoft.Legal.MatterCenter.UpdateAppConfig.UpdateConfig.UpdateResourceConstants(Dictionary`2 updateList, String constantElement, String constantAttribute, List`1 manifestFile)
   at Microsoft.Legal.MatterCenter.UpdateAppConfig.UpdateConfig.UpdateConstants(Dictionary`2 updateList, String folderName)
Message: Failed to update app schema files
Failed to update resource files
Updating Constants.resx file
Successfully updated Constants.resx file
Updating Constants.resx file
Successfully updated Constants.resx file
Updating Log.resx file
Successfully updated Log.resx file
Successfully updated resource files
Updated Web.config
20/04/2016 12:43:18 - Updating resource and config files in solution failed

**Comment by premchandpl** [comment]
@fdyn I assume in the constant.resx file, in one of the source code project, you haven't update one of the URL. The URL in the constant.resx file is not in a valid format. Can you check all your resx files and check all the url's are valid in those resx files

**Comment by skaggej** [comment]
In the MCDeploymentConfig.xlsx file, check the values of AzureWebsiteName and AzureWebServiceName. I originally had them set to the full domain name as specified in the instructions, but that didn't work. I had to change it to use just the first node of the domain name.
Didn't work: mattercenterui.azurewebsites.net
Did work: **mattercenterui**

The instructions here state "AzureWebsiteName and AzureWebServiceName should just contain the domain name and not an URL." That's a bit misleading and I recommend providing an example.

**Comment by mvosmer** [comment]
I have the same issue here.
Some questions.
What is the difference between AzureWebsiteName and AzureWebServiceName= I have them set both to mattercenterlialis   is this right?

About the constant.resx file, which files do you mean exactly= I have many of them when I search for them. And which URL value is then one mentioned in the above post and how should it be set?

**Comment by skaggej** [comment]
@mvosmer - You'll have two web apps (under app services in the new portal) - one for the UI of the application and another for the service behind it. I created one as mattercenterui.azurewebsites.net and another as mattercenterservice.azurewebsites.net.

**Comment by mvosmer** [comment]
Hi Skaggej, thanks for your tip. I missed the service app. Finally I managed to get the matter center deploy script to finish without errors. I had more wrong URL values in the project which caused this issue I think.
