### ISSUE TITLE
Matter Center Addin/App for outlook rich client

### ISSUE THREAD

**Issue by muradhaider5** [Microsoft/mattercenter#148]
The Addin/App for matter center can not be found in my desktop outlook rich client. The 'SourceLocation' URL in 'Microsoft.Legal.MatterCenter_Outlook.xml' manifest file seems to be correct as it successfully opens the app in browser but i cant find the app in outlook. What could be the issue? Does Outlook needs to be configured with my email?

**Comment by ctrulove** [comment]
The Outlook Add-In should be added through the Exchange Admin Center -> Organization -> add-ins.

![image](https://cloud.githubusercontent.com/assets/9450534/14916870/089ae3bc-0dea-11e6-8081-f8a444d5e2b4.png)

Make sure that you see "Matter Center" or "Matter Center Beta" in this list and that it is enabled for the user that you are testing with. Once this is done, you should be able to see it in the rich client as long as you are viewing an email with a user that it is enabled for.

![image](https://cloud.githubusercontent.com/assets/9450534/14917103/605ee692-0deb-11e6-8577-f0856f45cb61.png)

**Comment by muradhaider5** [comment]
i checked exchange admin center and the addin was provided to 'Specific Users'. i removed the addin, and reloaded the addin manifest to provide it to everyone. Matter Center Beta is now visible with my inbox but add-in doesn't loads. what could be the issue?
![image](https://cloud.githubusercontent.com/assets/7326775/14924798/a847b02a-0e5d-11e6-829b-1e1926b7b3f4.png)
FYI, the app successfully opens in browser if we copy the ''SourceLocation' url from add-in manifest file.

**Comment by ctrulove** [comment]
Does it work in OWA?

**Comment by amitabhm21** [comment]
The current version does not work on OWA. The Matter Center code refactor update would work on OWA. Please take a look at MatterCenter2 branch [https://github.com/Microsoft/mattercenter/tree/mattercenter2] for the updates that were made to include ADAL authentication.

**Comment by NelsonLamprecht** [comment]
Looking at implementing this internally, but should we wait until the SPA version is out?>
