### ISSUE TITLE
New client does not show up on matter creation page

### ISSUE THREAD

**Issue by kawan365** [Microsoft/mattercenter#150]
I created new SharePoint site collection for new client, added new client on Term Store, added matter center app to the site collection, but the new client name does not show up on matter creation page.

**Comment by ctrulove** [comment]
The only thing that determines if a Client **_shows _**in the drop down is whether or not it is in the Clients term set. Can you verify that the Client name has been added to the Clients term set within the MatterCenterTerms group?

![image](https://cloud.githubusercontent.com/assets/9450534/14916638/ced94642-0de8-11e6-9a30-a8315dfd17e8.png)

**Note: **It's existence within this term set allows the item to display in the list but it will not work if you do not set the custom properties.

![image](https://cloud.githubusercontent.com/assets/9450534/14916700/1cbe542e-0de9-11e6-9e25-ccdb3a2e39fe.png)

**Comment by kawan365** [comment]
Thank you for the response. I was able to get it to work after stopping and starting the web app, could be cache issue. However, I still run into permission issue when trying to create a matter (see below). I am using admin accounts when creating the matter, any idea? Thanks!

![capture](https://cloud.githubusercontent.com/assets/18692478/14920494/cba9383e-0de2-11e6-8e76-b5950a924368.JPG)

**Comment by premchandpl** [comment]
@kawan365 Can you check whether a list with the name "Matter Configurations" has been created in the "Catalog" site collection. If not, you need to create that list manually. That information has been mentioned in the deployment document

**Comment by ctrulove** [comment]
@kawan365, @premchandpl  is correct. That message is only displayed if a check for permissions on that list within the client fails. This can happen for two reasons:

1. The list does not exist as @premchandpl is suggesting.
2. The user does not have EditListItems permissions on the list.

FWIW, it is possible to be a tenant admin without having permissions to SharePoint content.

**Comment by kawan365** [comment]
Solved, thanks!. Matter Configurations list was missing.
