### ISSUE TITLE
Publishing the new changes

### ISSUE THREAD

**Issue by rohitjadhav999** [Microsoft/mattercenter#160]
I wanted to change the name of the lists so I made the changes in ProvisionHelperFucntions.cs , but how can I publish it on the existing site collection?

**Comment by ctrulove** [comment]
Can you provide a bit more detail as to which list(s) you are wanting to change the name of and which lines of ProvisionHelperFunctions.cs you have made changes in?

**Comment by rohitjadhav999** [comment]
I wanted to change the name of the calendar list(Internal name) which is currently the matterGuid. You can see it on line number 493.

**Comment by ctrulove** [comment]
Ok, so a couple of things:

1. You will also want to update the MatterLanding.js in the SiteAssets folder. The matter landing page looks for the caledar using the matterGuid. I believe the JS function you will need to update is [retrieveListItems on line 961](https://github.com/Microsoft/mattercenter/blob/master/tree/master/cloud/src/deployments/Static%20Content/Matter%20Center%20Assets/Matter%20Landing%20Assets/scripts/MatterLanding.js).
2. You will need to either support both list names in the function referenced in \#1, or you will need to replace any existing lists manually.
3. You should be able to just build and publish the web project to Azure.

**Comment by rohitjadhav999** [comment]
Can you please help me exactly where I've to make the changes in [retrieveListItems on line 961](https://github.com/Microsoft/mattercenter/blob/master/tree/master/cloud/src/deployments/Static%20Content/Matter%20Center%20Assets/Matter%20Landing%20Assets/scripts/MatterLanding.js)

**Comment by ctrulove** [comment]
The retrieveListItems function works on the basis that the lists associated with a matter have the matter GUID in the internal name. In the function, documentLibraryName is used to reference this GUID. As you can see in the code, it uses that plus a listSuffix to grab the list.

`var listName = documentLibraryName + listSuffix;`

It is important to note that you will need some sort of unique identifier as each client will have multiple matters.

**Comment by rohitjadhav999** [comment]
Hi, I've changed the following line:
_return ("undefined" === typeof (documentLibraryGUID)) ? documentLibraryName : documentLibraryGUID;_

and replaced it with the following:
_return documentLibraryName;_

so I'm getting the value of listname as that name instead of numbers.
But while creating the matter its giving the error:
"_An error has occurred and the matter was not created. Error Code: 2000_"

Is there anything I've to modify apart from the above changes?

**Comment by amitabhm21** [comment]
Is this issue still active @rohitjadhav999 ?

**Comment by rohitjadhav999** [comment]
Yes @amitabhm21 , thanks to @ctrulove
