### ISSUE TITLE
add custom tabs on view matter detail page 

### ISSUE THREAD

**Issue by kawan365** [Microsoft/mattercenter#162]
Hi All,
I would like to add some custom tabs on the view matter detail information (image below), when the new matter is provisioned, the tabs created as below "Matter Profile",  "Matter Description", "New Tap",...

Thanks!

![capture](https://cloud.githubusercontent.com/assets/18692478/14999674/8bbb2628-113f-11e6-90ec-b78e49745f91.JPG)

**Comment by ctrulove** [comment]
The contents of this content editor webpart are generated when the page is loaded by MatterLanding.js. [MatterLanding.js](https://github.com/Microsoft/mattercenter/blob/master/tree/master/cloud/src/deployments/Static%20Content/Matter%20Center%20Assets/Matter%20Landing%20Assets/scripts/MatterLanding.js) is uploaded to the SiteAssets library of you App Catalog site when you install Matter Center. If you are looking to add the tab to an existing installation, just modify the file in the SiteAssets library. If you are trying to add a tab for future installs, update the file that is [part of the Static Content](https://github.com/Microsoft/mattercenter/blob/master/tree/master/cloud/src/deployments/Static%20Content/Matter%20Center%20Assets/Matter%20Landing%20Assets/scripts/MatterLanding.js).

**Comment by kawan365** [comment]
Thank you!

**Comment by kawan365** [comment]
I tried to add a new tab in the MatterLanding.js, code shows three <div> tags, but for some reason the UI only display two tabs, please see below. Any suggestion, thanks!

![capturehtml](https://cloud.githubusercontent.com/assets/18692478/15083296/41f246c2-1381-11e6-8095-bc6ea63d8388.JPG)
![captureui](https://cloud.githubusercontent.com/assets/18692478/15083301/468ce80e-1381-11e6-9179-db138c968486.JPG)

**Comment by ctrulove** [comment]
You will need to do a bit more than add the divs. The styles are applied based upon the specific class names. You will need to update MatterLanding.css to make your tab show. There may need to be some wiring up of the click event to show your content as well.

**Comment by kawan365** [comment]
Two tabs were overlap one another, because their margin-left and width were the same length, fixed that and all tabs show up fine. Thanks.
