### ISSUE TITLE
Accessing documents stored in Matter Center

### ISSUE THREAD

**Issue by alfallouji** [Microsoft/mattercenter#164]
Hi, 

I was wondering if for some reason the Matter Center is not working properly and an end user cannot access it, would it still be possible to access the documents that were previously associated to a matter? Is there any work around to access them or the only way to get to the documents would be through the matter center?

Correct me I am wrong, my understanding is that it all gets stored using sharepoint online capabilities (behind the scene), would the documents previously uploaded be accessible via a sharepoint online folder for example? 

Thanks for your help,

**Comment by ctrulove** [comment]
Matter Center stores the documents in SharePoint document libraries. So, as long as Office 365 and SharePoint Online are available, so will your documents be. Consider the following example:

Client Name: A. Datum Corporation
Client ID: 100002
Client URL: https://tenant.sharepoint.com/teams/100002

Matter Name: Klondike Expansion
Matter ID: 000001
Matter GUID: 2776a60e07232c74ea724ee2fa84cf46

In this example, the "Matter" consists of the following SharePoint components:

Document Library
Name: Klondike Expansion
Url: https://tenant.sharepoint.com/teams/100002/2776a60e07232c74ea724ee2fa84cf46

OneNote Library
Name: Klondike Expansion_OneNote
Url: https://tenant.sharepoint.com/teams/100002/2776a60e07232c74ea724ee2fa84cf46_OneNote

Calendar List
Name: Klondike Expansion_Calendar
Url: https://tenant.sharepoint.com/teams/100002/Lists/2776a60e07232c74ea724ee2fa84cf46_Calendar

Task List
Name: Klondike Expansion_Task
Url: https://tenant.sharepoint.com/teams/100002/Lists/2776a60e07232c74ea724ee2fa84cf46_Task

Matter Landing Page
Url: https://tenant.sharepoint.com/teams/100002/SitePages/2776a60e07232c74ea724ee2fa84cf46.aspx

I hope this helps.

**Comment by ctrulove** [comment]
Hey @alfallouji, just checking to see if this got you what you need. Let us know if you are still having issues.

**Comment by amitabhm21** [comment]
@ctrulove thanks much for the details. Closing this issue.
