### ISSUE TITLE
Create new matter - the guid is not find in term store issue

### ISSUE THREAD

**Issue by mren2006** [Microsoft/mattercenter#168]
While creating a new matter, the ProvisionHelperFunctionUtility class has a function GetWSSId, which tried to call CSOM function to get the term back from the term store: got the exception: cannot find the Guid in the term store. Checked the Guid for terms, all are correct - this prevent creating Matter and Matter landing page in the System.  

Question: the top level of term store group has the structure like this. Would the Group name "MatterCenterTerms" cause the issue? How to fix it?

**Comment by aravindmp** [comment]
Can you check if the client sites have the metadata mapping(Managed Metadata Site Columns ) have been mapped correctly?

**Comment by mren2006** [comment]
checked the mapping it works, will look into source code to see how it added while creating new client sites, this maybe a potential bug.
