### ISSUE TITLE
An error has occurred and the matter was not created. Error Code: -2146233079

### ISSUE THREAD

**Issue by sptrov** [Microsoft/mattercenter#169]
Hey Guys,
We are trying to deploy the matter center and we've gone through many errors which we were able to resolve one by one reading through the other threads around, but we get to the moment where we cant proceed.Everything is deployed and app is enabled and installed , but when we try to create a matter we get the below error
An error has occurred and the matter was not created. Error Code: -2146233079

When I open the network browser tab there is a single request sent to 
.....azurewebsites.net/MatterProvision.svc/CreateMatter

and the response is this one
"{ \"code\": \"-2146233079#|#05-09-2016 09:55:39:7709979\", \"value\": \"The remote server returned an error: (404) Not Found.\" }"

I've found  some people are having similar errors but with different error codes and the fix was usually in the contet types and columns.So we fixed the content type columns of type Managed Metadata and confirmed that the terms are pointing to the correct urls.

I also noticed in the request body that we send an empty SpAppToken and UserID refers to an html input field id(not sure if this should be the expected values or not)
![untitled](https://cloud.githubusercontent.com/assets/17924366/15109974/d97f56e4-15e6-11e6-9fc0-de5ae97347ad.jpg)

Any hints or suggestions are appreciated
Thanks

**Comment by ctrulove** [comment]
Can you check the Azure table storage and provide the error information from there? It should have the method call and line number that where the error is coming from. From there, we should be able to pin point exactly what is going on.

**Comment by sptrov** [comment]
Hi @ctrulove  , would you please tell me how to get that information.
We have a storage account but when I open that in azure , under services I see 
Blobs,Files,Tables and Queues.
We assume it should be probably under tables - but when I click on tables it just lists 3 names (probably table names)
So should we install some additional software like azure management studio or this can be seen through the azure portal ?

Thanks

**Comment by ctrulove** [comment]
You can use [Azure Storage Explore](http://storageexplorer.com/) to connect to your storage account and view the logs.

**Comment by sptrov** [comment]
![untitled](https://cloud.githubusercontent.com/assets/17924366/15173016/2b447ee2-1762-11e6-8861-b1b432a245e1.jpg)

This is what we found with the storage explorer from the last try to create a matter.
Thanks

**Comment by sptrov** [comment]
![untitled](https://cloud.githubusercontent.com/assets/17924366/15182491/7095cc2a-1795-11e6-9042-44c464380591.jpg)

And this picture is with errors from the 3 tables we have.
1st is from Utility table
2nd is from the UI Site  table
3rd is from  Service SIte table

**Comment by ctrulove** [comment]
Hey @sptrov,

Can I get you to check a couple things for me?

1. Verify that the "Matter Configurations" list exists in the Client site collection.
2. Verify that the Client term has the custom properties provisioned and that the values are correct. Specifically we want to verify that the ClientURL property is set to the Client site collection URL.

From best I can tell, the request is making it to the MatterProvision service but it is having issues either getting a client context for the Client site or in verifying that the user has permissions to the Matter Configurations list (which is how it determines if the user has permissions to create a matter).

I hope this helps. Let me know what you find.

**Comment by sptrov** [comment]
Hi @ctrulove  
Thank you for your post.
For point 1 , I was able to verify that "Matter Configurain" can be seen under Recent in the client site collection , though it s not under Site Contents - I still was able to open and see a single record inside of it and verified that the user has a full control on this List.

On point 2 - I am not 100% sure what is the expected so I am uploading a picture and will try to explain what else I see:
![untitled](https://cloud.githubusercontent.com/assets/17924366/15186301/2b8ae02e-17a5-11e6-8657-6428c4e34068.jpg)

I've noticed that Microsoft which is the test client we put in the exel file does have 2 custom properties and Yes the url is valid , I also noticed that the clientID 100001 which is referenced here does not have custom properties at all.

**Comment by ctrulove** [comment]
Ok, those values look correct. Can you run chrome dev tools while tyring to create a matter and send me the request payload for the POST to MatterProvision.svc/CreateMatter? Below is an example of a successful POST:

![image](https://cloud.githubusercontent.com/assets/9450534/15191005/a671afcc-1780-11e6-93c5-f4571f149d9b.png)

**Comment by sptrov** [comment]
Hi @ctrulove 
Our ReuqstPlayload looks similar:
![untitled](https://cloud.githubusercontent.com/assets/17924366/15207376/6d82434e-182e-11e6-991c-33a87ee78262.jpg)

And here are the requests from the network tab:
![untitled1](https://cloud.githubusercontent.com/assets/17924366/15207459/1ee0ff54-182f-11e6-853a-a12f2c4d909e.jpg)

Thanks

**Comment by ctrulove** [comment]
Ok, admittedly we are grasping at straws here. A couple more things to check for:

1. Check for the existence of any matter assets by attempting to access them manually.
  - https://\<tenantname>.sharepoint.com/sites/MS/6bc3c05225ee1dace1851c4a5d48b03
  - https://\<tenantname>.sharepoint.com/sites/MS/6bc3c05225ee1dace1851c4a5d48b03_OneNote
  - https://\<tenantname>.sharepoint.com/sites/MS/Lists/6bc3c05225ee1dace1851c4a5d48b03_Task
  - https://\<tenantname>.sharepoint.com/sites/MS/Lists/6bc3c05225ee1dace1851c4a5d48b03_Calendar
  - https://\<tenantname>.sharepoint.com/sites/MS/SitePages/6bc3c05225ee1dace1851c4a5d48b03.aspx

2. Verify Client Matter Configurations List in proper location
  - https://<tenantname>.sharepoint.com/sites/MS/Lists/Matter%20Configurations

3. Verify permissions. User should have Full Control of the Client site
  - https://\<tenantname>.sharepoint.com/sites/MS/_layouts/15/user.aspx

Let me know what you find.

**Comment by sptrov** [comment]
Thank you @ctrulove ,
Assuming that https://<tenantname>.sharepoint.com/sites/MS/ is one of our excel client site collection(this site was created through the deployment) - 
1.None of these exist - 404 NOT FOUND
2.That is on place with single configuration value
3.User who submits the Matter and the one chosen in the people pickers are part of the Fill control owners group

Thanks

**Comment by ctrulove** [comment]
Can you check the value of your Provision_Matter_App_URL in the Microsoft.Legal.MatterCenter.Utility Constansts.resx file? It should be pointed to the MatterCenter app in your App Catalog. For instance if your app catalog is located at:

` https://<tenantname>.sharepoint.com/sites/apps`

your Provision_Matter_App_URL should be:

`https://<tenantname>.sharepoint.com/sites/apps/MatterCenter`

**Comment by sptrov** [comment]
Hi @ctrulove ,
we get over this already ,it was correct in the Microsoft.Legal.MatterCenter.Utility Constansts.resx file , but when we got to azure deployed files we found that it points to https://sharepoint.com/sites/catalog/ProvisionDMSMatter  , so fixed that in Azure.(We found this possible issue in another issue/thread - https://github.com/Microsoft/mattercenter/issues/52 )

Thanks

**Comment by ctrulove** [comment]
@sptrov, at this point my next step would be to do remote debugging of the MatterProvision service to see if we can step through as the request is being made to determine what is causing the issue. It feels like a cop out but I am out of ideas.

**Comment by sptrov** [comment]
Hi @ctrulove ,
Thanks for your answer again , We will have a look how we can debug and provide more meaningful information.
But what about the urls you asked me to try access like -
https://<tenantname>.sharepoint.com/sites/MS/6bc3c05225ee1dace1851c4a5d48b03
....
..

We have none of these(404 NOT FOUND), is it the expected behavior or this content/sites should exist. 
Thanks

**Comment by ctrulove** [comment]
My appologies, I should have been more clear. Those URLs were the lists that Matter Center was going to provision for the request you showed me the post data for. If they had existed, I would have had you delete them and try again. 

Matter Center stores the documents in SharePoint document libraries. Consider the following example:

Client Name: A. Datum Corporation
Client ID: 100002
Client URL: https://tenant.sharepoint.com/teams/100002

Matter Name: Klondike Expansion
Matter ID: 000001
Matter GUID: 2776a60e07232c74ea724ee2fa84cf46

In this example, the "Matter" consists of the following SharePoint components:

Document Library
Name: Klondike Expansion
Url: https://tenant.sharepoint.com/teams/100002/2776a60e07232c74ea724ee2fa84cf46

OneNote Library
Name: Klondike Expansion_OneNote
Url: https://tenant.sharepoint.com/teams/100002/2776a60e07232c74ea724ee2fa84cf46_OneNote

Calendar List
Name: Klondike Expansion_Calendar
Url: https://tenant.sharepoint.com/teams/100002/Lists/2776a60e07232c74ea724ee2fa84cf46_Calendar

Task List
Name: Klondike Expansion_Task
Url: https://tenant.sharepoint.com/teams/100002/Lists/2776a60e07232c74ea724ee2fa84cf46_Task

Matter Landing Page
Url: https://tenant.sharepoint.com/teams/100002/SitePages/2776a60e07232c74ea724ee2fa84cf46.aspx

**Comment by sptrov** [comment]
Since we were stuck and didn't know what to do to overcome the issue , we decided to download the latest build and start fresh(we were not using the latest- from around a month ago).
So after having few issues , that we were already familiar how to fix we finished with a working demo of Matter Center.

Hope all these posts can help someone to go.
Many thanks to @ctrulove 

Stoyan

**Comment by amitabhm21** [comment]
Thanks @ctrulove
