### ISSUE TITLE
When the new designed solution will be available?

### ISSUE THREAD

**Issue by mren2006** [Microsoft/mattercenter#175]
The new designed solution Re-Architecture document states using new ASP.NET 5 and other technologies - Just wanted to get some idea about the roadmap: When the Microsoft team plans to release the new solution?

**Comment by amitabhm21** [comment]
The details around the feature enhancements that we are working on in the next 3-4 months will be available here: https://github.com/Microsoft/mattercenter/milestones 

We have completed our [Milestone1](https://github.com/Microsoft/mattercenter/milestones/MatterCenter%20Code%20Refactor) and you can start playing with the code here: 
https://github.com/Microsoft/mattercenter/tree/mattercenter2

Once we are done with milestone 2 (Tentatively end of September) we will merge this to the main MatterCenter branch, Please do keep looking at the wikis as we will be adding more information there as well.
