### ISSUE TITLE
An error has occurred and the matter was not created. Error Code: -900000001

### ISSUE THREAD

**Issue by Skipper52** [Microsoft/mattercenter#178]
Hello everyone, I'm strugling some time with deployment of Matter Center and going around same errors all the time:
1. someteimes when I open matter center page I get totally unresponsive page - clicking any link on page nothing happens
2. when first error does not occur, and when I try to create new matter, I get to the 3rd step and when clicked "Create" after some time I got error "An error has occurred and the matter was not created. Error Code: -900000001"

I've done everything like it is written in Deployment guide except that my O365 admin is not admin in Azure subsrciption (I opened trial accounts and that could not be done)

Any help please.
![1](https://cloud.githubusercontent.com/assets/19323309/15209484/94aa504e-1831-11e6-8b5c-5a05b8ce88f2.jpg)
![2](https://cloud.githubusercontent.com/assets/19323309/15209487/993a3296-1831-11e6-85ef-005d9f489eb4.jpg)

I've searched some other issues that had beed reported here, and most commonly discussed about and it looks good.

![3](https://cloud.githubusercontent.com/assets/19323309/15216001/704f3c22-1855-11e6-8221-ef9589d72c78.jpg)

![4](https://cloud.githubusercontent.com/assets/19323309/15216006/739487d4-1855-11e6-9574-47989ef9da01.jpg)

Thanks
RGS

**Comment by ctrulove** [comment]
HI @Skipper52, it looks like you have connected to the storage account with Azure Storage Explorer and have posted the logs. I would have expected to see an entry in the log with error code -900000001. Can you verify that you have checked all of the tables and there is no entry with this value?

You should also be able to view the logs in real time and determine the exact entries that are created as part of your request. Can you verify that the logs posted above are created at the time you are receiving the error?

**Comment by Skipper52** [comment]
Hi @ctrulove, thank You for answer
There is no entry in log with error code 900000001. Entry on the top was created when I got that error (I intentionally left old entries in order to see all the errors which are being repeated).

I tried to replicate problem and got a new error code -2146233088 and a lot of log entries (those which are selected in the picture)
![5](https://cloud.githubusercontent.com/assets/19323309/15220715/c032a3d8-1868-11e6-8893-c5e32e570ce9.jpg)

![6](https://cloud.githubusercontent.com/assets/19323309/15220773/fde5919a-1868-11e6-9d1a-8a7e05501102.jpg)

I have only two tables, and second one is below
![7](https://cloud.githubusercontent.com/assets/19323309/15220776/01658fbe-1869-11e6-960e-78ecf61b5a73.jpg)

**Comment by ctrulove** [comment]
@Skipper52, from these logs it looks like it is never submitting a request to create the matter. Can I have you do the following?

1. Open up Matter Center in Chrome
2. Press F12 to open the developer tools
3. Go to the Resources tab in developer tools
4. Expand Cookies and select your site (should be the url of your UI site)
5. Does the refreshToken have a value? If so, it should look something like this: ![image](https://cloud.githubusercontent.com/assets/9450534/15247816/9e66b452-18e4-11e6-8701-a494586b6d36.png)
6. If this looks right, continue to the "Create a new Matter" portion of the site
7. Fill out section 1 and click Next
8. Fill out section 2 and click Next
9. Go back to developer tools and, under the Resources tab, expand out Local Storage
10. Select your site and then post the following things to the thread:
    - Screenshot of the Local Storage values
    - Value of oPageOneData
    - Value of oPageTwoData
11. Click Create and Notify and post the results of what happens if they are different than previous posts.

**Comment by Skipper52** [comment]
Hi @ctrulove, there is refresh token and all other parameters:

Local storage:
![localstorage](https://cloud.githubusercontent.com/assets/19323309/15250295/6203b862-1924-11e6-9e07-f9f727106270.jpg)


`oPageOneData: {"ClientValue":[{"ClientName":"TestClient","value":"https://MYTENANT.sharepoint.com/teams/TestClient","ClientId":"100001"}],"ClientId":"100001","MatterTitle":"dsgfdsg","MatterId":"123","MatterDescription":"sfsdfs","ContentTypes":[{"DataValue":"0","DataDocumentTemplate":"Copyright","DataAssociatedDocumentTemplate":"Patent","DocumentTemplateText":"Copyright (1)","DataPracticeGroup":"Litigation","DataAreaOfLaw":"Intellectual Property","DataFolderNamesPG":"Emails; Documents","DataFolderNamesAOL":"Emails;","DataFolderNamesSAL":"Emails; Documents","DataisNoFolderStructurePresent":"FALSE","DataDisplayName":"Copyright","DataPracticeGroupId":"d5201d30-6ea0-4a91-a424-f9d1f55de2ea","DataAreaOfLawId":"f5a1462b-20fa-4027-bcd3-4e4c33ae9ad5","DataSubAreaOfLawId":"37fbbcbe-e82e-46e0-9818-6c2c699dd43c"}],"matterMandatory":true}`


`oPageTwoData: {"BlockedSiteUsers":["admin@MYTENANT.onmicrosoft.com","jane.carness@MYTENANT.onmicrosoft.com","admin@MYTENANT.onmicrosoft.com"],"ConfCheckCond":1,"ConfCheckCondBy":{"Text":"Kevin Carnes (admin@MYTENANT.onmicrosoft.com);","DataResolved":true},"CheckPerfOn":"05/11/2016","ConflictIdent":"True","BlockUsers":{"Text":"Jane Carness (jane.carness@MYTENANT.onmicrosoft.com);","DataResolved":true},"BoolSecureMatter":"True","AssignPermission":[{"NameList":"Kevin Carnes (admin@MYTENANT.onmicrosoft.com); ","DataResolved":true,"Role":"Responsible Attorney","Permission":"Full Control"}]}`


After clicking Create & Notify, I got this, and same log entry as earlier:
![result](https://cloud.githubusercontent.com/assets/19323309/15250515/73fc8020-1925-11e6-97d7-e7eaefb0d927.jpg)


I also debugged it via remote debugger and found out that it doesn't retrieve any content type in SharePointHelper.cs on [this](https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.client.web.contenttypes.aspx) method invoke

**Comment by ctrulove** [comment]
Can you verify that the Content Types have been published? This is a manual step that must be done and is outlined in Appendix C of the [Matter Center Build and Deployment Guide](https://github.com/Microsoft/mattercenter/blob/master/tree/master/cloud/docs/Matter%20Center%20Build%20and%20Deployment%20Guide.docx).

For the options that you have chosen you will need to pay particular attention to the Copyright content type and make sure that it has been successfully published to the https://MYTENANT.sharepoint.com/teams/TestClient site collection.

**Comment by Skipper52** [comment]
Hi, 
I did that from apendix C, but now when I checked Client site collection - there isn't any Conten type published (I don't know could it be deleted when I redeployed matter center). I've republished them agan and I will wait until it propagates and then I will check does it works and I will report that. 

Thank You once more @ctrulove

**Comment by Skipper52** [comment]
Hi @ctrulove and others

Republishing ContetTypes solved one part of problem - i've managed to create matters, and that works  when we don't have another problem. 

The other problem is when we open matter center add-on, it displays an error:
![matter_error](https://cloud.githubusercontent.com/assets/19323309/15425806/12213f74-1e8b-11e6-819e-d2ab159b63aa.png)

This happens about 20% of the time. It turned out that _CheckPermissionOnList_ method throws an exception when trying to retrieve SendMail list from SharePoint (method: [ExecuteQuery](https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.client.clientcontext.executequery.aspx), line: 660, file: Microsoft.Legal.MatterCenter.DataLayer.Lists.cs). The exception message is "_Value cannot be null. Parameter name: AppSiteDomainPrefix_". Since ExecuteQuery method doesn't have parameter named AppSiteDomainPrefix, it must be some method that ExecuteQuery calls, but we cannot access ExecuteQuery method's source code, so this was as far as we could debug it. It is possible that we have some invalid data in our ClientContext, but it is confusing to me that it works 80% of the time, and only breaks occasionally.

Thanks in advance
RGS

**Comment by ctrulove** [comment]
From the screenshot it looks like you are doing this from OWA. Do you receive the same error from Outlook rich client?

**Comment by Skipper52** [comment]
@ctrulove I have same error when opening MC from Outlook rich client.

**Comment by amitabhm21** [comment]
Is this issue still active @Skipper52 ?

**Comment by Skipper52** [comment]
You can close the ticket. Thanks

**Comment by premchandpl** [comment]
@Skipper52 Closing the ticket. Also matter center has been upgraded with new features. Upgrade to MatterCenter2
