### ISSUE TITLE
New SharePoint Client programming Framework

### ISSUE THREAD

**Issue by mren2006** [Microsoft/mattercenter#179]
with the new announcement about SharePoint Framework Graph, File API and Site API, is there any design change for Matter Center for the next release, beside the milestone and re-Architecture document in wiki?

**Comment by amitabhm21** [comment]
The Re-Architecture also includes a WebAPIs for Matter Center [https://github.com/Microsoft/mattercenter/wiki/Matter-Center-Web-API-Documentation]. With the matter center code refactor update the WebAPI's are utilized to perform the operations needed. 
This ensures that any framework changes (o365) have the least impact on matter center core implementation. Making it simpler to maintain code and manage forks.
Over the next few months we will work to update the Matter Center WebAPIs to consume the new Sharepoint client API's that were announced. 
As we get closer to this release we will publish our Milestone details to the community.
