### ISSUE TITLE
Deployment Step Six: StartIndex cannot be less than zero.

### ISSUE THREAD

**Issue by kspizzle** [Microsoft/mattercenter#188]
I've built the solution without major issue, I had some issues at this step previously (the same as another poster) that said about URI invalid, but that seems to have been fixed by going through Constants.resx files. However, I've now got a new error message at the same place, here is the red text:

 Step 6: Update resource and config files in build
Updating resource files
Updating Constants.resx file
Message: **StartIndex cannot be less than zero.**
**Parameter name: startIndex**
Stacktrace:    at System.String.Substring(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex)
   at Microsoft.Legal.MatterCenter.UpdateAppConfig.UpdateConfig.CheckValueAndReplace(Dictionary`2 updateList, String constantElement, String constantAttribute, List`1 UpdateHardCoded, String tenant, String catalog, String catalogSiteName, String serviceURL, String delveLink, String contentTypeGroupName, String replace, String emptyPlaceHolder, XDocument document)
   at Microsoft.Legal.MatterCenter.UpdateAppConfig.UpdateConfig.UpdateResourceConstants(Dictionary`2 updateList, String constantElement, String constantAttribute, List`1 manifestFile)
   at Microsoft.Legal.MatterCenter.UpdateAppConfig.UpdateConfig.UpdateConstants(Dictionary`2 updateList, String folderName)
Message: Failed to update app schema files

My amateur guess is that there is an issue when updating the strings in Helper Utilities then Microsoft.Legal.MatterCentre.UpdateAppConfig, I can find some of these values but I can't see what I might need to change to make StartIndex have a value of 0 or greater. Any assistance is greatly appreciated!

**Comment by ctrulove** [comment]
Hello @kspizzle,

Can you check the value of App_Redirect_URL in your [$/tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.SharePointAppWeb/App_GlobalResources/Constants.resx](https://github.com/Microsoft/mattercenter/blob/master/tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter.SharePointAppWeb/App_GlobalResources/Constants.resx)? It should look something like:

`https://tenant.sharepoint.com/sites/apps/_layouts/15/appredirect.aspx`

where https://tenant.sharepoint.com/sites/apps is the URL of your App Catalog.

**Comment by kspizzle** [comment]
Hi @ctrulove,

Thanks for getting back to me. Yes my App_Redirect_URL follows the same format as your example. I rebuilt, and am still getting the error that "startindex" cannot have a value less than zero

**Comment by kspizzle** [comment]
Does anyone have any further ideas on what my be causing this issue?

**Comment by amitabhm21** [comment]
The deployment in MC2 release is now significantly simplified. The app configuration is now automated in Azure.

Please get the latest version of the code from master.
