### ISSUE TITLE
Post Deployment WebDashboard Issues

### ISSUE THREAD

**Issue by mm43838** [Microsoft/mattercenter#194]
We are getting the following on the webdashboard.aspx page, behavior seems the same in Chrome and IE:
 
https://txhhsmc.sharepoint.com/teams/microsoft/SitePages/webdashboard.aspx
 
Sorry, something went wrong
An unexpected error has occurred.
TECHNICAL DETAILS
Troubleshoot issues with Microsoft SharePoint Foundation.
Correlation ID: 00000000-0000-0000-0000-000000000000
Date and Time: 5/20/2016 7:14:51 AM

WebDashboard never loads, just continually says "Working on it".  

Please advise.

**Comment by amitabhm21** [comment]
Would you please look at the application logs (web app in azure) and check if you see any exceptions ?

**Comment by amitabhm21** [comment]
Is this issue still active @mm43838 ?
