### ISSUE TITLE
Step 10 problem

### ISSUE THREAD

**Issue by rafaelqueiroz89** [Microsoft/mattercenter#197]
Hi, I'm not sure what to do in Step 10, can someone help me out? Thanks.

**Comment by WilsonReddy** [comment]
1. Open windows power shell
2. Navigate to <solution location>/Deployments/Scripts/
3. Run Deploy.ps1
4. Provide credentials when it prompts.

**Comment by rafaelqueiroz89** [comment]
@WilsonReddy  thanks a lot for your response! Now I'm getting an exception on Running Azure Site and Service Check, but it seems that the setup continues well..

![1st error](https://cloud.githubusercontent.com/assets/19557655/15544468/2fa8476c-226f-11e6-9996-4bbd8ab6e2f3.jpg)


Also, after this error On Step 1b and Step 3 too, how I solve this? 

![2nd error](https://cloud.githubusercontent.com/assets/19557655/15544549/848f2aac-226f-11e6-8869-6c5e6ef74686.jpg)


Thanks a lot.

**Comment by WilsonReddy** [comment]
proceed with your deployment if script successfully installs web site, service and outlook apps. Did you get any error after step 4 in script execution?

**Comment by amitabhm21** [comment]
@rafaelqueiroz89 closing this issue. If you need further help please feel free to reopen the issue.
