### ISSUE TITLE
Deployment completes but add in doesn't work

### ISSUE THREAD

**Issue by samrutur** [Microsoft/mattercenter#200]
I followed the deployment guide and was able to deploy and no errors came up. When I view an email from the Outlook web the add-in Matter Center Beta shows up but when I click on it I get the error attached in File1. Then I click retry the error in file 2 comes up. Click 'Start' and the screen comes up but the buttons don't do anything. See file3. I see a bunch of errors on the browser console. I see the same set of errors when I launch the app directly from the site. See File4 for the errors. Can you help? Do you think any files are missing? Thank you.

![file4](https://cloud.githubusercontent.com/assets/19577299/15552410/3f9f62f4-2288-11e6-8eb5-ab3b439b2d0d.PNG)

![file3](https://cloud.githubusercontent.com/assets/19577299/15552381/132fb660-2288-11e6-8d57-0d6f4dc9befd.PNG)

![file2](https://cloud.githubusercontent.com/assets/19577299/15552283/b84bc68a-2287-11e6-85d8-02048250e617.PNG)

![file1](https://cloud.githubusercontent.com/assets/19577299/15552236/86fb78e6-2287-11e6-9ef7-293ee7ea6ef3.PNG)

**Comment by samrutur** [comment]
Another update to my issue. In the Azure log table I see these two rows of errors repeated.
Error 1:
**Value cannot be null.Parameter name: context**
**Method: Page_Load**
**Line: 77**
======================================
Error 2:
**"mattercentersvc.azurewebsites.net" is not the intended audience "c5c383f0-4d26-4082-ba4d-611f5bcfc9a6/mattercenterui.azurewebsites.net@793491f2-9648-4f13-a07e-60f27bdf8b73"**
**Method: SetConstantsResponse**
**Line: 188**

**Comment by premchandpl** [comment]
The issue may be with your web.config file of the sharepoint app web project.

<add key="HostedAppHostNameOverride" value="xxxxxxx.azurewebsites.net" />

For the HostedAppHostNameOverride, the value has to be sharepoint app web azure web sites and not service azure web sites. Can you confirm this?

-Premchand

**Comment by samrutur** [comment]
You are right. I have the service azure web site and not the UI site. Do I have to run the deploy PowerShell script again after updating this or is there a way to update it directly on the Azure site to make this work?

**Comment by premchandpl** [comment]
If you have VS 2013 or later, you can deploy the same from VS or you can deploy it from powershell, by copying the updated web.config file to the deployment folder

**Comment by samrutur** [comment]
Thank you ! I ran through the deployment script successfully and the add in launches from Outlook web but no action occurs when I click "Matters" or 'Documents" links. In the browser console, I am seeing these errors in screen shot. Am I missing any configuration? Please assist. In Azure log table I see entries
**Message: Value cannot be null. Parameter name: context
Method: Page_Load
Line : 77**

 ![file5](https://cloud.githubusercontent.com/assets/19577299/15576832/cd66c592-2327-11e6-942f-4fb6302b9307.PNG)

**Comment by samrutur** [comment]
Just to close this out, I republished all content types and waited for about 15 hours. Everything started to work fine. Thanks for the help!
