### ISSUE TITLE
Roadmap and plan to address priorities?

### ISSUE THREAD

**Issue by amalabey** [Microsoft/mattercenter#203]
Can someone help me understand the roadmap for addressing issues listed in PRIORITIES.MD? I can see there is another branch called 'mattercenter2'. Is this the one that is addressing these issues? If so, what is the roadmap and when will it likely to be ready for use?

**Comment by amitabhm21** [comment]
New Roadmap and priorities are updated. Please see https://github.com/Microsoft/mattercenter/blob/mattercenter2/PRIORITIES.md
