### ISSUE TITLE
403 Error on the settings page

### ISSUE THREAD

**Issue by lindendaniels2** [Microsoft/mattercenter#207]
Have just finished all 13 steps of the MC deployment doc and checking if it is working. In the sharepoint site, I click on the MC Settings App (Which redirects to https://customermattercenter1.azurewebsites.net/pages/settings.aspx?SPHostUrl=https%3A%2F%2Fdmspoc%2Esharepoint%2Ecom%2Fsites%2Fcatalog2&SPLanguage=en%2DUS&SPClientTag=0&SPProductNumber=16%2E0%2E5312%2E1215&SPAppWebUrl=https%3A%2F%2FDmsPoc%2D5fab549f793bdf%2Esharepoint%2Ecom%2Fsites%2Fcatalog2%2FMatterCenter?&clientdetails=https://dmspoc.sharepoint.com/sites/contoso1$|$Contoso). 
It gets stuck. The JS loading circle keeps spinning and the page never loads. 

Checking the network tab of the developer tools, I see the following page is getting Error 403 Forbidden: https://outlook.office365.com/owa/SuiteServiceProxy.aspx?suiteServiceUserName=GlobalAdmin%40DmsPoc.onmicrosoft.com&suiteServiceReturnUrl=https%3a%2f%2fdmspoc.sharepoint.com%2fsites%2fcontoso1%2fSitePages%2fsettings.aspx&returnUrl=https%3a%2f%2fdmspoc.sharepoint.com%2fsites%2fcontoso1%2fSitePages%2fsettings.aspx&silent=1&f=255&MSPPError=-2147217396

Not sure if this is the issue or not. I dont see anyone else reporting this.

**Comment by amitabhm21** [comment]
This looks like a configuration issue in the web.config  Please check your web.config
