### ISSUE TITLE
An unexpected error has occured

### ISSUE THREAD

**Issue by lindendaniels2** [Microsoft/mattercenter#216]
Testing the Matter Center deployment, the following erro occurs when using the Matter Center SharePoint App:

An unexpected error has occured while performing your last action. Please try again. If this issue persist, please contact your administrator.
Error Code: NA
Timestamp: NA

This error is displayed if clicking on the menu in the MatterCenter app and selecting Matters.

**Comment by WilsonReddy** [comment]
Have you published content as mentioned in deployment document Appendix C?

Sent from my Windows Phone
________________________________

**Comment by amitabhm21** [comment]
Incorrect configuration value in web.config.

Closing this issue,
