### ISSUE TITLE
Matter Center Dashbord

### ISSUE THREAD

**Issue by kawan365** [Microsoft/mattercenter#234]
I am having difficulty to get all matters to show up on “My Matters” and “All Matters” taps; only matters from one client show up on these two tabs. All new matters have been created with no error; they show up on their clients’ sites collections…but only matters from one client (first client created) show on the "My Matters" and "All Matters". 

Differently from these above tabs, “Pinned Matters” works correctly, it shows all the matters which have been pinned from all clients.

What am I missing? Please advise.

**Comment by amitabhm21** [comment]
The "My Matters" and "All Matters" views are based on the SPO search.
Looks like the index has not run on the client sites that were created after the first client. Usually there is a delay of 15-20 minutes max.

If this is still an issue you should try manually re-indexing the sites.
https://support.office.com/en-us/article/Manually-request-crawling-and-re-indexing-of-a-site-a-library-or-a-list-9afa977d-39de-4321-b4ca-8c7c7e6d264e?ui=en-US&rs=en-US&ad=US

**Comment by amitabhm21** [comment]
I am assuming this issue is resolved. Please feel free to re-open if needed.
