### ISSUE TITLE
Helper Utilities source is missing

### ISSUE THREAD

**Issue by PieterVeenstra** [Microsoft/mattercenter#24]
The source of the helper Utilities is missing.

I can find the .exe files for this but not the source in mattercenter / tree / master / cloud / src / deployments / Scripts / Helper Utilities /

**Comment by LeoConniff** [comment]
We are currently finalizing our review and preparations to bring this code into our solution.  We will update this issue once we have merged that code into the repository.  Thanks!

**Comment by amitabhm21** [comment]
The source for Helper Utilities are now added to the Repo. 
https://github.com/Microsoft/mattercenter/tree/master/tree/master/cloud/src/Helper%20Utilities
