### ISSUE TITLE
Matter centar doesnt register ribbon with the new One drive

### ISSUE THREAD

**Issue by seranus** [Microsoft/mattercenter#245]
I just installed matter center and it took me a few days to realize that One Drive missing ribbon features where due to Office365 redirecting me to a page https://TENNAT-my.sharepoint.com/personal/MY USER/_layouts/15/onedrive.aspx QUERY, seems like a new page, 
instead of https://TENNAT-my.sharepoint.com/personal/MY USER/_layouts/15/start.aspx#/Documents/Forms/All.aspx?LoadProfile=TRUE

It should be at least noted in the deployment guide.

**Comment by amitabhm21** [comment]
This is a known issue and goign forward with the new one drive this feature will be deprecates. Now sharepoint document libraries have onedrive Sync feature out of the box. The out of the box feature will be used by matter center.
