### ISSUE TITLE
Error in step 8 is ignored

### ISSUE THREAD

**Issue by PieterVeenstra** [Microsoft/mattercenter#25]
After the following error the installer simply continues:

18/12/2015 14:36:11 - Step 8: Update App files for SharePoint and OneDrive Ribbon Apps
18/12/2015 14:36:12 - Getting parent Content Type ID
18/12/2015 14:36:15 - Parent Content Type ID retrieved
The variable cannot be validated because the value  is not a valid value for the parentContentTypeId variable.
At C:\Git\mattercenter\tree\master\cloud\src\deployments\Scripts\UpdateAppPackage.ps1:148 char:9
+         $parentContentTypeId = ""
+         ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], ValidationMetadataException
    + FullyQualifiedErrorId : ValidateSetFailure
 
The variable cannot be validated because the value  is not a valid value for the parentContentTypeId variable.
At C:\Git\mattercenter\tree\master\cloud\src\deployments\Scripts\UpdateAppPackage.ps1:148 char:9
+         $parentContentTypeId = ""
+         ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], ValidationMetadataException
    + FullyQualifiedErrorId : ValidateSetFailure

**Comment by PieterVeenstra** [comment]
This problem occurs when the .app files aren't in the correct deployment folder. A check should probably be added to make sure that the .app files exist.

**Comment by LeoConniff** [comment]
This has been flagged as a bug for us to prioritize fixing.  Both the issue where the install continues and the check for existence.  Thanks!

**Comment by LeoConniff** [comment]
Also, in order to provide clarity to those viewing this issue later, the deployment guide at the time of writing does not include steps to package the OneDrive Ribbon app and include it in the SharePoint App folder created in the deployment folder.
