### ISSUE TITLE
SendMail list missing/Cannot manage users

### ISSUE THREAD

**Issue by lindendaniels2** [Microsoft/mattercenter#251]
The symptoms seem similar to #89 as the sendmail list is missing. Also cannot see the Manage Users link in the Matter details page. 

When debugging the Matter details page I can see 404 errors for this url: https://dmspoc.sharepoint.com/sites/Catalog2//ProvisionDMSMatter/_api/Web/lists/getbytitle('SendMail')/EffectiveBasePermissions

I have checked Microsoft.Legal.MatterCenter.UpdateAppConfig.exe.config and Microsoft.Legal.MatterCenter.UpdateListPermissions.exe.config. They already seem to have the correct setting (ProvisionMatterAppName/MatterCenter)

As the customer is already evaluating the tenant, what files would I need to change on Office 365/Azure web sites? And how to manually create the SendMail list?

**Comment by SwapnilM92** [comment]
Referring to issue #89 and updates provided above it seems that app has been deployed successfully but it is referring to invalid list URL.
This can be rectified by updating MatterLanding.js file. 
To resolve this issue, 

a.	Navigate to https://dmspoc.sharepoint.com/sites/Catalog2 and open Site Assets library.
b.	Inside Site Assets library go to Matter Center Assets > Matter Landing Assets > Scripts > MatterLanding.js
c.	Download existing MatterLanding.js file and take a backup. 
d.	In MatterLanding.js file, update the 'oGlobalConstants.sAppName' value from 'ProvisionDMSMatter' to 'MatterCenter'.
e.	Save the file and replace it inside '/Matter Landing Assets/Scripts' folder on SharePoint.
f.	Reload the Matter details page with Ctrl + R to avoid caching and check if issue is resolved.

**Comment by sunnymistry** [comment]
@lindendaniels2 after following steps provided above did your issue get resolved.

**Comment by amitabhm21** [comment]
hey @lindendaniels2 closing this issue as a fix/resolution is provided. Please do open this again if needed.
