### ISSUE TITLE
'Default-Web-WestUS' 

### ISSUE THREAD

**Issue by PieterVeenstra** [Microsoft/mattercenter#26]
During Step 10 I'm getting an error about a resource group. 'Default-Web-WestUS' my Azure site has a group 'Default-Web-NorthEurope' There doesn't seem to be a setting for this.

18/12/2015 14:36:15 - Step 10: Publishing files to Azure/IIS
18/12/2015 14:36:15 - Please enter your Azure credentials for Azure Resource Management
18/12/2015 14:37:09 - Creating Redis cache
18/12/2015 14:37:10 - Matter Center Redis cache doesn't exist, creating redis cache for Matter Center
Resource group 'Default-Web-WestUS' could not be found.
18/12/2015 14:37:11 - Please enter your Azure credentials for Azure service management

18/12/2015 14:37:11 - Please enter your Azure credentials for Azure service management
18/12/2015 14:47:33 - Publishing web service on Azure
Publish-AzureWebsiteProject : The website bluesourcematters.azurewebsites.net was not found. Please specify a valid website name.
At C:\Git\mattercenter\tree\master\cloud\src\deployments\Scripts\PublishOnAzure.ps1:45 char:2
+     Publish-AzureWebsiteProject -Name $ExcelValues[1] -Package $Servi ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Publish-AzureWebsiteProject], CloudException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Websites.PublishAzureWebsiteProject

18/12/2015 14:47:35 - Publishing web site on Azure
Publish-AzureWebsiteProject : The website bluesourcematters.azurewebsites.net was not found. Please specify a valid website name.
At C:\Git\mattercenter\tree\master\cloud\src\deployments\Scripts\PublishOnAzure.ps1:47 char:2
+     Publish-AzureWebsiteProject -Name $ExcelValues[0] -Package $Websi ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Publish-AzureWebsiteProject], CloudException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Websites.PublishAzureWebsiteProject
 
18/12/2015 14:47:38 - Updating App settings for website
Cannot index into a null array.
False
18/12/2015 14:47:41 - Publishing files to Azure or creating Azure Redis cache failed
18/12/2015 14:47:41 - 
18/12/2015 14:47:41 - Reverting till step 9
18/12/2015 14:47:41 - Clearing all the previous logs...
18/12/2015 14:47:41 - All previous logs cleared

**Comment by LeoConniff** [comment]
It looks like the main issue encountered was that the website was not found in Azure.  The scripts will detect the azure site and pull the location and resource group from that site to create the Redis Cache.  To change the defaults for these values, you can modify lines 38 and 39 in the PublishOnAzure.ps1 file.  

To fix the error with your site not being found, you can change lines 28 and 29 in the deployment config Excel file, on the config tab, to be just the name of the web app in Azure.  IE, if the site is located at https://ExampleSite.azurewebsites.net (this is the value for lines 7/8 respectively), then the name of that web app is going to be ExampleSite (the value for lines 28/29 respectively).

**Comment by eekels** [comment]
I am running into the same error. The second error that is, the fact that my website cannot be found in Azure. I am sure the websites are there. Also, the Test-AzureName -Website  $AzureSite in the PreRequisitesScript.ps1 gives a True, so the names of my websites in the Excel file are correct. Anyone any idea? Here's the error:

10/01/2016 20:55:48 - Step 10: Publishing files to Azure/IIS
10/01/2016 20:55:48 - Please enter your Azure credentials for Azure Resource Management
10/01/2016 20:57:12 - Creating Redis cache
10/01/2016 20:57:14 - Please enter your Azure credentials for Azure service management
10/01/2016 20:57:24 - Publishing web service on Azure
Publish-AzureWebsiteProject : The website sushi-matterservice was not found. Please specify a valid website name.
At C:\Projects\MatterCenter\deployments\Scripts\PublishOnAzure.ps1:45 char:2
+     Publish-AzureWebsiteProject -Name $ExcelValues[1] -Package $Servi ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Publish-AzureWebsiteProject], CloudException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Websites.PublishAzureWebsiteProject

10/01/2016 20:57:26 - Publishing web site on Azure
Publish-AzureWebsiteProject : The website sushi-mattercenter was not found. Please specify a valid website name.
At C:\Projects\MatterCenter\deployments\Scripts\PublishOnAzure.ps1:47 char:2
+     Publish-AzureWebsiteProject -Name $ExcelValues[0] -Package $Websi ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Publish-AzureWebsiteProject], CloudException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Websites.PublishAzureWebsiteProject

10/01/2016 20:57:26 - Updating App settings for website
Cannot index into a null array.
False
10/01/2016 20:57:28 - Publishing files to Azure or creating Azure Redis cache failed

**Comment by eekels** [comment]
Never mind... Select-AzureSubscription to the rescue. It could help to set the right subscription as default smile emoticon (feel bit stupid now, although still find it weird that Test works on non-default subscriptions too, but Publish doesn't)

**Comment by DaveyDoo** [comment]
I am seeing a similar error, but I have verified that I am pointing to the correct subscription.
