### ISSUE TITLE
The variable cannot be validated because the value  is not a valid value for the parentContentTypeId variable.

### ISSUE THREAD

**Issue by PieterVeenstra** [Microsoft/mattercenter#27]
During step 8 I'm getting some errors:

18/12/2015 15:49:50 - Step 8: Update App files for SharePoint and OneDrive Ribbon Apps
18/12/2015 15:49:50 - Getting parent Content Type ID
18/12/2015 15:49:53 - Parent Content Type ID retrieved
The variable cannot be validated because the value  is not a valid value for the parentContentTypeId variable.
At C:\Git\mattercenter\tree\master\cloud\src\deployments\Scripts\UpdateAppPackage.ps1:148 char:9
+         $parentContentTypeId = ""
+         ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], ValidationMetadataException
    + FullyQualifiedErrorId : ValidateSetFailure
 
The variable cannot be validated because the value  is not a valid value for the parentContentTypeId variable.
At C:\Git\mattercenter\tree\master\cloud\src\deployments\Scripts\UpdateAppPackage.ps1:148 char:9
+         $parentContentTypeId = ""
+         ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], ValidationMetadataException
    + FullyQualifiedErrorId : ValidateSetFailure

**Comment by LeoConniff** [comment]
Closing issue as the error is being tracked in issue #25
