### ISSUE TITLE
Cannot contact site at the specified URL https://xxx.sharepoint.com/teams/<ClientName>.

### ISSUE THREAD

**Issue by kspizzle** [Microsoft/mattercenter#278]
Hi guys,

I am up deploying Matter Center and it gets to step 14/15 (Provisioning Site Collection) and I get the following error messages:

19/07/2016 11:01:32 - Step 14: Creating Site Collection(s)
19/07/2016 11:01:32 - Provisioning Site Collection
Exception occurred while creating site collection: The site url https://xxx.sharepoint.com/teams/<ClientName> contains the reserved character '<' at index 0.
Creating Matter Center Interfaces group.
Exception occurred while creating group: Cannot contact site at the specified URL https://xxx.sharepoint.com/teams/<ClientName>.
Exception occurred while assigning permissions: Cannot contact site at the specified URL https://xxx.sharepoint.com/teams/<ClientName>.
Exception occurred while assigning permissions: Cannot contact site at the specified URL https://xxx.sharepoint.com/teams/<ClientName>.
Message: Cannot contact site at the specified URL https://xxx.sharepoint.com/teams/<ClientName>.
Stacktrace:    at Microsoft.SharePoint.Client.ClientContext.GetFormDigestInfoPrivate()
   at Microsoft.SharePoint.Client.ClientContext.EnsureFormDigest()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.Legal.MatterCenter.CreateSiteCollection.Program.ActivateFeature(String clientUrl, SharePointOnlineCredentials credentials)
19/07/2016 11:01:47 - Creating site collection failed

I'm not sure where, or even if, I needed to enter <ClientName> somewhere but I'm pretty stuck at this point. It looks like the same error rears its head for provisioning Settings.aspx:

Successfully provisioned the matter center page: settings.aspx
Exception while Provisioning Matter Center page: Cannot contact site at the specified URL https://xxx.sharepoint.com/teams/<ClientName>.

Any help would be most welcome!

**Comment by kspizzle** [comment]
This is so close to being deployed, this is killing me! Any help would be great!

**Comment by ctrulove** [comment]
Can you check to see if any of the URLs in your config file are hyperlinks?
If so, you should be able to right click and remove the hyperlink.

**Comment by kspizzle** [comment]
Hi ctruelove, 

Thank you so much for getting back to me. Which config file are you referring to?

**Comment by ctrulove** [comment]
MCDeploymentConfig.xlsx

**Comment by amitabhm21** [comment]
@kspizzle Is thsi issue still open ?

**Comment by amitabhm21** [comment]
Closing this issue. Please feel free to open if there are further questions.
