### ISSUE TITLE
E4 Required?

### ISSUE THREAD

**Issue by BSchorr-RST** [Microsoft/mattercenter#28]
The installation documentation seems to say that Office 365 E4 is required...two questions:

1. I had heard it only required E3. Do we really need to upgrade everybody to E4?

2. E4 is being discontinued. Does that mean the requirement is going to be E5?

**Comment by PieterVeenstra** [comment]
I'm currently trying to install this on E3. The installer is now up to step 11 without any problems. I had  to do a lot of debugging and I had quite a few errors to get past.
Did you try to install this solution on E3? I will let you know how I'm getting on.

**Comment by BSchorr-RST** [comment]
I haven't tried it yet, but hope to over the next week or so.

**Comment by LeoConniff** [comment]
An E3 subscription to Office 365 will be sufficient to install Matter Center in the environment.  If future enhancements to Matter Center include PowerBI or Delve functionality, then an E5 subscription will be necessary to gain access to those features.  We will update our documentation to include this information.  Thanks!
