### ISSUE TITLE
Technical Specification Doc - Client limit

### ISSUE THREAD

**Issue by RRFreemanArchitect** [Microsoft/mattercenter#294]
According to [https://support.office.com/en-us/article/SharePoint-Online-software-boundaries-and-limits-8f34ff47-b749-408b-abc0-b605e1f6d498?ui=en-US&rs=en-US&ad=US&fromAR=1](Office 365 Boundaries) each tenant can have 500,000 site collections yet the documentation says only 2000 clients per tenant.  We need an explanation of the reasoning for this or a fix here.

**Comment by amitabhm21** [comment]
The matter center supports 2000 clients per site collection (internally we represent each client as a sub site of a site collection). The limit of sub sites per site collection is 2000 and hence this limitation.
However a client can be "split" into multiple site collections to overcome this limit.
