### ISSUE TITLE
reference to beta

### ISSUE THREAD

**Issue by PieterVeenstra** [Microsoft/mattercenter#30]
In the appinstall.ps1 

line 46:
$FriendlyName = @("Matter Center Beta")

Should be:
$FriendlyName = @("Matter Center")

line 380:
$AppName = @("Matter Center Beta")
should be
$AppName = @("Matter Center")

and line 
$AppInfo = Get-SPOAppInfo -Name $AppName

should be
$AppInfo = Get-SPOAppInfo -Name $AppName | Where {$_.Name -eq $AppName}

The where is needed for the second fix as Get-SPOAppInfo doesn't filter on exact matches. It does a contains filter.

**Comment by sunnymistry** [comment]
We are currently finalizing our review and preparations to bring this code into our solution. We will update this issue once we have merged that code into the repository. Thanks!

**Comment by sunnymistry** [comment]
Hello Pieter, We have updated the logic for AppInstall.PS1 and merged it with the repository. If you can now verify this fix and see if you are still running to the challenge of app not getting installed correctly.
