### ISSUE TITLE
$AppInstance.Status  is stuck on Initialized

### ISSUE THREAD

**Issue by PieterVeenstra** [Microsoft/mattercenter#31]
in AppInstall.ps1 my AppInstance is stuck on Initialized rather than Installing. Therefore the script is not waiting for the app to be installed in this part of the script:

 while($AppInstance.Status -eq "Installing")
                     {                        
					   Show-Message -Message "." -Type ([MessageType]::Success) -Newline $false
                       Start-Sleep -s 10
                       $context.Load($AppInstance)
                       $context.ExecuteQuery()
                     }
                     
                     if($AppInstance.Status -eq "Installed") {
						 Show-Message -Message ([String]::Concat($AppInstance.Title, " has been successfully loaded and installed")) -Type ([MessageType]::Success)
                     }
                     else {                        
						Write-Log $ErrorLogFile "Failed to install apps to SharePoint."
                     }

-----

[DBG]: PS C:\Git\mattercenter\tree\master\cloud\src\deployments\Scripts\Helper Utilities>> $AppInstance

AppPrincipalId     : i:0i.t|ms.sp.ext|19e59e66-4640-471c-9e60-efd7dc4f9e88@ac15dc91-a1c5-4c0a-8c88-a194b32af5aa
AppWebFullUrl      : 
Id                 : 3160aa38-1144-4e21-b708-4d8cfabcc079
ImageFallbackUrl   : 
ImageUrl           : 
InError            : False
StartPage          : 
PackageFingerprint : {209, 253, 19, 21...}
ProductId          : ac9e3be9-85e5-4078-94c3-efea9675ba32
RemoteAppUrl       : 
SettingsPageUrl    : 
SiteId             : 0103b090-8bc6-490e-9b47-d8b56a3d89e6
Status             : Initialized
Title              : Matter Center
WebId              : a71dee1c-0987-4025-aba4-ddb8bf9d076c
Context            : Microsoft.SharePoint.Client.ClientContext
Tag                : 
Path               : Microsoft.SharePoint.Client.ObjectPathIdentity
ObjectVersion      : 
ServerObjectIsNull : False
TypedObject        : Microsoft.SharePoint.Client.AppInstance

**Comment by LeoConniff** [comment]
We are trying to reproduce this error on our end.  I just wanted to confirm that you are still experiencing this problem when trying to install the app.

**Comment by PieterVeenstra** [comment]
Hi Leo, 

I just tried this again but no luck:

AppPrincipalId     : i:0i.t|ms.sp.ext|19e59e66-4640-471c-9e60-efd7dc4f9e88@ac15dc91-a1c5-4c0a-8c88-a194b32af5aa
AppWebFullUrl      : 
Id                 : ce20cc27-53a5-4c8b-886c-ad2c70caa020
InError            : False
StartPage          : 
RemoteAppUrl       : 
SettingsPageUrl    : 
SiteId             : 0103b090-8bc6-490e-9b47-d8b56a3d89e6
Status             : Initialized
Title              : Matter Center
WebId              : a71dee1c-0987-4025-aba4-ddb8bf9d076c
Context            : Microsoft.SharePoint.Client.ClientContext
Tag                : 
Path               : Microsoft.SharePoint.Client.ObjectPathIdentity
ObjectVersion      : 
ServerObjectIsNull : False
TypedObject        : Microsoft.SharePoint.Client.AppInstance

**Comment by DaveyDoo** [comment]
I'm pretty sure this is the same bug I just reported.  In the MatterCenter/App.Manifest.xml, there is a space after MatterCenter. I removed that space and the deployment succeeded.

**Comment by sunnymistry** [comment]
Hello All, Yes this was indeed the case. We have updated the AppManifest file in the codebase to reflect the app name correctly.
