### ISSUE TITLE
Error on Matter Center Home on web app ui

### ISSUE THREAD

**Issue by quennethks** [Microsoft/mattercenter#312]
Why do I keep seeing this error? What part of the source code to I need to check? Please help. 

![screenshot 48](https://cloud.githubusercontent.com/assets/20659375/17401541/cd130fb6-5a80-11e6-93a1-a0fd430b89f9.png)

**Comment by NelsonLamprecht** [comment]
Getting the same issue after doing a a deploy. I am also getting an error 2000 on the home.aspx page. Looks like something to do with logging. I don't see any tables in my storage account so not sure how they get there....

**Comment by WilsonReddy** [comment]
You can create storage account and tables. Then try. refer issue #108 for additional details.
