### ISSUE TITLE
Build and Deployment Guide has no Step 7

### ISSUE THREAD

**Issue by StationaryDave** [Microsoft/mattercenter#32]
On Page 19: 5.	Create a folder called SharePoint App and copy the file created in Step 7 to the newly created folder

There is no Step 7 anywhere in the document.

**Comment by PieterVeenstra** [comment]
Hi Dave, simply copy the .asp files that are created during the packaging step. I had the same issue yesterday. The documentation is currently being reviewed.

**Comment by LeoConniff** [comment]
Thanks for pointing this out.  This version appears to be missing the column that includes those step numbers.  Step 7 should be the step that packages the SharePoint app.  Also, that step should incluce packaging the OneDrive Ribbon app and including that in the SharePoint App folder as well.  There will be an update this week with fixes to some of the issues we have encountered so far.

**Comment by StationaryDave** [comment]
Thanks!

**Comment by johnnycardy** [comment]
@PieterVeenstra - I think (at least I hope) you mean .app files.

**Comment by PieterVeenstra** [comment]
@johnnycardy yes .app. a bit of an annoying typo.

**Comment by DaveyDoo** [comment]
I am attempting to forge ahead even though the documentation hasn't been updated.
Assuming Step 7 is:  package the SharePoint app. Package the OneDrive Ribbon app and include that APP file SharePoint App folder as well.
I am able to package the OneDrive Ribbon app and add that to the SharePoint App folder.  Is that all?  Is there an additional file or files that need to go in the SharePoint App folder?

**Comment by johnnycardy** [comment]
No additional files - just those two. You're a harp player! High five :-)

**Comment by DaveyDoo** [comment]
Thanks.
That brings me to my next question:  The SharePointAppWeb project doesn’t offer a Publish | Package the add-in option option.  Do I have the wrong project?
Dave

**Comment by johnnycardy** [comment]
Yes. `Microsoft.Legal.MatterCenter` is the app project.

**Comment by DaveyDoo** [comment]
Right! Got it!

**Comment by ajmeradivyesh** [comment]
We are working on this issue and solution for this will be available with the next release
