### ISSUE TITLE
Build and Deployment Guide LogTableName setting

### ISSUE THREAD

**Issue by StationaryDave** [Microsoft/mattercenter#33]
There are two constants named LogTableName that (I guess) should be renamed to a table in the Azure storage service, but there are no instructions about setting up any such tables in the Azure storage service. 
Or will these perhaps be set up by the PowerShell script?

**Comment by PieterVeenstra** [comment]
Just to help you a bit I added this to the excel and I got my site fully created by the installation script. The logtable was also created for me.


TenantURL	https://bluesourcematterssite.sharepoint.com
ContentTypeHubURL	https://bluesourcematterssite.sharepoint.com/sites/contentTypeHub
CatalogSiteURL	https://bluesourcematterssite.sharepoint.com/sites/AppCatalog
TenantAdminURL	https://bluesourcematterssite-admin.sharepoint.com
UISiteURL	https://bluesourcematterssite.azurewebsites.net
ServiceSiteURL	https://bluesourcematterssite.azurewebsites.net
ClientID	19e59e66-5640-471c-9e60-efd7dc4f9e88
ClientSecret	q95Qp4vDZglZyiLJObBRhS1HiVcL7vTeBHm4ebuYkLc=
ApplicationInsightAppId	9516e8d7-e40e-45b8-ad87-48131b3763fb 
SharePointApplicationInsightAppId	9516e8d7-e40e-45b8-ad87-48131b3763fb 
CloudStorageConnectionString	DefaultEndpointsProtocol=https;AccountName=bluesourcematterssitelog;AccountKey=HkzHkkufBYFyzRpNkOyTUdWxnZBuvtQfdC9tL6FWR+6dHTEbau7V8xpdNHbG3Mw1O/xinTKcQWr3V1lR2jIz2g==
LogTableName	bluesourcematterssitelog
ExchangePowerShellURL	https://ps.outlook.com/powershell
Overwrite_Config_Property	Email Only
AzureWebsiteName	bluesourcematterssite
AzureWebServiceName	bluesourcematterssite
DelveLink	https://bluesourcematterssite-my.sharepoint.com/_layouts/15/me.aspx?q=

**Comment by LeoConniff** [comment]
Pieter is mostly correct that our scripts will create the necessary tables.  The scripts will populate the utility resource file on our service site with the proper connection string and log table name.  Whenever an event is triggered that would require logging, our service will create the table if it doesn't already exist.  If you try to visit the site before the application has been trusted/deployed (by visiting the home page for example) an error will be thrown and those tables will be created.

**Comment by StationaryDave** [comment]
Thanks!

**Comment by StationaryDave** [comment]
Pieter:
Thanks for posting your settings.  I notice that your UI site and Service site have the same name.  I was under the impression that two sites needed to be set up in Azure, one for the UI and one for the Service.  Therefore, I named one site XYZui.azurewebsites.net and the other XYZservice.azurewebsites.net.
Since it appears neither of us have gotten Matter Center up and working, it remains to be seen which of us is right.

**Comment by LeoConniff** [comment]
Dave:
You are correct.  The service and the ui site should be separate azure sites.  You will need two separate sites in order for the deployment to be successful.
