### ISSUE TITLE
Matter Name (Length) - Error Code:-2146233088

### ISSUE THREAD

**Issue by TacitIT** [Microsoft/mattercenter#330]
We've experienced an issue where matter names above a certain length (approximately 40 characters) cause a "Error Code:-2146233088".

Reducing the matter name to less than 40 characters resolves the issue.

Not sure if this is related to overall path length.

**Comment by sunnymistry** [comment]
Yes this is associated with the overall path length.

**Comment by premchandpl** [comment]
@TacitIT Closing this ticket. Let us know if more information is required
