### ISSUE TITLE
Deleting Matters

### ISSUE THREAD

**Issue by TacitIT** [Microsoft/mattercenter#350]
Is there a correct way to delete old/test matters?

Just curious if there are any specific lists that need to be taken into consideration?

**Comment by sunnymistry** [comment]
Following are the steps to delete old/test matters:
a. Delete Document library, OneNote library, Task List, Calendar from the site collection
b. Delete the Matter Landing Page from Site Pages library in the site collection

Once above is done, you might want to re-index the site collection. This will ensure that the Matter (and its related documents) are remove from the list soon.
