### ISSUE TITLE
Creating and Registering new Client

### ISSUE THREAD

**Issue by wizneeraj** [Microsoft/mattercenter#352]
Please let me know the steps to follow to create a new client and register the same in Matter Center

**Comment by sramangit** [comment]
Appendix A in the documentation (Matter Center Build and Deployment Guide.docx) details the steps required to create and register a new client.

**Comment by darkocolak** [comment]
Is this something that can be done grammatically form matter center application? Like add new page where we can create client?

**Comment by wizneeraj** [comment]
Thanks for the response

**Comment by amitabhm21** [comment]
This is part of the Roadmap. Please look at the [Priorities](https://github.com/Microsoft/mattercenter/blob/master/PRIORITIES.md) . "Automate new client creation". We invite the community  to contribute towards this feature.
