### ISSUE TITLE
New Matters from Newly Registered Clients not showing up

### ISSUE THREAD

**Issue by quennethks** [Microsoft/mattercenter#357]
Hi there,

I've successfully deployed Matter Center. 

Now whenever I add new matters, the new clients appear in the client list. And I'm able to create new matters.

The problem is they don't appear in the All Matters tab. Though I can pin them, I doesn't show up in All Matters and they're not "searchable" (the new matters from new clients).

I know it takes time before they show up in All Matters but its almost 3 days. And I doubt it takes that long. I'm not getting any error on my azure storage logs. 

I've attached screenshots for your reference. 

Any help would be appreciated. Thanks.

![screenshot 51](https://cloud.githubusercontent.com/assets/20659375/17956545/2503752a-6abd-11e6-9be7-f80ac35c7905.png)
![screenshot 52](https://cloud.githubusercontent.com/assets/20659375/17956575/72feb46a-6abd-11e6-862d-a1e6927f2e43.png)

**Comment by amitabhm21** [comment]
@quennethks it looks like the index on your SPO tenant is not getting updated. You could try doing the following to force a full craw on the site.

1. On the site, click Settings > Site Settings.
2. Under Search, click Search and offline availability.
3. In the Reindex site section, click Reindex site. 
4. A warning appears, click Reindex site again to confirm. 
The content will be re-indexed during the next scheduled crawl.

However its odd that this should happen if a force re-crawl fixes the issue you might want to investigate your SPO tenant.

**Comment by quennethks** [comment]
@amitabhm21 

I've tried it. But the problem's still there. How long does it take for reindexing to finish? It's been a day now since I've reindeer my site collections.

I also tried deploying matter center to another tenant, added new clients and new matters. And the same problem occurred. 

Is there additional steps I need to take in adding a new client aside from the deployment manual?

**Comment by amitabhm21** [comment]
It should not take more that an hour for the re-index to finish, Would you go to site search and search for the matter name ? It should return you the site created for your matter, If this works then we can focus on debugging matter center code and eliminate SharePoint search.

**Comment by quennethks** [comment]
@amitabhm21 

Yes, when I used the SharePoint search, the matters not showing up in the Matter page seem to be found.

Which part of the code do you think I need to check to fix this issue? Thanks

**Comment by amitabhm21** [comment]
@quennethks is this still an issue?

**Comment by quennethks** [comment]
Yes, still haven't been able to resolve it.

**Comment by amitabhm21** [comment]
Have you checked the error log table in Azure? Do you see any exceptions?

**Comment by quennethks** [comment]
I checked the error log tables and this is what appears
![screenshot 54](https://cloud.githubusercontent.com/assets/20659375/18536082/686d3970-7b2c-11e6-840f-71c481b49cac.png)

But, I believe this error is a result of not being logged in to the tenant. Because when I logged in the Outlook app, it doesn't seem to show up.

Not sure if this affects the search.

**Comment by iHeartRobinson** [comment]
I'm having the same issue.

I'm able to pin and search for newly created matters, but I can't get them to show up in the All Matters or My Matters list. Have attempted to force the site index already.

Any updates on this?

Many thanks!

**Comment by WilsonReddy** [comment]
@iHeartRobinson Go to https://<<tenant name>>.sharepoint.com/_layouts/15/manageresultsources.aspx?level=sitecol and click on mattercenter. Then from url get source id. You should replace %2D in sourceid valu.  you need to update this value in web app appsettings searchresouredid.

**Comment by iHeartRobinson** [comment]
@WilsonReddy Thanks Wilson! I was able to locate the Source ID, and replaced the %2D values in the Source ID.

Having a bit of trouble finding where to update SearchResourceID in the Web App Settings. Any tips on this?

Thanks so much.

**Comment by WilsonReddy** [comment]
@iHeartRobinson go azure portal-> go to your web site application settings. you will find search results source id. reopen this issue if still you find difficulty.

**Comment by Vasanth1981** [comment]
Hi,
I having same issue with Matter Center 1, the new client's Matter is not appearing in All Matter Or My Matters. But after the Pinned the Matters, then its appearing only on Pinned Matters. Any idea?

**Comment by premchandpl** [comment]
@Vasanth1981 Have you done the steps mentioned in this issue such as re-indexing the site collections? If this is still not working, we can have live session and I will help you to resolve the issue. Let me know if this helps

My skype id is - premchand_76@hotmail.com

**Comment by Vasanth1981** [comment]
Yes. I re-indexed the site site collections. But still the new client is not appearing on the My Matters or All Matters.

**Comment by premchandpl** [comment]
@Vasanth1981 Now of the matters are appearing in "All matters"  and "My Matters" or only specific matters?

**Comment by premchandpl** [comment]
@Vasanth1981 I mean "None of the matters are appearing in "All matters" and "My Matters" or only specific matters?"

**Comment by Vasanth1981** [comment]
The only Matters which created by Client 2 (which is configured manually)

**Comment by Vasanth1981** [comment]
@premchandpl , @WilsonReddy 
Looks like, I have fix the issue. I have edit Result Source (Matter Center) and add the new Client URL in the Query Builder. Now the Matters is created with new client is appearing on the My Matters and All Matters.

{searchTerms} AND ( path: "https://XXXX.sharepoint.com/sites/Client1" OR Path: "https://XXXX.sharepoint.com/sites/Client2")

Please let me know if this is correct approach.

Regards,
Vasanth.

**Comment by premchandpl** [comment]
@Vasanth1981 I think it is just sufficient to provide the path up to your root site that is,  https://XXXX.sharepoint.com.

But the disadvantage is, if that root site collection is used for other business purposes, then the matter search will show the documents which are not related to matter center

Tomorrow if you add any new client (Site Collection) again you have to update the new site collection to that path

Can you try to that and let me know

**Comment by shijov** [comment]
None of my new matters were showing up because the Matter Center result source had the first client sitecollection path. I updated it with {searchTerms} AND ( path: "https://XXXX.sharepoint.com"), it works now.

@WilsonReddy @premchandpl @Vasanth1981  Thank you guys.
