### ISSUE TITLE
Office & Outlook deployment

### ISSUE THREAD

**Issue by Vasanth1981** [Microsoft/mattercenter#358]
How to avoid to deploying the Office & Outlook(Exchange) App to all users.

**Comment by sunnymistry** [comment]
For Outlook, you can restrict the app getting added to all user by 2 ways:
a. During automated deployment, provide specific list of users in the configuration excel file. With this it will only add the app to specific users specified
b. Once the app is deployment and then if you want to restrict the access, in that case you can following steps give here: https://technet.microsoft.com/en-us/library/jj943752(v=exchg.150).aspx

For Office, unfortunately there is no way to not show the app in Office Catalog.
