### ISSUE TITLE
Error Code 2000 after sucessful deployment of Matter Center

### ISSUE THREAD

**Issue by ashishshukla1183** [Microsoft/mattercenter#360]
Hi,

We are getting  "Unexpected error. Error code : 2000" after completing all the deployment steps.
Attached is the image with error description. ![error code 2000](https://cloud.githubusercontent.com/assets/10719499/17983910/8eb70ce0-6ad4-11e6-904d-07aa6c8abb21.png)

As part of deployment steps, we completed the following steps:
1.	Executed successfully all deployment scripts downloaded from Matter Centre pnp site, which completed the following:
•	Web application and Web Service Deployment to Azure
•	SharePoint Site Collections , Content Hub ,SharePoint  Configuration Lists 
•	Azure Cache Settings
•	User Permissions
2.	Manually updated all the configurations mentioned in the Matter Center Configuration Deployment guide.

While troubleshooting the issue, we are unable to find any logs created for this error. Also, we are unable to find Log Table in Azure  which it should had been created with deployment script. 

Please advise if we are doing something wrong. If its of any help, please refer the attached document. I am seeing the same error on every screen.

[MatterCenterErrors.docx](https://github.com/Microsoft/mattercenter/files/437964/MatterCenterErrors.docx)

Thanks in advance.

**Comment by amitabhm21** [comment]
@ashishshukla1183 . Based on the errors it looks like the Client ID/client secret is not configured properly in the Web.Config of the matter center web application and the service.

Would you please double check the Client ID/client secret values?
![settings webconfig](https://cloud.githubusercontent.com/assets/13580071/18371504/9b91a13a-75e9-11e6-8ce5-76ac6d910fc9.png)

**Also if this is a new deployment I would encourage you to get the latest version of Matter Center from the master branch**, The architecture has significantly changed with Web APIs and configuration management. The deployment is much simpler as well.

Let me know once you check the Client ID/client secret in the web.config files.

**Comment by ashishshukla1183** [comment]
Thanks Amitabh for the suggestions. Client Id and Client secret are properly configured as you indicated.
So, is there anything else supposed to be verified? 
If not do you suggest deploying the latest code base rather than looking to resole the existing issues?

**Comment by amitabhm21** [comment]
If this is a new deployemet i would recommed that you deploy the latest code base.

**Comment by ashishshukla1183** [comment]
I will deploy the latest code and let you know if i face any issues.

**Comment by amitabhm21** [comment]
Thanks @ashishshukla1183. I am closing this issue so that we can focus in the new deployment
