### ISSUE TITLE
Error during deploy.ps1 script

### ISSUE THREAD

**Issue by jamvandermeer** [Microsoft/mattercenter#37]
Running the deploy.ps1 script I get this error. can't find the cause is it in the XLSX file?

Reading parameters from Excel file...
Exception calling "LoadFile" with "1" argument(s): "An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information."
Method invocation failed because [System.Boolean] does not contain a method named 'Split'.
At F:\vs2015\projects\mattercenter-master\tree\master\cloud\src\deployments\scripts\PreRequisitesScript.ps1:178 char:5
+     $ExcelValues = $ExcelValues.Split(";")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

You cannot call a method on a null-valued expression.
At F:\vs2015\projects\mattercenter-master\tree\master\cloud\src\deployments\scripts\PreRequisitesScript.ps1:185 char:9
+     if ("false" -eq $ExcelValues[1].ToLowerInvariant()) {
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by PieterVeenstra** [comment]
This happens if you run the script and keep the excel file open. Close the excel file and then rerun the script.

**Comment by LeoConniff** [comment]
There are three reasons that this error can occur:
 1.  The Excel file is still open (mentioned by Pieter)
 2.  You do not currently have [Office Developer Tools for Visual Studio](http://www.microsoft.com/web/handlers/WebPI.ashx?command=GetInstallerRedirect&appid=OfficeToolsForVS2015) installed.  Without developer tools, the library that we use will not be available.
 3.  If you used the download as zip option from GitHub, as opposed to closing the repository, Windows may block the files.  As a result, the scripts and exes will be treated as coming from an external source and won't execute for security reasons.  To make sure all files are unblocked, right click the zip file, go to properties and there will be a button to unblock the file if it is blocked.  After unblocking the zip file, extract the files like normal.
