### ISSUE TITLE
MC2 - SP App project is not in the VS solution

### ISSUE THREAD

**Issue by luismanez** [Microsoft/mattercenter#382]
The project for the SP App itself (Microsoft.Legal.MatterCenter), is not included in the main solution. Also, v2 Deployment guide is not saying anything about the SP App file, which is required later for the Deployment scripts, as far as I can see in the PS code and Helper EXE files...

I think the deployment guide for version 2 is not OK, and should include more required information, or is impossible to make a succesful deploy from that document...

Thanks.

**Comment by WilsonReddy** [comment]
The SharePoint App is not required in MC2. The app deployment script reference is removed from SharePoint development script.  Please refer Wiki to understand complete changes from MC1.0 to MC2.

Sent from my Windows Phone
________________________________

**Comment by luismanez** [comment]
Thanks for your reply @WilsonReddy 
I read all the docs related with V2, and I undestand that now is an Azure App, so no need to register the app in SP. However, in the AppInstall.ps1 file (in the Master branch) is still looking for the "Sharepoint App Folder"

```
# SharePoint App Folder name
$SharePointAppFolder = "SharePoint App"
```

and seems will fail if the folder doesn't exist, as Deploy.ps1 script is calling the AppInstall.ps1 script

Am I wrong? will work if we just create the folder and leave it empty?

**Comment by amitabhm21** [comment]
Projects not required by MC2 are removed from the solution,
The SharePoint app is no longer needed and any references to the app from the deployment scripts have been removed as well.
