### ISSUE TITLE
ClientID & ClientSecret 

### ISSUE THREAD

**Issue by PieterVeenstra** [Microsoft/mattercenter#39]
In the excel file there is a client id and a secret. Which Client Id and secret is this referring to? Shouldn't the 2 SharePoint add-ins have both their own secret and clientId?

**Comment by LeoConniff** [comment]
Only the main Matter Center SharePoint app needs to be registered through the SharePoint app registration.  The OneDrive app does not need to be registered as it does not follow the same self hosted model as the main application.
