### ISSUE TITLE
Workflow.xaml file cannot be opened in Microsoft.Legal.MatterCenter project 

### ISSUE THREAD

**Issue by harrychen1** [Microsoft/mattercenter#404]
The error is:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.SharePoint.WorkflowExtensions, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.SharePoint.WorkflowExtensions, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

Do we need this project for the matter center? It seems VS 2015 does not support workflow 2013
https://social.technet.microsoft.com/Forums/projectserver/en-US/f64c51b6-6e11-4957-b288-2df2db1053c2/visual-studio-2015-and-sharepoint-2013-workflow?forum=sharepointgeneral?

Any suggestions?

Thanks.
Harry

**Comment by amitabhm21** [comment]
The SharePoint app and workflow is no longer needed. This is now handled by an Azure web job. The references to the projects and installs are removed as well.

Would you please pull the latest updates from master and try this again?

**Comment by octavioccl** [comment]
But what are the options now if I want to develop some workflow for sharepoint 2016 from Visual Studio, The only way now is using SharePoint designer?

**Comment by premchandpl** [comment]
@octavioccl The new version matter center does not use any workflows. We have simplified the architecture  and have used azure web jobs for matter center scenarios

For sharepoint online as told by you, you can user sharepoint designer. Closing this as we are not using workflows in matter web app

As @amitabhm21 explained, get latest code and try the new matter web app solution
