### ISSUE TITLE
Deployment Error

### ISSUE THREAD

**Issue by mbayo** [Microsoft/mattercenter#419]
Getting the following error. 

![capture1](https://cloud.githubusercontent.com/assets/171925/18560593/53749e5a-7b4a-11e6-8ec0-9a3a0759d538.JPG)

**Comment by premchandpl** [comment]
@mbayo Can you check the url's that you have specified in the "MCDeploymentConfig.xlsx" in the sheet name called config
In the config sheet, <TENANTNAME> has to be replaced with your tenant name and "teams/<CATALOGNAME>" has to be replaced with catalog url where it has been created. If it has created at managed path "teams" use teamd and if it has been created at "sites" managed path use that managed path

Also before running the powershell script, the "MCDeploymentConfig.xlsx" should be closed

**Comment by mbayo** [comment]
I did replace the tenant name and remove Teams/ from all the urls.

**Comment by amitabhm21** [comment]
Were you successfully able to build the Microsoft.Legal.MatterCenter.HelperUtilities project?
This is the Step 3 of the Deploying Sharepoint assets section in the Build and deployment guide. 

Would you please confirm that the deployment utilities are copied into deployments\scripts\Helper Utilities folder ?

**Comment by mbayo** [comment]
@amitabhm21 yes, I was able to successfully build the Microsoft.Legal.MatterCenter.HelpUtilities project using VS. Yes, they are.

**Comment by WilsonReddy** [comment]
@mbayo Ensure powershell window opened as administrator.  Here is the sample values for excel. can you check your excel values?
Config sheet:
![image](https://cloud.githubusercontent.com/assets/9116038/18687675/1253bc36-7f36-11e6-8e7a-9ca2eb5212b6.png)
Create_Group sheet:
![image](https://cloud.githubusercontent.com/assets/9116038/18687735/4fb86626-7f36-11e6-9f70-759bdec04648.png)
Client_Config:
![image](https://cloud.githubusercontent.com/assets/9116038/18687918/13bd8d76-7f37-11e6-9f31-ba91b5f6ae46.png)

**Comment by WilsonReddy** [comment]
![image](https://cloud.githubusercontent.com/assets/9116038/18687936/2b38e84c-7f37-11e6-9ebc-cc8801d58a9b.png)

**Comment by amitabhm21** [comment]
@mbayo Closing this issue as there is a solution posted. Feel free to open again if needed.
