### ISSUE TITLE
Standards

### ISSUE THREAD

**Issue by PieterVeenstra** [Microsoft/mattercenter#42]
A lot of the PowerShell scripts do not follow the standard of Verb-....

https://technet.microsoft.com/en-us/library/ms714428(v=VS.85).aspx

e..g DisplayErrorInfo, CheckSharePointVersion, ScriptRoot

Also the guidelines document doesn't include PowerShell guidelines.

**Comment by sunnymistry** [comment]
Thanks for the feedback! We will add this request to our backlog.
