### ISSUE TITLE
Error when creating matter with punctuation in the Matter Description field

### ISSUE THREAD

**Issue by mobiledevco** [Microsoft/mattercenter#422]
If you use any punctuation in the Matter Description field you will get an error "Please enter a valid text which contains only alphanumeric characters, spaces & hyphen.
![create matter error w punctuation](https://cloud.githubusercontent.com/assets/2348834/18594612/eb732ebe-7c0e-11e6-8e4c-219ac327be1e.JPG)

**Comment by amitabhm21** [comment]
Hi @mobiledevco. The matter description is stored as a property bag in the backend SharePoint schema. So we have some validation on this field to exclude special characters that are not honored as property bag values.
However **"."** should be allowed. Tagging this as a bug. 

Thanks Again for your feedback ! You are most welcome to fix this and submit a pull request as well. It will be greatly appreciated.

**Comment by premchandpl** [comment]
@mobiledevco In the latest code that has been published into github we are allowing , and . See the regular expressions that we are using 

"SpecialCharacterExpressionMatterTitle": "[A-Za-z0-9_]+[-A-Za-z0-9_, . '() –]*",
"SpecialCharacterExpressionMatterId": "[A-Za-z0-9_]+[-A-Za-z0-9_, .]*",
"SpecialCharacterExpressionMatterDescription": "[A-Za-z0-9_]+[-A-Za-z0-9_, . –]*",

As you can see we are allowing , and . for both matter name and description. 

We are closing this and let me know whether you encounter this issue after taking latest code
