### ISSUE TITLE
Deployment script error

### ISSUE THREAD

**Issue by pravinohal** [Microsoft/mattercenter#424]
I'm getting this error while running the Deploy.ps1 file in Windows Powershell

![mmdeploymenterror](https://cloud.githubusercontent.com/assets/7835285/18628392/a0b08d4c-7e7d-11e6-8182-5dfa8495a9bc.png)

Thanks in Advance

**Comment by WilsonReddy** [comment]
Have you added admin account to term store admin. if not refer deployment document page number 6, step 2.

**Comment by pravinohal** [comment]
Thanks, Wilson that worked like charm!!
