### ISSUE TITLE
Deployment Issue 

### ISSUE THREAD

**Issue by bhaskarsaladi** [Microsoft/mattercenter#427]
Hi Team,

We are planning to use Matter Center Tool in our company and we planned to start with analysis by deployment in our development environment.We Downloaded Latest Source Code and Followed the steps mentioned in the Deployment Guide.

![error2](https://cloud.githubusercontent.com/assets/21247678/18682113/9b6e0bf8-7f30-11e6-9599-766833097c25.PNG)
![error3](https://cloud.githubusercontent.com/assets/21247678/18682112/9b6acd08-7f30-11e6-8aee-f97e11c57419.PNG)
![internal server error](https://cloud.githubusercontent.com/assets/21247678/18682111/9b69f612-7f30-11e6-9d5a-2c11857a8dcb.PNG)

Also in Document there is a step to update 
• Update web dashboard URL in ‘WebDashboardSPTemplate’ HTML.
Location for ‘WebDashboardSPTemplate’= “../mattercenter-master/tree/master/cloud/src/deployments/Static Content/HTML/ WebDashboardSPTemplate .html”
• URL should be Azure web dashboard as below:

• Update the catalog URL in script as below:

• Upload following HTML page under ‘Site Pages’
1.  WebDashboardSPTemplate.html
• Create a new page using Wiki template and name it as ‘MatterCenterHome’.

 As there is no Pages folder in Solution not sure the Pages/Webdashboradpage.aspx will be accsible.

Please let me know if need more details. Thanks for Supporting.

**Comment by WilsonReddy** [comment]
@bhaskarsaladi  you need to set hosting environment to development to see error details.  follow below steps for setting environment variable to development.
1. Go to https://portal.azure.com, 
2. Select web app (your see your web app as 3mmattercenterweb09201557 appservice) under the resource group created as part of the deployment.
3. Go to application settings and add Hosting:Environment key with development value.
Now you will get more error details.  ensure to access your web app with https. (your web app url https://3mmattercenterweb09201557.azurewebsites.net/)

also, verify app service plan. The Scale up(App Service plan) should be B1 Basic.

**Comment by bhaskarsaladi** [comment]
@WilsonReddy  Thank you for the response. I have added the  " Hosting:Environment key with development value. in Azure web app. When i try to access https://3mmattercenterweb09201557.azurewebsites.net/ am getting below error. Can you suggest if any error with my deployment or configuration missing. 2 PS  Deployment scripts ran successfully without any issues. 

![certificate error](https://cloud.githubusercontent.com/assets/21247678/18689580/7698189a-7f4f-11e6-9d1f-d191fa1d6909.PNG)

[Azure Deployment Log.txt](https://github.com/Microsoft/mattercenter/files/483644/Azure.Deployment.Log.txt)

Please find attachments for more details.

**Comment by WilsonReddy** [comment]
@bhaskarsaladi Have you check service plan? it should be Basic B1.

**Comment by bhaskarsaladi** [comment]
Hi @WilsonReddy  I have changed the service plan to Basic B1 and still getting the same null exception with certificate error. Is there any specific configurations missing from SharePoint  sites / Azure Publish sites ? Thanks for helping on fixing the issues.

**Comment by bhaskarsaladi** [comment]
![app service plan](https://cloud.githubusercontent.com/assets/21247678/18726005/2d7986b2-8008-11e6-8d94-79bbe14a685b.PNG)

**Comment by pravinohal** [comment]
Me too facing the same error. I'm already having the Basic:1 Small plan

**Comment by amitabhm21** [comment]
@bhaskarsaladi ,@pravinohal Would you please check the Azure SDK version that you have ?

**Comment by bhaskarsaladi** [comment]
Hi @amitabhm21  Azure SDK Version is  v2.9

**Comment by pravinohal** [comment]
Hi @amitabhm21 installed Azure SDK version is v2.9.5

**Comment by bhaskarsaladi** [comment]
Hi @WilsonReddy @amitabhm21  Thank you both of you for helping us to resolve this deployment issues.We have to explore the functionalities to use this tool in our company.please let me know any suggestions / pointers to fix these issues".we urgently required to make it working soon. Thank you once again !!!

**Comment by amitabhm21** [comment]
@bhaskarsaladi can you send me an e-mail amitabhm@microsoft.com

**Comment by pravinohal** [comment]
Hi Guys,
   Any update on this issue?

**Comment by WilsonReddy** [comment]
@pravinohal can you attach your log file? bhaskarsaladi issue was with his machine. He was deploying from windows server 2008. New-SelfSignedCertificate is not supported in windows server 2008 machine. Refer https://technet.microsoft.com/en-us/library/hh848633.aspx for additional details.

**Comment by amitabhm21** [comment]
@bhaskarsaladi would you please help @pravinohal with similar issues ? The community will appreciate you sharing the very specific issues in your scenarios.

**Comment by bhaskarsaladi** [comment]
@amitabhm21 Sure Amitab. I started redeploying in new server 2012 R2 and started getting new error.
![image](https://cloud.githubusercontent.com/assets/21247678/18878037/cd4b9424-8494-11e6-8f03-f6533b406495.png)

I thought its issue with office installation and installed Office 2016.but still same issue reading excel. could you please suggest on this issue. Thanks.

**Comment by Majovero** [comment]
I'm actually getting this same EXACT error! 

![image](https://cloud.githubusercontent.com/assets/16903695/18879328/d5f30c8a-84a1-11e6-9e96-c2af9ecf249c.png)

I'm using Windows 10, VS15.

**Comment by bhaskarsaladi** [comment]
Hi @amitabhm21 @WilsonReddy  , We have tried again with new server windows 2012 and getting same above mentioned Certificate error.Some Reason still it is failing to execute the certificate creation and  certificate specific configurations.

[MCDeploy20160929-123056.txt](https://github.com/Microsoft/mattercenter/files/501551/MCDeploy20160929-123056.txt)

**Comment by bhaskarsaladi** [comment]
hi @Majovero  Did your Azure script executed with out any issues specifc to Certificate creation and export ? can you share your log file ?

**Comment by amitabhm21** [comment]
@bhaskarsaladi were you able to resolve the certification creation issue?
This behavior is local to your environment so not sure how to proceed. Did you try creating a certificate manually and updating the app? The script has finished all the steps the certificate is the only piece left so you can manually create a certificate and update the application settings.

**Comment by WilsonReddy** [comment]
@bhaskarsaladi @pravinohal @Majovero  Only windows 10 and windows server 2016 supports deployment. Try deploying from either win 10 or windows server 2016.
