### ISSUE TITLE
Capture Additional Field On Matter Provision

### ISSUE THREAD

**Issue by Vasanth1981** [Microsoft/mattercenter#432]
Hi,

I would like to capture additional field while create a new matter. Is there a way to do that without changing the code?

Regards,
Vasanth.

**Comment by WilsonReddy** [comment]
@Vasanth1981  we have design in place but still working on enabling this feature. Can you elaborate on what additional fields you want?

**Comment by Vasanth1981** [comment]
@WilsonReddy ,

Like Matter Name, Matter Description, I would like capture some more infomation like Country, Area, Department in the Provisioning,
![image](https://cloud.githubusercontent.com/assets/21088333/18846765/15fa40c4-83ed-11e6-8247-e49f55de0f63.png)

**Comment by Vasanth1981** [comment]
Hi Wilson,

Do you any idea, when this feature will be enabled?

Regards.
Vasanth.

**Comment by WilsonReddy** [comment]
@Vasanth1981 we are actively working implementation. It will be available in couple of weeks.

**Comment by premchandpl** [comment]
@Vasanth1981 Now matter center allows Additional Field On Matter Provision. Please let me know if more information is required
