### ISSUE TITLE
Issuue deploy.ps1 - Step 6

### ISSUE THREAD

**Issue by BjornVanWettere** [Microsoft/mattercenter#44]
29/12/2015 16:23:10 - Step 6: Update resource and config files in build
Updating resource files
Updating Constants.resx file
Message: StartIndex cannot be less than zero.
Parameter name: startIndex
Stacktrace:    at System.String.Substring(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex)
   at Microsoft.Legal.MatterCenter.UpdateAppConfig.UpdateConfig.UpdateResourceConstants(Dictionary`2 updateList, String constantElement, String constantAttribute, List`1
 manifestFile)
   at Microsoft.Legal.MatterCenter.UpdateAppConfig.UpdateConfig.UpdateConstants(Dictionary`2 updateList, String folderName)
Message: Failed to update app schema files
Failed to update resource files
Updating Constants.resx file
Successfully updated Constants.resx file
Updating Constants.resx file
Successfully updated Constants.resx file
Updating Log.resx file
Successfully updated Log.resx file
Successfully updated resource files

I had this error before, but thanks to somebody else here I figured out it had something to do with 'images' in the path. 

Any idea, how I get to know wich property is wrong, or how to fix this? 

Thanks in advance.

**Comment by LeoConniff** [comment]
We are in the process of bringing the source code for the helper utilities into the repository.  Once they are available you would be able to check which properties were being accessed in the code directly.  Additionally, we have recently updated the hint text on the image urls to give a better indication of what values should appear there.

**Comment by bryanlibin** [comment]
I got the same error message with Step 6: Update resource and config files in build. Can you share how you resolve it (e.g. the images path)? Thanks!
