### ISSUE TITLE
Matter Center App not functioning

### ISSUE THREAD

**Issue by SFghub** [Microsoft/mattercenter#45]
So I got the deployment to go through successfully but I'm having trouble actually using the App. The App takes me here but the links do not work:

![capture](https://cloud.githubusercontent.com/assets/16419194/12042256/2558a398-ae47-11e5-8de0-5a69efd963e8.PNG)

**Comment by LeoConniff** [comment]
Could you open the developer tools for your browser and post the network trace and console logs when you try to access this page?  The first issue that causes this error is when your internet settings are too restrictive and don't allow scripts to run.  This can typically be fixed by adding the SharePoint and website domains to the trusted sites in your browser.

Another possible issue is that there is an extra '/' in the links in the JS file, which can occur if a URL in the excel sheet had a trailing "/".  This will break the scripts and prevent the constants variable from getting populated.  The network trace will show what URL the site is trying to access to get the URLs and the console logs will tell us if the constants variable is null.

**Comment by LeoConniff** [comment]
We have looked into this issue further and we found an issue in the helper utilities that don't update the web config files for the websites as they should.  If the clientID/Secret/HostedAppName were not properly updated, then they will not be updated in the scripts at this time.  So if the previous instructions do not resolve the issue, check to make sure that the following fields are correct in your Web.config files:

Service site:
- Client ID
- Client Secret
- HostedAppHostNameOverride
- Access-Control-Allow-Origin

UI Site:
- Client ID
- Client Secret
- HostedAppHostNameOverride

**Comment by SFghub** [comment]
It looks like the issue is the constants variable, although I don't have any URL with an extra "/"

![consolelog](https://cloud.githubusercontent.com/assets/16419194/12052397/97ab540a-aedc-11e5-8176-332591069231.PNG)
![configxlsx](https://cloud.githubusercontent.com/assets/16419194/12052398/9d001d6e-aedc-11e5-92e7-4430b485b515.PNG)

**Comment by SFghub** [comment]
I've also confirmed the WebConfig files were updated:
![webconfigproviderservice](https://cloud.githubusercontent.com/assets/16419194/12056772/4d7c060a-af08-11e5-969e-3a966ec8ac15.PNG)

![webconfigappweb](https://cloud.githubusercontent.com/assets/16419194/12056775/5168b06a-af08-11e5-96cf-99cc3894b17f.PNG)

**Comment by s-KaiNet** [comment]
Exactly the same problem - this nasty errors `Uncaught ReferenceError: oGlobalConstants is not defined`

**Comment by s-KaiNet** [comment]
Actually find the reason  - I redeployed solution. After that you need to close you browser and delete cookie, after that error disappears.

**Comment by SFghub** [comment]
When you re-deployed did you just re-run the scripts on top of the existing install?

**Comment by s-KaiNet** [comment]
Yes, I just re-run the scripts on top off. Actually I had to fix some scripts to make it work without issues.   
Especially method `loadAndInstallSharePointApps` under `AppInstall.ps1`

**Comment by bblackwood1** [comment]
SFghub.... did this solve your problem?  I have the exact same issue and it is still occuring

**Comment by s-KaiNet** [comment]
@bblackwood1 try to clear cookie or start a new browser window "In Private" mode.

**Comment by bblackwood1** [comment]
That worked.... unfortunately it just helped me to uncover another problem.  Thank you for your answer though

**Comment by s-KaiNet** [comment]
> unfortunately it just helped me to uncover another problem  
The same situation for me....

**Comment by bblackwood1** [comment]
did you figure out the issue with the  line 148 ( #$parentContentTypeId = "" )?  

It ended up being an issue with a missing step in the install guide.  Package up the Microsoft.legal.mattercenter.onedriveribbon and place it in the sharepoint app folder.  When you rerun the script it will not error out there anymore

**Comment by s-KaiNet** [comment]
> It ended up being an issue with a missing step in the install guide. Package up the Microsoft.legal.mattercenter.onedriveribbon and place it in the sharepoint app folder  

Yes, also faced with this on the first run...   
For line 148 I just commented it because the error itself shouldn't affect other installation steps.

**Comment by aravindmp** [comment]
@s-KaiNet  - Were you able to fully deploy the solution and able to see it functioning . As i read your comments , i feel like following your path towards solving issues.

**Comment by amitabhm21** [comment]
These issues are resolved as part of the latest merge.

**Comment by NelsonLamprecht** [comment]
Faced this issue and my resolution was ensuring the web.config for the appweb has the correct HostedAppHostNameOverride of "123-ui.azurewebsites.net"
