### ISSUE TITLE
Renaming a Client

### ISSUE THREAD

**Issue by TacitIT** [Microsoft/mattercenter#458]
What's the correct process for renaming a client?

My current attempts only appear to update new matters AFTER the client name change in the term store.

Existing matters continue to show the previous client name.

**Comment by SwapnilM92** [comment]
It seems you have updated the Client name in term store however while creating a new Matter, we set Matter properties in document library properties. 
These properties include Matter name, area of law, subarea of law, Client name, team members etc. Hence after renaming the client in term store, new matters will be created with new client name but for existing matters, we have to update 'Client name' property in document library properties.
This can be done using small console app using CSOM.

**Comment by WilsonReddy** [comment]
@TacitIT  Reopen this issue if you need additional details.
