### ISSUE TITLE
Mattercenter-master zip file

### ISSUE THREAD

**Issue by Algenabe1** [Microsoft/mattercenter#475]
I was trying to follow the Matter Center Build and Deployment Guide but couldn't find the mattercenter-master zip File. I've downloaded the pre-requisites already but I can't do this step:

**4.	We are using powershell scripts for deployment, sometimes the scripts are not allowed to execute on the machine, we can follow below steps to allow execution of the script:
•	Unblock all PowerShell scripts and DLL files by unblocking mattercenter-master zip file in Windows Explorer (right-click -> Properties -> checkmark: Unblock -> OK)**

**Comment by WilsonReddy** [comment]
@Algenabe1 you need to do above step only if you downloaded as zip. you need not to do if you cloned from Visual Studio.

![image](https://cloud.githubusercontent.com/assets/9116038/19226056/f4647736-8e5a-11e6-81d1-e47ae3d50747.png)

**Comment by Algenabe1** [comment]
Thanks Wilson. I found the file from the Github site and downloaded it as zip.

Al Genabe | Online Support
Business Technology
6 Henderson Valley Rd, Henderson, Auckland 0612
Private Bag 92255, Auckland 1142
