### ISSUE TITLE
Error running Deploy.PS1

### ISSUE THREAD

**Issue by Algenabe1** [Microsoft/mattercenter#480]
![ps1 error](https://cloud.githubusercontent.com/assets/22734081/19255463/cd6d9b2e-8fba-11e6-9449-952694b4e414.PNG)

I've been receiving these errors. Can you please let me know what this means?

Thank you

**Comment by atjohns2** [comment]
That happens when it cannot read the configuration file correctly. Make sure the configuration file is filled out and that its closed before you run the Deploy script.

**Comment by Algenabe1** [comment]
Thank you Austin. I’ve checked the file and made sure there are no fields left blank and the file is definitely closed.

**Comment by atjohns2** [comment]
You are also running powershell as an administrator yes? I would also check that you've done all of the things listed in this part of the deployment guide (you probably have because I think you'd get  different error) . Otherwise I'm not sure what could be going on because it can read the file itself its just having issues with Read-FromExcel function. That comes from the LibraryFunctions.ps1 file which is actually built from one of the Helper Utilities - Microsoft.Legal.MatterCenter.Common.dll - you could always try rebuilding that DLL and moving it over to the correct library and see if that helps :

4.	We are using powershell scripts for deployment, sometimes the scripts are not allowed to execute on the machine, we can follow below steps to allow execution of the script:
•	Unblock all PowerShell scripts and DLL files by unblocking mattercenter-master zip file in Windows Explorer (right-click -> Properties -> checkmark: Unblock -> OK)
•	Open PowerShell.exe in administrator mode
•	Type the following command: Set-ExecutionPolicy “RemoteSigned”, it will ask for confirmation then type “Y” for yes.

**Comment by Algenabe1** [comment]
got rid of the message by installing Visual Studio Enterprise when my manager gave me a MSDN account. Not sure if it is related but I'm no longer getting the same error. However, I am receiving this error now  

"& : The term 'C:\MC\mattercenter-master\mattercenter-master\tree\master\cloud\src\deployments\Scripts\Helper
Utilities\Microsoft.Legal.MatterCenter.CreateGroups.exe' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At C:\MC\mattercenter-master\mattercenter-master\tree\master\cloud\src\deployments\Scripts\Deploy.ps1:217 char:7
+     & "$HelperPath\Microsoft.Legal.MatterCenter.CreateGroups.exe" "tr ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\MC\mattercen...reateGroups.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException"

**Comment by Algenabe1** [comment]
![mattercenter](https://cloud.githubusercontent.com/assets/22734081/19876911/3cfecf96-a03f-11e6-8276-7b15a0e6a135.PNG)

**Comment by WilsonReddy** [comment]
@Algenabe1 have you compiled helper utilities solution as explained in deployment document? compiling helper utilities will create these exes.

**Comment by Algenabe1** [comment]
Thanks @WilsonReddy . I have done that and built the solution which now allows me to proceed to the next step. I think the issue was I didn't build it. Do you know why I am getting the message below?

![mattercenter1](https://cloud.githubusercontent.com/assets/22734081/19911533/0c18a52c-a0f9-11e6-835f-0673f0e3367d.PNG)

**Comment by Algenabe1** [comment]
Permission issues with my login to the sites mentioned in the mcdeploymentconfig spreadsheet.
Sorted by giving myself access to the links. A slight improvement but still wondering why it came up with this:

![mattercenter2](https://cloud.githubusercontent.com/assets/22734081/19913370/c753ba2c-a106-11e6-8b5e-72ba6e2149e1.PNG)

**Comment by stuartcporter** [comment]
check that the compiled exe's were actually copied to the c:\src\depolyment\scripts\helper utilities\ directory - i found about 3-4 that were missing - hope that helps

**Comment by Algenabe1** [comment]
Thanks for the reply. I got a total of 4 errors for the following:

Microsoft.Legal.MatterCenter.ConfigureLists.exe
Microsoft.Legal.MatterCenter.CreateContentTypes.exe
Microsoft.Legal.MatterCenter.CreateSiteCollection.exe
Microsoft.Legal.MatterCenter.UpdateListPermissions

And I checked C:\src\deployments\Scripts\Helper Utilities and confirmed they are all there. Do you have any other ideas why these didn't run?

**Comment by stuartcporter** [comment]
check that the versions in that directory are the ones that have been compiled on your machine?
they should all have the date and time set based on when you compiled the helper utilities projects.

**Comment by Algenabe1** [comment]
Thanks again. I can see all files were created on the same day. So what I have done now is to clone the repository in our VSTS and loaded it in Visual Studio. I've got past all the error messages and got excited but then this 1 last error message came up before the script completed. Do you know how to fix this?
<img width="406" alt="capture" src="https://cloud.githubusercontent.com/assets/22734081/20551248/f6647b1a-b1a2-11e6-960b-d290a48c1981.PNG">

**Comment by stuartcporter** [comment]
i would make sure that you are using a sharepoint admin account to update - looks to be a permission issue - try using the global admin for your office 365 or the primary admin account for your sharepoint

**Comment by Algenabe1** [comment]
Awesome!!! I have an admin account but apparently I don't have global admin access. I've asked my colleague who has and it worked! Thanks a lot for your help Stuart! Now I can move on to the next step. :)
