### ISSUE TITLE
Issue :: Please select primary matter type

### ISSUE THREAD

**Issue by Vasanth1981** [Microsoft/mattercenter#495]
Hi,

After the deployment, I have updated the terms in terms store and deleted ones which added while deploying the matter center. After refresh the Redis Cache, now the terms are appearing, but now is always giving me below error while provisioning a new matter,
![image](https://cloud.githubusercontent.com/assets/21088333/19605720/5db31a64-9782-11e6-8147-bfa13676d3a1.png)

After debug the javascript, I have found that, the localStorage.setDefaultContentType is empty. But I have another tenant with default terms where I couldn't find this error. This error appearing after I change the terms store values.

Any help, I could I restore it and test?

Regards,
Vasanth.

**Comment by Vasanth1981** [comment]
![image](https://cloud.githubusercontent.com/assets/21088333/19606229/8cca34f0-9786-11e6-8c07-23dae63ae05d.png)

**Comment by Vasanth1981** [comment]
I found the issue, this is related to the custom properties that we set for each terms in the terms store. This was missing while we added manually.

**Comment by tgarmon** [comment]
I am having the exact same issues but cannot find a solution. What did you change in the settings fix this issue?

**Comment by Vasanth1981** [comment]
Make sure you have set the custom properties for each terms that you have created in Terms Store.
![image](https://user-images.githubusercontent.com/21088333/36397946-5071e718-158a-11e8-979a-3f97bb907990.png)

**Comment by tgarmon** [comment]
DO they need to be in order as displayed in your screenshot, or can they be
in any order?

Tom

On Mon, Feb 19, 2018 at 3:34 PM, Vasantha P Thomas <notifications@github.com
