### ISSUE TITLE
no -help with azure deployment

### ISSUE THREAD

**Issue by stuartcporter** [Microsoft/mattercenter#498]
i managed to get the sharepoint deployment working fine, however when i try the azure deployment with 

Deploy-AzureResourceGroup.ps1

it starts with an error looking for a json file

MatterCenterWeb10251055
Reading from template.parameters.json file...
Get-Content : Cannot find path 'C:\Windows\Templates\template.parameters.json' because it does not exist.
At C:\mc\mattercenter-master\tree\master\cloud\src\solution\Deployment\Scripts\Deploy-AzureResourceGroup.ps1:72 char:42
- $params = ConvertFrom-Json -InputObject (Get-Content -Path $TemplateParametersFi ...
-                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : ObjectNotFound: (C:\Windows\Temp...parameters.json:String) [Get-Content], ItemNotFoundEx
    ception
  - FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

and then some stuff appears to be created and some not, attached is the install log, any pointers would be appreciated

thx

[install_log.txt](https://github.com/Microsoft/mattercenter/files/550723/install_log.txt)

**Comment by dougmordy** [comment]
I believe you can solve the JSON location problem by changing the directory in powershell to be the directory containing AzureResourceGroup.ps1

**Comment by stuartcporter** [comment]
i guess i need to read the doc more, missed out the navigate to download location - thanks - running the deploy again to see how far it goes this time.

**Comment by stuartcporter** [comment]
well, things went a lot further, however seemed to go off the rails at the new self signed certificate
![deploy-error](https://cloud.githubusercontent.com/assets/23055584/19767772/42b43cd8-9c4c-11e6-8d27-42d1d91c6752.PNG)
and then further on web job creation and adding app to exchange

attached is the log if anybody has some pointers - we are trying to evaluate this to see if it's something that could be used by our law clients

[MCDeploy20161027-041201.txt](https://github.com/Microsoft/mattercenter/files/555827/MCDeploy20161027-041201.txt)

thanks
stuart

**Comment by WilsonReddy** [comment]
@stuartcporter Can you deploy from windows 10 machine?  Windows 2012 R2 machine don't support keyspect so failing to create certificate.  We will plan to resolve this issue but mean while please deploy from windows 10 machine.

**Comment by stuartcporter** [comment]
Ah ha, thanks I will try that,

stuart

**Comment by stuartcporter** [comment]
deploying from windows 10 machine got me past the certificate error - thanks
however I still have an error when I try to deploy to exchange
![exchange error](https://cloud.githubusercontent.com/assets/23055584/20005549/39d63e5e-a250-11e6-8424-c627bc26debd.PNG)
the error log is attached
[MCDeploy20161104-045649.txt](https://github.com/Microsoft/mattercenter/files/571468/MCDeploy20161104-045649.txt)

any help is appreciated
thx
Stuart

**Comment by stuartcporter** [comment]
still struggling with this,
when i access web site in azure i get a http 500 error,

if i try and debug against the site, the attach debugger fails with a object not found error
if i attempt to debug on machine that builds and publishes to azure - the clientAssertionCertPfx is null in the GetCert function...

very frustrating, the app looks like it may be useful, but trying to get it all to work is a pain in the @@@ !

willing to take any advice :)
stuart

**Comment by stuartcporter** [comment]
sorry closed my mistake

**Comment by stuartcporter** [comment]
i am getting a http 500 error when i try and run the web app, looking in the project that gets published to azure the appsettings.json file contains this

![appsettings](https://cloud.githubusercontent.com/assets/23055584/20428349/79e18b58-ad80-11e6-8e6c-851fea2e098c.PNG)

should these values not be updated by one of the scripts as part of the deployment to azure process?

**Comment by stuartcporter** [comment]
i ran the keyvaultsecret.ps1 to update the secret in azure.
however where do i get the keyvaultclientid or keyvaultcertthumbprint from?

**Comment by stuartcporter** [comment]
ok, turns out using the old azure management portal is alot easier to find the info you need, however after updating the appsettings.json file with what i believe are teh correct values. i still get this

![screen shot 2016-11-18 at 2 13 23 pm](https://cloud.githubusercontent.com/assets/23055584/20432933/66ada562-ad99-11e6-8bc4-a46c91838827.png)

any help at all would be appreciated.

thanks
stuart

**Comment by stuartcporter** [comment]
getting close, checking the web site was set to basic 1 on teh old azure portal , cured the http 500 error , however i now have a 'No service namespace '................' was found in the data store - if i attempt to access MatterCenterHome.aspx (how are you supposed to access the matter center ? )
and what service namespace should it be looking for?

what should be the tenant and aadinstance settings be? in the appsettings.json file?

![screen shot 2016-11-21 at 1 49 48 pm](https://cloud.githubusercontent.com/assets/23055584/20484935/6aba849a-aff1-11e6-9106-829b17f76d63.png)

![screen shot 2016-11-21 at 1 56 12 pm](https://cloud.githubusercontent.com/assets/23055584/20485175/4d778c1a-aff2-11e6-8f0d-fddeefdea37b.png)

**Comment by stuartcporter** [comment]
can somebody please help with hopefully this last bit of configuration?
