### ISSUE TITLE
Enabling Publishing Feature in Matter Center Site Collection?

### ISSUE THREAD

**Issue by Vasanth1981** [Microsoft/mattercenter#523]
Hi,

Can we enable publishing site feature in matter center site collection?

-Vasanth.

**Comment by SwapnilM92** [comment]
Yes, we can enable this feature on Matter Center site collection. By default the feature (SharePoint Server Publishing Infrastructure) is enabled with Matter Center deployment.
If it is not enabled then we can activate this feature from Site settings > Site collection features > SharePoint Server Publishing Infrastructure.

**Comment by WilsonReddy** [comment]
@Vasanth1981 closing this issue.  Reopen if you need more details.
