### ISSUE TITLE
Issue deploy.ps1 - Step 1a

### ISSUE THREAD

**Issue by lukebailey** [Microsoft/mattercenter#53]
Message: Unexpected response from the server. The content type of the response is "text/html; charset=UTF-8". The status code is "OK".
Stacktrace:    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.Legal.MatterCenter.Common.ConfigureSharePointContext.ConfigureClientContext(String Url, String login, String password, Boolean isDeployedOnAzure)
   at Microsoft.Legal.MatterCenter.CreateGroups.Program.deleteGroups(Dictionary`2 listval, List`1 groupData) occurred at 07/01/2016 11:30:28

Not particularly descriptive as the status code is OK - attempting behind a firewall but all other checks are successful.

**Comment by sunnymistry** [comment]
@lukebailey  will it be possible to share the screenshot when you perform the run. Based on this snippet I can only think about that the SPO URL is incorrect in the Excel file.

**Comment by sptrov** [comment]
We have kind of similar issue on 1a , 
![1a_issue](https://cloud.githubusercontent.com/assets/17924366/14358196/9d1f49a8-fcf4-11e5-85df-a6b99bbb19ae.jpg)

Users who runs the Deopoy.ps1 should have proper permissions since he created all the manual steps from the deployment guide.
So does anyone have a similar issue or knows what might be the case here.
Thanks

**Comment by ctrulove** [comment]
Are you still having this issue? The line that it is erroring on in the screenshot below is when it is trying to get a client context for the App Catalog site. Can you verify that the CatalogSiteUrl is pointing to your App Catalog and that the account you are running as is able to access this site?

**Comment by sptrov** [comment]
Thanks, This was found as a permission issue and was resolved.

**Comment by ctrulove** [comment]
@lukebailey was your original issue resolved?

@sptrov glad to hear it!

**Comment by rafaelqueiroz89** [comment]
@lukebailey I'm kinda new to azure and 365, where do you run those scripts?

**Comment by AbouJalal** [comment]
@sptrov I am having the same issue as yours, can you please elaborate on how you fix it?

**Comment by AbouJalal** [comment]
Can anyone help me please?

**Comment by amitabhm21** [comment]
@sptrov @AbouJalal Would you please take the latest version of matter center and let the team know if you still see this issue?
There are significant improvements made around deployment. Appreciate your help and feedback. 

Closing this issue. Please open a new issue if needed.
