### ISSUE TITLE
Azure Deployment - Verify Certifcate is valid and associated with this Subscription

### ISSUE THREAD

**Issue by youranupama** [Microsoft/mattercenter#539]
The Azure Deployment runs smooth untill Create-MatterCenterWebJob script is executed.  All the commands like New-AzureWebsiteJob, New-AzureSchedulerJobCollection gives following error when run from Powershell console.

New-AzureWebsiteJob : ForbiddenError: The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.
At
D:\MatterCenter\mattercenter-master\tree\master\cloud\src\solution\Deployment\Scripts\Create-MatterCenterWebJob.ps1:20
char:9
+     $job = New-AzureWebsiteJob -Name $WebSiteName `
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureWebsiteJob], CloudException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Websites.WebJobs.NewAzureWebsiteJobCommand

**Comment by WilsonReddy** [comment]
@youranupama  we never faced this issue. Did you try publishing job from Visual Studio? 

https://docs.microsoft.com/en-us/azure/app-service-web/websites-dotnet-deploy-webjobs

**Comment by youranupama** [comment]
Thanks for the reply. I have tried with Visual Studio and give it a try.

**Comment by WilsonReddy** [comment]
@youranupama Reopen this issue if you still facing this issue.

**Comment by meemakwana** [comment]
I am facing this issue, did anyone manage to fix ?
