### ISSUE TITLE
Drag and Drop of multiple emails

### ISSUE THREAD

**Issue by Vasanth1981** [Microsoft/mattercenter#544]
Hi,

In the description, mentioned that "Allow Drag and Drop of multiple emails and/or documents into Matter Center".

Could you please let me know how can I achieve this?

**Comment by WilsonReddy** [comment]
@Vasanth1981 the functionality not yet implemented. it is in road map.  you can consider http://www.epona.com/dmsforlegal/matter-center/ if you need it immediately.
