### ISSUE TITLE
Installation Step 10 Failing

### ISSUE THREAD

**Issue by DaveyDoo** [Microsoft/mattercenter#55]
Updated:
Running Azure Site and Service check...
1/12/2016 3:06:21 PM - XXXXXXXXXXui.azurewebsites.net Azure Web Site is present
1/12/2016 3:06:22 PM - XXXXXXXXXXservice.azurewebsites.net Azure Web Service is present
1/12/2016 3:06:22 PM - Pre-requisite check completed successfully

But Step 10 fails every time:
1/12/2016 3:08:02 PM - Publishing web service on Azure
Publish-AzureWebsiteProject : The website XXXXXXXXXXservice.azurewebsites.net was not found. Please specify a valid website name.
At C:\office365\mc\tree\master\cloud\src\deployments\Scripts\PublishOnAzure.ps1:48 char:2
+     Publish-AzureWebsiteProject -Name $ExcelValue1 -Package $ServicePackagePath
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Publish-AzureWebsiteProject], CloudException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Websites.PublishAzureWebsiteProject
1/12/2016 3:08:03 PM - Publishing web site on Azure
Publish-AzureWebsiteProject : The website XXXXXXXXXXui.azurewebsites.net was not found. Please specify a valid website name.
At C:\office365\mc\tree\master\cloud\src\deployments\Scripts\PublishOnAzure.ps1:53 char:2
+     Publish-AzureWebsiteProject -Name $ExcelValue0 -Package $WebsitePackagePath
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Publish-AzureWebsiteProject], CloudException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Websites.PublishAzureWebsiteProject

**Comment by DaveyDoo** [comment]
I also tried without the https:// in the setting and it fails in Step 10 as well.

**Comment by DaveyDoo** [comment]
I think I see the problem.  There is an inconsistency in the Azure commands.
The command Test-AzureName -Website  "mywebsite.azurewebsites.net" and Test-AzureName -Website  "mywebsite" will both return True.
However, the commands Publish-AzureWebsiteProject and Get-AzureWebsite only want the sub-domain name "mywebsite" and will fail if you pass the entire domain name "mywebsite.azurewebsites.net"

Inconsistency = BAD!

**Comment by sean8781** [comment]
@DaveyDoo I've run into the same problem, along with the deploy script trying to create a new Redis Cache because mine isn't in the default data center... I've tried running the commands in PS, with no success.. Do you or anyone else happen to know the steps to manually deploy these azure sites?

**Comment by amitabhm21** [comment]
The latest update to matter center has updated the deployment. If you are using [Matter Center 1.0] (https://github.com/Microsoft/mattercenter/tree/mattercenter1.0) please reopen the bug if the updated code is not resolving this issue.
