### ISSUE TITLE
Uprgade from MatterCenter 1 to Matter Center 2?

### ISSUE THREAD

**Issue by sramangit** [Microsoft/mattercenter#553]
Hello,

We had a working instance of Matter Center 1 several months ago, but the Azure subscription got deleted and we lost the service layer sites. I still see the Matter center v1 app listed under Exchange add-ins, but What is the recommended path to install Matter Center 2 in such a scenario? 

- Do we need to uninstall Matter Center 1 completely and start from scratch with Matter center 2? If so, is there an uninstall guide?
- Do we just use the V1 codebase and recreate the Azure sites and run through the install?
- Or, is there some form of upgrade path to move from v1 to v2?

What we did was go through the processes of installing v2 using the documentation, but it looks like our O365 environment is still showing v1.

Thanks!
Sudharsan.

**Comment by WilsonReddy** [comment]
@sramangit follow step 3,4,7,8 in deployment document to upgrade to V2.

**Comment by sramangit** [comment]
Thanks Wilson, I'll try that out. Will the upgrade work on the SharePoint and Exchange side, even if the Azure sites have been deleted? Wondering what's the best approach to take if the Azure sites have been deleted.. should we start with a fresh install?

**Comment by WilsonReddy** [comment]
@sramangit Yes, if you follow step 3,4,7,8 in deployment document, It will install new azure web site, outlook app and update sharepoint javascript files.

**Comment by premchandpl** [comment]
@sramangit Is the upgrade successful and can we close this issue?

**Comment by amitabhm21** [comment]
Closing this issue as the is no pending resolutions.
