### ISSUE TITLE
Deploy Step 6 Failed

### ISSUE THREAD

**Issue by bryanlibin** [Microsoft/mattercenter#56]
Got an error at deploy step 6 as follows:

Step 6: Update resource and config files in build
Updating resource files
Updating Constants.resx file
Message: StartIndex cannot be less than zero.
Parameter name: startIndex
Stacktrace:    at System.String.Substring(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex)
   at Microsoft.Legal.MatterCenter.UpdateAppConfig.UpdateConfig.UpdateResourceConstants(Dictionary`2 updateList, String constantElement, String constantAttribute, List`1 manifestFile)
   at Microsoft.Legal.MatterCenter.UpdateAppConfig.UpdateConfig.UpdateConstants(Dictionary`2 updateList, String folderName)
Message: Failed to update app schema files
Failed to update resource files

**Comment by lacovosika** [comment]
update values in Constants.resx under Microsoft.Legal.MatterCenter.SharePointAppWeb\App_GlobalResources to your SPOnline site for Image_Document_Icon and Image_General_Document.

Example:
https://<tenant>.sharepoint.com/images/MC_Documents.png. 
Worked for me, not sure if you need to provide an actual file or whether https://<tenant>.sharepoint.com/images/ is sufficient.

**Comment by bryanlibin** [comment]
Great, it seemed to work. Thanks, lacovosika!

**Comment by sunnymistry** [comment]
Thank you @lacovosika for helping out @bryanlibin .
