### ISSUE TITLE
 Framework mismatch - Service solution is not building.

### ISSUE THREAD

**Issue by youranupama** [Microsoft/mattercenter#567]
I tried to publish the Service project but the project is not building becuase of framework mismatch. The service project is using DNX4.5 but Model, Repository and Utility projects are using Net4.6. I am missing something here? Do I need to install anything. I have visual studio 2015 and all the prerequsite in place. 

![2016-11-21_10h32_39](https://cloud.githubusercontent.com/assets/22494716/20471230/f4fabe84-afd5-11e6-8b64-73593cec3622.png)

**Comment by rvanraamsdonk** [comment]
I'm having the exact same issue. Looking forward to getting some insights here. As a general comment, the last section of the MatterCenter deployment manual is way too sparse. It provides the bare minimum of information and leaves many questions unanswered. I'm really eager to get this build done.

**Comment by youranupama** [comment]
There is no documenatation about service project. I realised it later after deploying web application that api/service is not there at all. Steps to publish service will help tremendously.

**Comment by WilsonReddy** [comment]
@youranupama @rvanraamsdonk  There is no separate deployment for service in V2. The Web Api is hosted as part of the web site.  Ensure you have latest dotnet version in your machine. https://www.microsoft.com/net/core#windowsvs2015 after installing latest dotnet version, you can check version from command prompt as below. 
![image](https://cloud.githubusercontent.com/assets/9116038/20579969/8a74abbe-b184-11e6-8038-7f7e77bf9818.png)

Take latest code and verify build.  The dotnet version in your local machine should match with version in global.json.

![image](https://cloud.githubusercontent.com/assets/9116038/20581021/f7ebb5ec-b18a-11e6-88d6-22ec1309efc5.png)

**Comment by youranupama** [comment]
Thanks, I rebuild the project and published the web to the already created App Service. So when I load the the Index.html page, after some time, it give me this error. Any idea what could be wrong here?

![image](https://cloud.githubusercontent.com/assets/22494716/20588867/82950fbe-b23e-11e6-80ee-064296b1c59c.png)

**Comment by WilsonReddy** [comment]
@youranupama Have you configured AD application as per deployment document? I provided a screen shot with required permission to SharePoint online in deployment document. ensure delegate permissions are granted to AD application.

**Comment by rvanraamsdonk** [comment]
Another question: before Publishing Microsoft.Legal.Matter.Center.Web, do I need to run NuGet Package Manager? I've done that, it starts to run but fails on some incompatible packages after a couple of minutes. Are the packages essential for the Publish?

**Comment by WilsonReddy** [comment]
Publish will build and during build nuget packages get restored. Package restoration is essential. What error you are getting?

Sent from my Windows Phone
________________________________

**Comment by youranupama** [comment]
@WilsonReddy. Yes I have set the required permission as discribed in the documentation and has also executed keyValueSecret.ps1 with secret key. See images below for permssion for the permssions set for AD App.  What else could be  wrong here?
![image](https://cloud.githubusercontent.com/assets/22494716/20615655/f48dcf66-b301-11e6-826e-6dd5c2252f07.png)

![image](https://cloud.githubusercontent.com/assets/22494716/20615653/ede1bf4c-b301-11e6-81df-018e2a952c08.png)

![image](https://cloud.githubusercontent.com/assets/22494716/20615649/e6ad202c-b301-11e6-9fbe-944cb703394d.png)

**Comment by premchandpl** [comment]
@youranupama I am matter web app developer. Based on the error response that I am seeing, there is some issue with the client token that got generated from AAD. 

Have you updated your appsettings.json with key vault values properly. Let me know how can I help you in this case and I will try to resolve the issue for you

**Comment by amitabhm21** [comment]
@youranupama I am closing this issue assuming you were able to get the correct client token and update appsettings.json.

Please feel free to reopen if you need any help form the community.
