### ISSUE TITLE
AppInsights error when deploying because of azure changes

### ISSUE THREAD

**Issue by seranus** [Microsoft/mattercenter#572]
When deploying to west europe i started getting an error, after that deployment hangs 

![image](https://cloud.githubusercontent.com/assets/590231/20565087/63feead8-b190-11e6-981d-1d3e06ac7cb9.png)

I'm guessing this is because of https://azure.microsoft.com/en-us/updates/application-insights-general-availability-in-additional-regions-and-resource-location-update-east-us-south-central-us-west-europe-and-north-europe/

**Comment by WilsonReddy** [comment]
@seranus Take latest and verify. let me know if you still see issue.
