### ISSUE TITLE
Document Details not working

### ISSUE THREAD

**Issue by paulconroyNZ** [Microsoft/mattercenter#574]
We have deployed MC with On Premise Exchange, everything else is where it should be.
Clicking on document details from the web portal throw a none-descript error which is repeatable against all documents.  I've got no additional error information beyond what is seen in the image below, even clicking for more details simply reports "something went wrong"
![capture](https://cloud.githubusercontent.com/assets/20937786/20577571/d012fab0-b227-11e6-9488-592f5d05c0f7.PNG)

**Comment by WilsonReddy** [comment]
@paulconroyNZ Have you checked azure storage table for errors?

**Comment by WilsonReddy** [comment]
@paulconroyNZ  can you update sharepoint config file? you can do that by following below steps.

1. Go to https://<<your web app name>>.azurewebsites.net/#/admin
2. click on two buttons in the navigated page.
3. Then go to document view and do ctrl + F5

**Comment by paulconroyNZ** [comment]
Thanks @WilsonReddy 
Yes, checked the storage tables, and nothing of note.  I can't access that URL (tried both the UI and service websites).  Error "You do not have permission to view this directory or page".  Logged in with the account I've been using to do the install and not aware of any other account with superior permissions !

**Comment by WilsonReddy** [comment]
@paulconroyNZ Have you published code from Visual studio? The issue could be with the way you published code.

**Comment by paulconroyNZ** [comment]
The code was published via the powershell scripts and not straight out of VS.

**Comment by WilsonReddy** [comment]
@paulconroyNZ can you publish from VS as explained in deployment document. I am assuming you are deploying latest matter center (not 1.0).

**Comment by paulconroyNZ** [comment]
Not running the latest release, and likely to be too costly to upgrade at this stage of the project.  The customer will probably live with the issue for the time being.  Thanks all the same.

**Comment by lindendaniels2** [comment]
Hi Wilson,
As Paul says, this is V1 code, not V2, therefore powershell was used to deploy. As I understand this was working before. So, I dont think this is a code issue, but we need to find out what has changed in the environment to cause this. I will explore the envronment, and if needed, will inject some debugging code to get the actual error. Will get back to you.
For V1, is this a known or new issue?

**Comment by WilsonReddy** [comment]
@lindendaniels2  V1 working without any issue in our internal deployment. http://sp2013searchtool.codeplex.com/ tool is very helpful for debugging. Also, see if the issue happening for other types of documents.

**Comment by lindendaniels2** [comment]
Not resolve this yet, just an update: There are a series of SP Restful API calls in the Document details web page. Outside of the customer network, they all work. Inside the customer network the /Author API call is failing with a 500 http response error code (But the others are successful). Not sure why some SP Restful APIs would work and others would not - More research required...

**Comment by premchandpl** [comment]
@lindendaniels2 Is this still an issue. We can get into skype and can look into this

**Comment by amitabhm21** [comment]
Closing this issue. If this still needs attention please feel free to comment and open.
