### ISSUE TITLE
Another day - another deployment issue

### ISSUE THREAD

**Issue by stuartcporter** [Microsoft/mattercenter#577]
trying re-deployment to a new office 365 tenant and new azure subscription,

after publishing web site getting this, 
![screen shot 2016-11-24 at 9 37 11 pm](https://cloud.githubusercontent.com/assets/23055584/20610226/733ce500-b28e-11e6-90a9-902284a067c9.png)

any ideas, anyone?

**Comment by seranus** [comment]
Check your service plan, i got my up yesterday and azure started to auto downscale my service plan to D1 Shared when idle.

**Comment by stuartcporter** [comment]
basic b1 - as mentioned in some earlier issues
