### ISSUE TITLE
step 8 - deployment 

### ISSUE THREAD

**Issue by stuartcporter** [Microsoft/mattercenter#579]
is the application supposed to be added into your azure ad for you?
my application is not visible in azure ad

**Comment by stuartcporter** [comment]
the document for step 8
![screen shot 2016-11-25 at 4 00 21 pm](https://cloud.githubusercontent.com/assets/23055584/20630353/5995af98-b328-11e6-862a-c2592e8d12a9.png)

I do not have the option to filter by apps you are developing, i can find the app by searching for the name i gave in under applications your company own...

**Comment by WilsonReddy** [comment]
@stuartcporter The deployment creates AD application with same name as web app name. you can find it in log file.
