### ISSUE TITLE
Space in MatterCenter\AppManifest.xml causes SharePoint Install to fail

### ISSUE THREAD

**Issue by DaveyDoo** [Microsoft/mattercenter#58]
There is a space at the end of Line 4 in the file Microsoft.Legal.MatterCenter\AppManifest.xml that causes the app to never get fully installed on SharePoint.
If you stop the scripts from un-doing everything and navigate to the Matter Center app, you will see a message "Sorry, something went wrong with adding the app." On the App Details page, viewing Install Errors displays "The content database on the server is temporarily unavailable. Details: The URL '/sites/catalog/MatterCenter ' is invalid. It may contain illegal characters, or be too long."
Notice that there appears to be a trailing space in '/sites/catalog/MatterCenter ' 
The only text in the code that matches "MatterCenter " is in the file Microsoft.Legal.MatterCenter\AppManifest.xml
Change this text to "MatterCenter" and the app installs correctly and full deployment succeeds.

**Comment by sunnymistry** [comment]
Hello @DaveyDoo, thank you for identifying this issue. We have updated App Name and submitted the Pull request for merge. Once this request is merged, it should resolve app deployment issues faced by others.

**Comment by amitabhm21** [comment]
Fixed with merge of  #60.
