### ISSUE TITLE
angular-route.js isn't available on cloudflare

### ISSUE THREAD

**Issue by seranus** [Microsoft/mattercenter#583]
i get 404 when trying to access the location 
https://cdnjs.cloudflare.com/ajax/libs/angularjs/1.5.8/angular-route.js

**Comment by WilsonReddy** [comment]
@seranus  we are not using angular-route, instead we are using UI-Router. you can find details at https://ui-router.github.io/ng1/.

Can you remove this reference from Microsoft.Legal.MatterCenter.Web\wwwroot\Index.html and make a pull request?

**Comment by WilsonReddy** [comment]
@seranus The reference to angular-route.js is removed.  Reactivate this issue if still see in latest code.
