### ISSUE TITLE
matter landing page not setting app catalog path for scripts

### ISSUE THREAD

**Issue by seranus** [Microsoft/mattercenter#584]
I have a non default app catalog path and i didn't have a reference to sites/catalog in excel file or when deploying to azure.
Tenant path is correct, site collection was created from excel, matter with gui.

![image](https://cloud.githubusercontent.com/assets/590231/20667825/ad50fa12-b56b-11e6-8a2e-6fcbffcf4319.png)

All referenced assets are uploaded to the correct location.

**Comment by WilsonReddy** [comment]
@seranus you need to update path catalog site path in \tree\master\cloud\src\solution\microsoft.legal.mattercenter.web\appsettings.json file. either you can directly edit that file connecting to your subscription from visual studio -> cloud explorer or edit and publish that file from visual studio.

**Comment by seranus** [comment]
Updated the appsettings and published the web site. Missing MatterLanding.js

**Comment by premchandpl** [comment]
@seranus The matterlanding.js file should be available in the catalog site collection. If those files are not present, then the deployment script might not copied those files into sharepoint.  Can you validate the same
