### ISSUE TITLE
Matter Detail page missing labels etc

### ISSUE THREAD

**Issue by stuartcporter** [Microsoft/mattercenter#588]
when i click through to view the detail of a matter it seems rather sparse

![screen shot 2016-11-29 at 2 12 15 pm](https://cloud.githubusercontent.com/assets/23055584/20713277/89b800ee-b63f-11e6-8629-e6346c957d03.png)

i assume the proposed solution is to "Also, Can you access https://<>.azurewebsites.net/#/admin and then click on two buttons in the view? It will update UI lables and config settings for sharepoint."

however when i try that i get 2 errors like so

![screen shot 2016-11-29 at 2 26 56 pm](https://cloud.githubusercontent.com/assets/23055584/20713373/eebb1fd0-b63f-11e6-856d-2a3a9065ecee.png)

**Comment by stuartcporter** [comment]
are the missing info on this page and the document details page related to not being able to access the storage tables because of the uppercase letters in the secret?

**Comment by stuartcporter** [comment]
any ideas on how to get my poor looking screen - more fleshed out like this?

![screen shot 2016-11-29 at 5 14 22 pm](https://cloud.githubusercontent.com/assets/23055584/20762600/d2eff7dc-b71e-11e6-8c41-406387200740.png)

thanks

**Comment by premchandpl** [comment]
@stuartcporter I think the MatterLanding.js page is not loaded properly. Also the config.js should be there in MatterCenterAssets/CommonAsstes/Scripts folder in your catalog site collection.

**Comment by stuartcporter** [comment]
missing js file, no matterlanding.js 

![screen shot 2016-11-30 at 10 34 09 pm](https://cloud.githubusercontent.com/assets/23055584/20774205/37e45484-b74d-11e6-97c0-2c4f2b45edf8.png)

**Comment by premchandpl** [comment]
@stuartcporter config.js file should be present in this folder. if that file is not present, then the Matter Landing Page wont load properly. Can we have one skype meeting?

**Comment by stuartcporter** [comment]
I can skype

**Comment by stuartcporter** [comment]
Ready at admin@wgmllcdev.com :)

**Comment by stuartcporter** [comment]
the missing icons seem to be missing the /sites/catalog/ at the start of the image path - instead they have /sites/wgm3 which is the individual client site - i believe all the common images should be coming from the catalog site as that is where all the assets seem to be.

**Comment by premchandpl** [comment]
@stuartcporter All the images, css, js files will be referenced from catalog sites. If the images are not rendering properly, then the issue will be, the paths are not set properly in the spcommon.js file

**Comment by stuartcporter** [comment]
thanks @premchandpl  this is good now

**Comment by kungfulu** [comment]
What was the fix for this?  I am having the same issue.

**Comment by stuartcporter** [comment]
missing a bunch of the js files from MatterCenterAssets/CommonAsstes/Scripts folder in your catalog site collection - compare what you have in your local directory to see what's missing.

**Comment by kungfulu** [comment]
I was missing a bunch of files in my catalog site.  I matched them up from my local but still nothing.  I noticed in this post that the scripts folder needs the config.js.  Mine does not have that.  Were do I find that file?  Seems to be the only thing missing.

**Comment by stuartcporter** [comment]
here is a copy of mine, you will need to enter some values,
under uri, spositeurl
and tenant
under adal the client id from azure
not sure if you need to change the instrumentation key under app insights
under global add the url to the catalog site.

i think the rest is standard, i assume this file is supposed to be generated for you , but not sure

[_config.txt](https://github.com/Microsoft/mattercenter/files/743154/_config.txt)

**Comment by kungfulu** [comment]
Thank you for the file.  I didn't have this one.  I updated and uploaded it but still the same.

**Comment by stuartcporter** [comment]
maybe more wrong, if you do f12 for developer tools and share the errors

**Comment by kungfulu** [comment]
I get 1 error in the developer tools, and it is not finding uiconfigforspo.js.  The full error is:
HTTP404: Not Found - the server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR) GET - https://<tenant>.sharepoint.com/sites/Microsoft/SitePages/[[[Catalog%20site%20Url]]]/SiteAssets/Matter%20Center%20Assets/Common%20Assets/Scripts/uiconfigforspo.js?_=1486064186761

So it looks like it is trying to go to the actual Matter site (Microsoft for testing) for the JavaScript, but then it is changing to the Catalog site in the middle.

**Comment by stuartcporter** [comment]
what page are you trying to load?

do you have uiconfigforspo.js in the common assets \scripts in the catalog site?

the [[[catalog ... is a place holder that should be the path to your catalog site -

**Comment by kungfulu** [comment]
The page that this error is on is the landing page after a new matter is created.  Yes the uiconfigforspo.js is in the common assets/scripts in the catalog site.  Yes it looks like it is trying to pull the place holder in the middle of the URL.  Do you know what file the place holder is being referenced?  It looks just like the one you posted in the first post of this thread.

**Comment by stuartcporter** [comment]
matterlanding.js i think, do you have that ?

**Comment by kungfulu** [comment]
yes, in common assets/scripts I have config (thanks to you), jquery-1.11.1.min, matterlanding, spcommon and uiconfigforspo.

**Comment by stuartcporter** [comment]
look in the matter landing.js for place holders that should have been updated with your urls

**Comment by kungfulu** [comment]
originally it wasn't so I manually updated them yesterday because it had the [[[Catalog%20site%20url]]] in front.  I just changed them back to the[[[Catalog%20site%20url]]] to see if that had any different and I get the same error.

**Comment by stuartcporter** [comment]
those place holders needs to be replaced with the actual values send the file and i can have a look for you

**Comment by kungfulu** [comment]
Here is the matterlanding JavaScript file.  
[_MatterLanding.txt](https://github.com/Microsoft/mattercenter/files/748905/_MatterLanding.txt)

**Comment by stuartcporter** [comment]
your file has some issues, namely

![screen shot 2017-02-02 at 9 45 00 pm](https://cloud.githubusercontent.com/assets/23055584/22569846/fb6d3522-e990-11e6-94c3-d6acf5ad8f21.png)

and

![screen shot 2017-02-02 at 9 44 04 pm](https://cloud.githubusercontent.com/assets/23055584/22569858/0667bcae-e991-11e6-92a9-86497294c21f.png)

update with your correct path

can you send spcommon.js

**Comment by kungfulu** [comment]
[_MatterLanding_update.txt](https://github.com/Microsoft/mattercenter/files/749095/_MatterLanding_update.txt)
[_spCommon.txt](https://github.com/Microsoft/mattercenter/files/749094/_spCommon.txt)
Here is the updated matterlanding & the spcommon.  Let me know if the matterlanding is how it should look?

**Comment by stuartcporter** [comment]
nope, 

what is the sharepoint tenant name? it's not mattercenter its the name of the sharepoint tenant on office 365 where you created the catalog etc.

**Comment by kungfulu** [comment]
Yeah I know I just put that in so everyone doesn't see the client tenant. The right name is in that spot in the file in the catalog site.

**Comment by stuartcporter** [comment]
are you still getting any errors?

do a screen shot of the error in the dev tools

**Comment by kungfulu** [comment]
Same error as above.  Attached is the screenshot
<img width="1080" alt="ieerror" src="https://cloud.githubusercontent.com/assets/24302715/22595956/8cbf33a2-e9f7-11e6-84a3-00a320b1915d.PNG">

**Comment by stuartcporter** [comment]
can you send your spcommon.js file?

**Comment by kungfulu** [comment]
[_spCommon.txt](https://github.com/Microsoft/mattercenter/files/751371/_spCommon.txt)
Here it is.

**Comment by stuartcporter** [comment]
remove the extra '/' on the scatalogSite entry
instead of 
"sCatalogSite": "/sites/catalog//",
this
"sCatalogSite": "/sites/catalog/",

    instead of this 
    "oMatterCenterAssetsLocation": "/SiteAssets/Matter%20Center%20Assets/Common%20Assets/",

try 
"oMatterCenterAssetsLocation": "../sites/catalog/SiteAssets/Matter Center Assets/Common Assets/",

**Comment by kungfulu** [comment]
no change.  Same error in IE as posted earlier.  I even tried going into a browser I have never used before on the site to see if I was cached but that displays the same also.

**Comment by stuartcporter** [comment]
are you opening the guid page for the matter details?
try creating a new matter

**Comment by kungfulu** [comment]
Yes it was the guid page.  I just created a new matter and it is the same.

**Comment by stuartcporter** [comment]
please share the whole error section

**Comment by kungfulu** [comment]
Here it is.
<img width="1073" alt="ieerror2" src="https://cloud.githubusercontent.com/assets/24302715/22606424/df127cac-ea21-11e6-9811-ee55f15acca1.PNG">

**Comment by stuartcporter** [comment]
replace 

![screen shot 2017-02-03 at 8 05 11 pm](https://cloud.githubusercontent.com/assets/23055584/22606552/2f7cf2a6-ea4c-11e6-9aec-39ae4fcdb140.png)

with /catalog/ 


does page load?

**Comment by stuartcporter** [comment]
is the error coming from  displaycontent function in matterlanding.js ? 
check those urls are good.

**Comment by kungfulu** [comment]
I took the URL and put it in the address bar, removed the /microsoft/sitepages/[[[Catalog%20site%20Url]]] and replaced that section with /catalog/ and the page shows the javascript for uiconfigforspo.  The URLs in matterlanding are the full url in the catalog site for uiconfigforspo.js & config.js.
