### ISSUE TITLE
issue when building the solution

### ISSUE THREAD

**Issue by wgrizzle** [Microsoft/mattercenter#59]
[BuildSolutionError.docx](https://github.com/Microsoft/mattercenter/files/89623/BuildSolutionError.docx)
I get an error or list of errors when I try to build the solution after updating all the files in the documentation. I have no idea where to go from here.

Thanks for your help.

**Comment by bblackwood1** [comment]
Screenshots of the errors would be helpful

**Comment by johnnycardy** [comment]
Image from word doc... 
![image](https://cloud.githubusercontent.com/assets/904610/12328173/18044ca0-bad2-11e5-918c-50f7e29605ed.png)

**Comment by johnnycardy** [comment]
I would guess that in the process of updating the files, you may have introduced a syntax error that's causing the build to fail. All the other errors then result from that. So you'd need to go back over your changes and check them. It's just a guess, though.

**Comment by wgrizzle** [comment]
Thanks, I will review and try the build again. Is there any way for you to take a look at what I have so far and help to figure this out?



Cheers
Wayne

_________________________________________________________________________
Wayne Grizzle | Solution Architect
Project Leadership Associates|120 S. LaSalle, Suite 1200, Chicago, IL 60603
Phone: 832-941-0270<tel://Phone:%20832-941-0270/> | Fax: 312.441.0088<tel://Fax:%20312.441.0088/> | Mobile: 815-409-1643<tel://Mobile:815-409-1643/>
www.projectleadership.net<http://www.projectleadership.net/>

**Comment by sunnymistry** [comment]
Looking at the error and its sequence it looks like there is a build error in Entity Project. Because of which all other class libraries are not build successfully.

**Comment by wgrizzle** [comment]
Thanks Sunny. I was able to resolve that issue. I’m now stuck running the deploy script and it failing while creating app in the catalog. Can you please review the log and let me know what I can do to resolve?



Cheers
Wayne

_________________________________________________________________________
Wayne Grizzle | Solution Architect
Project Leadership Associates|120 S. LaSalle, Suite 1200, Chicago, IL 60603
Phone: 832-941-0270<tel://Phone:%20832-941-0270/> | Fax: 312.441.0088<tel://Fax:%20312.441.0088/> | Mobile: 815-409-1643<tel://Mobile:815-409-1643/>
www.projectleadership.net<http://www.projectleadership.net/>

**Comment by johnnycardy** [comment]
This issue might be related: https://github.com/Microsoft/mattercenter/issues/58#issuecomment-171827234

**Comment by wgrizzle** [comment]
Leo, can you please review the log file and let me know how to fix. I really need to get this up and running today!



Cheers
Wayne

_________________________________________________________________________
Wayne Grizzle | Solution Architect
Project Leadership Associates|120 S. LaSalle, Suite 1200, Chicago, IL 60603
Phone: 832-941-0270<tel://Phone:%20832-941-0270/> | Fax: 312.441.0088<tel://Fax:%20312.441.0088/> | Mobile: 815-409-1643<tel://Mobile:815-409-1643/>
www.projectleadership.net<http://www.projectleadership.net/>

From: Grizzle, Wayne
Sent: Thursday, January 14, 2016 5:29 PM
To: 'Microsoft/mattercenter' <reply@reply.github.com>
Cc: 'Leo Conniff (MAQ LLC)' <v-leconn@microsoft.com>
Subject: RE: [mattercenter] issue when building the solution (#59)

Thanks Sunny. I was able to resolve that issue. I’m now stuck running the deploy script and it failing while creating app in the catalog. Can you please review the log and let me know what I can do to resolve?



Cheers
Wayne

_________________________________________________________________________
Wayne Grizzle | Solution Architect
Project Leadership Associates|120 S. LaSalle, Suite 1200, Chicago, IL 60603
Phone: 832-941-0270<tel://Phone:%20832-941-0270/> | Fax: 312.441.0088<tel://Fax:%20312.441.0088/> | Mobile: 815-409-1643<tel://Mobile:815-409-1643/>
www.projectleadership.net<http://www.projectleadership.net/>

**Comment by sunnymistry** [comment]
Wayne, this issue is associated with #58. If you remove the trailing space from the app name present in the AppManifest file under https://github.com/Microsoft/mattercenter/blob/master/tree/master/cloud/src/solution/Microsoft.Legal.MatterCenter/, this should resolve the app installation issue for you.

**Comment by amitabhm21** [comment]
Closing this as the Issue https://github.com/Microsoft/mattercenter/issues/58 is fixed.

**Comment by wgrizzle** [comment]
Yes, thank you.



Cheers
Wayne

_________________________________________________________________________
Wayne Grizzle | Solution Architect
Project Leadership Associates|120 S. LaSalle, Suite 1200, Chicago, IL 60603
Phone: 832-941-0270<tel://Phone:%20832-941-0270/> | Fax: 312.441.0088<tel://Fax:%20312.441.0088/> | Mobile: 815-409-1643<tel://Mobile:815-409-1643/>
www.projectleadership.net<http://www.projectleadership.net/>
