### ISSUE TITLE
Matter Center 2 Install Failure

### ISSUE THREAD

**Issue by kungfulu** [Microsoft/mattercenter#593]
I have been trying to get Matter Center 2 installed.  I had the same issue that was in #572.  After that fix I was good to go but I keep getting these errors as it approaches the end of the install.

The first is The variable '$LogFile' cannot be retrieved because it has not been set.  It gives this error, but keeps going.

<img width="672" alt="1error" src="https://cloud.githubusercontent.com/assets/24302715/20810361/736dcc6c-b7d7-11e6-805f-98c272471f6d.png">

The second and third are: Uploading the files the SharePoint Library failed & Updating Office, Outlook and SharePoint App schema files failed.

<img width="667" alt="2error" src="https://cloud.githubusercontent.com/assets/24302715/20810466/da33a08e-b7d7-11e6-9fdf-c80e8418a98c.png">

After this the script just terminates.  All of the steps and script up until Step 7 have all been successful with no issues or errors.

**Comment by AISDUG** [comment]
Please take the latest code and try the install again. Also please make sure that the log files under ..\tree\master\cloud\src\solution\Deployment\Scripts\Logs are deleted before running the install

**Comment by kungfulu** [comment]
I didn't get the same errors, but I got a bunch of new ones and it didn't finish either.  On a side note, I just started from Step 7.  With the new build do you think I should have started from Step 1?

**Comment by AISDUG** [comment]
Starting at step 7 should be ok. Can you give some details on the errors that you got?

**Comment by MarkStokes-outlook** [comment]
I am also experiencing these two errors when trying to deploy the latest version of the scripts.

**Comment by allenolayiwola** [comment]
Hi guys, 

Need help here, getting the same errors.
Should I just start the entire process again?

 Uploaded documentDetails.css successfully...
1/15/2017 6:46:18 AM - Uploading files to SharePoint Library failed
1/15/2017 6:46:18 AM - Step : Update Office, Outlook and SharePoint App schema files
Updating app schema files
C:\mc\tree\master\cloud\src\solution
C:\mc\tree\master\cloud\src\solution\Microsoft.Legal.MatterCenter_Office
C:\mc\tree\master\cloud\src\solution\Microsoft.Legal.MatterCenter_Office
Updating Microsoft.Legal.MatterCenter_Office.xml file
Successfully updated Microsoft.Legal.MatterCenter_Office.xml file
C:\mc\tree\master\cloud\src\solution\Microsoft.Legal.MatterCenter_Outlook
C:\mc\tree\master\cloud\src\solution\Microsoft.Legal.MatterCenter_Outlook
Updating Microsoft.Legal.MatterCenter_Outlook.xml file
Successfully updated Microsoft.Legal.MatterCenter_Outlook.xml file
Successfully updated app schema files
1/15/2017 6:46:18 AM - Updating Office, Outlook and SharePoint App schema files failed
**********************
Windows PowerShell transcript end
End time: 20170115064618
**********************

**Comment by kungfulu** [comment]
That is what I did to get past this.  The code had been updated, so I deleted the Web App and started over with the updated code and I was able to get past this point.

**Comment by AISDUG** [comment]
Please also ensure that the ErrorLog.txt file  located at the below location has been deleted before running the deployment. The scripts will check this log file and will fail if the file is not empty. 

tree\master\cloud\src\solution\Deployment\Scripts\Logs

**Comment by adrenaline1073** [comment]
This should not me that hard, there should be step by step workable instructions.

**Comment by rvn2k** [comment]
Hey guys.. need someone to install Matter Center for me on a virtual machine, send me your price to nicolasr@gmail.com

Thanks 😀

**Comment by adrenaline1073** [comment]
It's meant to be installed on 365/Cloud.  I don't see it working locally in a Vm world.

**Comment by rvn2k** [comment]
I thought it needed some parts on a real server? I have both a virtual
server and our Office 365 working.

Saludos cordiales,



*Nicolás Rehbein C. *Teléfono: *(+56-9) 76969203  <+56225812373>*
*nicolasr@neotech.cl* <nicolasr@neotech.cl> | *www.neotech.cl*
<http://www.neotech.cl/> | *www.linuxtech.cl* <http://www.linuxtech.cl/>



2018-04-25 0:26 GMT-03:00 adrenaline1073 <notifications@github.com>:
