### ISSUE TITLE
deployment error on key vault, no search source id

### ISSUE THREAD

**Issue by seranus** [Microsoft/mattercenter#598]
When deploying i noticed 

![image](https://cloud.githubusercontent.com/assets/590231/20881719/f7874ff6-badd-11e6-91ed-d9c9db83ad39.png)

![image](https://cloud.githubusercontent.com/assets/590231/20881757/23a4f1d8-bade-11e6-80e2-6595af66ca3a.png)

with error msg:   "message": "Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).",

I changed it manually to the value from appsetting and it works now

EDIT: works for matters but getting all files in document results

**Comment by AISDUG** [comment]
search source id is now been read at the Tenant level instead of the catalog level.

The default value for CatalogSiteURL  in in the MCDeploymentConfig.xlsx needs to be updated to point to sites instead of team. Please change the value in the below file to as follows:

...tree\master\cloud\src\deployments\MCDeploymentConfig.xlsx 

CatalogSiteURL https://<<TENANTNAME>TENANTNAME>.sharepoint.com/sites/<<CATALOGNAME>CATALOGNAME>

**Comment by seranus** [comment]
my catalog site url is https://something.sharepoint.com/sites/katalog so it was not a team site. Then i manually set the web app value to b1eaa66b-033f-426e-8020-9eb7e7e68133 from appsetting but I'm getting all documents.

Can i fix my search by changing some values or do i have to do a an Azure redeploy?

**Comment by AISDUG** [comment]
Manually updating the web app value is all that is required. There is no need to re-deploy Azure.

**Comment by seranus** [comment]
when i set id as b1eaa66b-033f-426e-8020-9eb7e7e68133 search is querying all sharepoint documents not just from matter site ones, do you know why?

**Comment by AISDUG** [comment]
Is the ID  that you are setting from this location

 https://<TENANTNAME>.sharepoint.com > Site Settings > Result Sources > Matter Center

This should only pick up the documents from Matter Center

**Comment by seranus** [comment]
thanks, wasn't using that one, going to try it tomorrow. Also Matter center is located under https://.sharepoint.com/sites/catalog > Site Settings > Result Sources > Matter Center, was trying to find it under main site
