### ISSUE TITLE
Create Matter - Matters visible only in App Catalog

### ISSUE THREAD

**Issue by rvanraamsdonk** [Microsoft/mattercenter#601]
The Matter Center Exchange add-in is partially working now, with these remaining issues:

1) **Create Matter** wizard in Exchange add-in produces errors on step 3/3 ('List does not exist', '_Managed Metadata GUID does not exist_', very similar to issues already reported by @stuartcporter), wizard appears to hang, but Matters are still being created, with correct metadata in the App Catalog site (screenshot 1)

2) Matters created with the **Create Matter** wizard in the Exchange add-in don't display on the Matter Center web home page (screenshot 2) nor the under the **My Matters** menu in the Exchange add-in (screenshot 3). 

![image](https://cloud.githubusercontent.com/assets/23553323/20901887/f6e425fe-bb34-11e6-9365-07ceb5d5131b.png)

![image](https://cloud.githubusercontent.com/assets/23553323/20902394/381fdf5c-bb37-11e6-9ce2-ef3ec136b04e.png)

![image](https://cloud.githubusercontent.com/assets/23553323/20901943/3b54c798-bb35-11e6-9ffd-02ed5a896f50.png)

Any new insights are highly appreciated

**Comment by stuartcporter** [comment]
in the client sharepoint site , do you see the subscribed content types?

**Comment by stuartcporter** [comment]
Is your client called Microsoft? If not you have the file with the hard code client name
https://cloud.githubusercontent.com/assets/23055584/20686730/c0a724ce-b5b1-11e6-961a-64be3ad56a3b.png

**Comment by stuartcporter** [comment]
on line 2234 of the creatematter.controller.js file there was a hardcoded value of "Microsoft" being used to set the client name on matters, that should have been set to = cm.selectedClientName

**Comment by rvanraamsdonk** [comment]
@stuartcporter: Yes, all content types are visible on the Sharepoint site collection.

![image](https://cloud.githubusercontent.com/assets/23553323/20923867/d8f89d16-bbae-11e6-8464-8b7d08ee33ef.png)

**Comment by stuartcporter** [comment]
what happens if you uncheck the email notification option when creating a matter? does that complete?

**Comment by rvanraamsdonk** [comment]
No, I tried that based already having read your comments in the other thread.

**Comment by stuartcporter** [comment]
@rvanraamsdonk 
under the client microsoft sharepoint site, do you see document libraries that have been created - there should be one per matter and be named with a guid?

**Comment by stuartcporter** [comment]
have you looked at this #124 - sounds the same

**Comment by stuartcporter** [comment]
i did have something similar, and re-publishing the content types made a difference, it can take up to 48 hours for that to happen

**Comment by premchandpl** [comment]
@rvanraamsdonk As stuart suggested publish your content types and this should solve the issue of "Managed Metadata GUID does not exist"

**Comment by premchandpl** [comment]
@rvanraamsdonk The matters that you saw in the App Catalog, is just for auditing purposes. All the matters that are created will be serialized into property bag of that matter document library and will be indexed by SharePoint search engine. The data you see in matter search results will be coming from SharePoint search and not from that catalog list

**Comment by premchandpl** [comment]
@rvanraamsdonk The hard coded client name has been fixed last week and if you taken latest code, that issue will not arise and you don't need to make any changes to the code

**Comment by rvanraamsdonk** [comment]
No, but that’s because I did specify a single Client, but zero Matters in the MCConfig.xslx file. I thought I would use the Create Matter function in the Exchange addin to create Matters instead. Probably a bad idea. Maybe there needs to be at minimum 1 Matter in the system for all this to start working, I dunno... Anyway, I’ll redeploy everything including SP assets using the latest code and specify at least one Matter to be created in the config file. Thanks for your interest and support, I’m still finding my way around Github and this open source collaboration, but it looks like fun.

**Comment by rvanraamsdonk** [comment]
Yes I did. But the taxonomy existed alright, so that did not lead anywhere. Redeploying tonight to see how far we get. Thanks!

**Comment by rvanraamsdonk** [comment]
OK, will keep that in mind. Thx.

**Comment by premchandpl** [comment]
@rvanraamsdonk Let me know whether we can close this issue. If not let me know the problem that you are facing so that we can guide us

**Comment by rvanraamsdonk** [comment]
@premchandpl OK go ahead and close it.
