### ISSUE TITLE
documents not having set clients

### ISSUE THREAD

**Issue by seranus** [Microsoft/mattercenter#603]
I tried last few builds and none set client values on documents

![image](https://cloud.githubusercontent.com/assets/590231/20930480/c787ee46-bbcd-11e6-9334-b0d7bee97810.png)

Matters work fine

![image](https://cloud.githubusercontent.com/assets/590231/20930508/df9a7346-bbcd-11e6-8e99-0490c293be3d.png)

Document details

![image](https://cloud.githubusercontent.com/assets/590231/20930551/1ded2ac6-bbce-11e6-8ecc-6b5d0a64cca3.png)

Log table screenshot

![image](https://cloud.githubusercontent.com/assets/590231/20930656/8b08ed7a-bbce-11e6-8592-0e47371a46d9.png)

**Comment by stuartcporter** [comment]
I am seeing this as well, :)

**Comment by premchandpl** [comment]
@stuartcporter @seranus Able to trace out the issue and fix has been found for clients not showing up for documents. For old documents which are uploaded, the clients will still not be visible. You have to delete the problem documents and re-upload the same. Will post another comment once the code is merged with the main branch

**Comment by stuartcporter** [comment]
Thx

stuart

**Comment by premchandpl** [comment]
@stuartcporter @seranus Now the latest code has been merged to the master branch and now the clients can be associated to the matter. But for old matters, the clients will be shown as "NA".

If you create new matters and upload documents to that new matter, then client will show properly for those documents

**Comment by stuartcporter** [comment]
@premchandpl
 
what is required to update ? get code and build web site and deploy that ?

will anything on existing matter center be affected by that?

thx
stuart
