### ISSUE TITLE
not properly serializing json on matter configuratin

### ISSUE THREAD

**Issue by seranus** [Microsoft/mattercenter#604]
Matter configuration isnt serialized properly on configurations for clients that i created manually

![image](https://cloud.githubusercontent.com/assets/590231/20930859/57201884-bbcf-11e6-9721-8b342b7ab2b8.png)

`<div class="ExternalClassC62209F5F2DE43FF86C9F2F9B29835E2">{"DefaultMatterName":"","DefaultMatterId":"","DefaultMatterType":"","MatterTypes":"","MatterUsers":"","MatterUserEmails":"","MatterRoles":"","MatterPermissions":"","IsCalendarSelected":false,"IsEmailOptionSelected":false,"IsRSSSelected":false,"IsRestrictedAccessSelected":false,"IsConflictCheck":false,"IsMatterDescriptionMandatory":false,"MatterPracticeGroup":"","MatterAreaofLaw":"","IsContentCheck":true,"IsTaskSelected":false,"ClientUrl":"https://oudtb.sharepoint.com/teams/marleragolfld","CachedItemModifiedDate":null,"UserId":[],"ShowRole":true,"ShowMatterId":true,"MatterIdType":"Custom"}</div>`

Client creating flow was site collection -> term store -> set document id -> set permissions -> create matter configuration list. Then i set client configuration.

Works for excel created clients

**Comment by premchandpl** [comment]
@seranus How you created that client configuration? What is the process that you followed to create that client configuration?

**Comment by seranus** [comment]
i followed appendix A from the manual, skipped the steps with webdashboard and settings pages. After setting document id i went to Settings list configurations

Created a custom list named “Matter Configurations”, created a multiline ConfigurationValue field.

Went into the client settings page set show role and custom guid and submited

![image](https://cloud.githubusercontent.com/assets/590231/20934542/d08e57a6-bbdb-11e6-9f34-c2fa0a7ddb39.png)

**Comment by premchandpl** [comment]
@seranus What is the column type that you set for ConfigurationValue filed? We have set that to as shown in the below screen shot

![image](https://cloud.githubusercontent.com/assets/3001352/21039229/44b0e2e6-bd91-11e6-92bf-9a20d4cdd069.png)

**Comment by premchandpl** [comment]
@seranus In the data that you added, I am able to see the div tag and that should not be present

**<div class="ExternalClassC62209F5F2DE43FF86C9F2F9B29835E2">**{"DefaultMatterName":"","DefaultMatterId":"","DefaultMatterType":"","MatterTypes":"","MatterUsers":"","MatterUserEmails":"","MatterRoles":"","MatterPermissions":"","IsCalendarSelected":false,"IsEmailOptionSelected":false,"IsRSSSelected":false,"IsRestrictedAccessSelected":false,"IsConflictCheck":false,"IsMatterDescriptionMandatory":false,"MatterPracticeGroup":"","MatterAreaofLaw":"","IsContentCheck":true,"IsTaskSelected":false,"ClientUrl":"https://oudtb.sharepoint.com/teams/marleragolfld","CachedItemModifiedDate":null,"UserId":[],"ShowRole":true,"ShowMatterId":true,"MatterIdType":"Custom"}**</div>**

**Comment by seranus** [comment]
I set the column type as in the screenshot from the manual, the part about client creation seems to have obsolete or old data

![image](https://cloud.githubusercontent.com/assets/590231/21042527/27c89032-bdf2-11e6-88a1-2f4b4aedde49.png)

**Comment by premchandpl** [comment]
@seranus can you update the list column settings to plain text and update the configuration value so that it is a proper json object
