### ISSUE TITLE
appsettings.json question

### ISSUE THREAD

**Issue by stuartcporter** [Microsoft/mattercenter#607]
when i look at the file deployed to azure i see this

![screen shot 2016-12-09 at 1 57 21 pm](https://cloud.githubusercontent.com/assets/23055584/21051305/9e6ecace-be17-11e6-9003-983085e93496.png)

should these have been updated before deployment?
i believe these are the default values.

**Comment by WilsonReddy** [comment]
@stuartcporter web site will take these values from web app settings. you can find these in azure portal.   

You need to update these to run in local machine. otherwise these settings are not used by azure hosted web site.

**Comment by stuartcporter** [comment]
i thought so, i copied values from azure and when i run locally i can create a matter with the email notification checked, without error - still waiting for email to be delivered thou.

**Comment by premchandpl** [comment]
@stuartcporter notification emails will get generated by Azure web jobs. In the solution, there is a separate project for this one "Microsoft.Legal.MatterCenter.Jobs" This project needs to be deployed as azure web jobs and this will send the notification

**Comment by stuartcporter** [comment]
Does that not get deployed as part of the scripts?

**Comment by stuartcporter** [comment]
There is nothing in the deployment guide about that?

**Comment by premchandpl** [comment]
@stuartcporter let me know whether I can help you in setting up the jobs

**Comment by stuartcporter** [comment]
yes please, some guidance would be good, if i publish the jobs program the only option is to the file system - what needs to happens to get that into azure?

thx

**Comment by premchandpl** [comment]
@stuartcporter Can we have some skype meeting so that I can explain the steps to deploy web jobs to azure

**Comment by stuartcporter** [comment]
Certainly, please send invite to admin@wgmllcdev.com thx

stuart

**Comment by stuartcporter** [comment]
where do we get these credentials from?

![screen shot 2016-12-13 at 8 15 51 pm](https://cloud.githubusercontent.com/assets/23055584/21157398/0e563014-c171-11e6-9ed0-27dee69a63b6.png)

**Comment by stuartcporter** [comment]
i see it pulling these from the general:CloudStorageConnectionString in program.cs

**Comment by stuartcporter** [comment]
@premchandpl  
i don't think i am zipping up the correct files, i'm getting a dll cannot be loaded.

will wait for video thx

Stuart

**Comment by stuartcporter** [comment]
it's trying to load v1.0.0.0 however the version in my project is 1.0.0.20622

**Comment by stuartcporter** [comment]
@premchandpl what happened to the video? at the live meeting i could not see exactly what was zipped up due to the lag in the picture .

is it just the selected files below?

![screen shot 2016-12-15 at 4 12 28 pm](https://cloud.githubusercontent.com/assets/23055584/21231902/c3346804-c2e1-11e6-895f-e149670f6213.png)

or the whole release folder?

**Comment by premchandpl** [comment]
@stuartcporter I have sent the lync recording video to this email address - admin@wgmllcdev.com

**Comment by stuartcporter** [comment]
@premchandpl thanks, i have the job running now :)
however see the image below 

![screen shot 2016-12-15 at 5 01 34 pm](https://cloud.githubusercontent.com/assets/23055584/21233756/45f0479e-c2e8-11e6-9d0d-7e31a84f4919.png)

do we need the AzureWebJobDashBoard connection string? i'm thinking no cause we pull from the web app config.
however the sign-in name or password does not match ? what's that about?

**Comment by premchandpl** [comment]
@stuartcporter The admin username and passwrod is same as the username and password that you might have given for your azure web site. Azure web job will read that information from there. No need to specify the username and password in azure web job app settings file

**Comment by stuartcporter** [comment]
so is this issue expected? or do i need to change anything?

**Comment by stuartcporter** [comment]
ok, i can create a matter with the email notification option selected - matter is created and accessible etc - however i do not get any emails from the web jobs - so there is something amiss somewhere - the web jobs remains running continuously.

**Comment by stuartcporter** [comment]
@premchandpl 
"The admin username and passwrod is same as the username and password that you might have given for your azure web site."

should i have username and password config values in azure somewhere?
right now the jobs app is looking for these...

![screen shot 2016-12-15 at 9 50 51 pm](https://cloud.githubusercontent.com/assets/23055584/21243402/9bb63044-c310-11e6-8df1-b30da5d7e7fd.png)

**Comment by premchandpl** [comment]
@stuartcporter The admin username and password will be in your azure key vault. Application will read that information from the azure key vault and will use that information to connect to your exchange online to send notification emails. Let me know if more information is required

**Comment by stuartcporter** [comment]
i see the settings in the key vault, the admin user name setting was set to a onmicrosoft.com account - that is no longer the user name of the account i had changed it to use the wgmlldev.com domain instead - i have changed the account back and can sign into exchange using that account and send emails etc.

i have tried again, but still no email are flowing, i am in the process of re-deploying the web job to see if that helps.

i did notice that the settings in the key vault are like General-AdminUserName whereas in the application settings the sections are defined by : ie, General: <KeyName> is that ok? 

stuart

**Comment by stuartcporter** [comment]
@premchandpl 
i have tried re-deploying no difference still saying this,
![screen shot 2016-12-16 at 1 39 37 pm](https://cloud.githubusercontent.com/assets/23055584/21264655/2b8092ee-c395-11e6-81c7-0239d78f988d.png)

if you enter the account in the appsettings.json file do you have to enter the password as a encoded value? - i thought i would try that ?

**Comment by WilsonReddy** [comment]
Did you verify password in key vault? Update password in key vault and verify job.

Sent from my Windows Phone
________________________________

**Comment by stuartcporter** [comment]
the password was set a couple of weeks back and everything else is working fine - i assume that this username \password combination gets used elsewhere in the system - like in the creation of a matter and sharepoint site etc.

stuart

**Comment by stuartcporter** [comment]
i redepolyed the web jobs app, 
updated the password in the General-AdminPassword setting [even though the password have not been changed since deployment last month]
and bingo emails are flowing :)

thank you @WilsonReddy @premchandpl 

stuart
