### ISSUE TITLE
Does Matter Center support SharePoint Online Dedicated

### ISSUE THREAD

**Issue by cmh6** [Microsoft/mattercenter#61]
There are not too many Dedicated customers out there but please can you clarify whether Matter Center supports SharePoint Online Dedicated. Thanks!

**Comment by amitabhm21** [comment]
Chris (@cmh6) would you please elaborate a little bit more on your scenario. What plan are you referring to when you say Sharepoint Online Dedicated. This will help us answer better. Thanks !

**Comment by BSchorr-RST** [comment]
Just a guess but I suspect they're asking about the SharePoint Online plans in Office 365 that only include SharePoint.

**Comment by amitabhm21** [comment]
@cmh6 Pinging to see if you have the information you need.

**Comment by amitabhm21** [comment]
Closing this issue as there was no traffic in this. Please feel free to re-open.
