### ISSUE TITLE
JavaScript errors oGlobalConstants and oMatterProvisionConstants not defined

### ISSUE THREAD

**Issue by DaveyDoo** [Microsoft/mattercenter#62]
The page /pages/MatterProvision.aspx throws Uncaught reference errors in common.js, FilterPanel.js, and MatterProvision.js.
Apparently, these objects reference the values in App_GlobalResources/Constants.resx and App_LocalResources/MatterProvision.resx  but these variables are never getting initialized.
It is possible to make these errors go away by adding code that parallels the .resx files such as
var oGlobalConstants = {
        Add_To_Mail_Cart: "/AddToMailCart",
        Admin_Support_URL: "#",
        All_Documents_Message: "Manage documents: view, edit, or pin a document",
        All_Documents_Title: "All documents",
        ...etc...
};
But this is the hard way around it.  Somewhere there's probably a single line of code that isn't getting fired.

**Comment by dioulos** [comment]
DaveyDoo,

The way I resolved that problem is by creating a helper method (in the MatterProvision.cs) which runs on Page_Load and that reads the ressource file, build a json string from it and then inject it into the  javascript variable (var oGlobalConstants) located in the MatterProvision.aspx file

Hope it helps,
Seve

**Comment by DaveyDoo** [comment]
I knew I was doing it the hard way.  Code snippet, please?

**Comment by johnnycardy** [comment]
Writing code to manually create the oGlobalConstants JSON is a bad idea because it's masking what is likely to be a bigger problem: the only way to fix it properly is to debug and find out why exactly it's not working correctly. Sorry to be a spoil sport!

**Comment by DaveyDoo** [comment]
No worries. Like I said, I knew I was doing it the hard way.  Sometimes we doctors of technology try to take care of the obvious symptoms and get the patient out of the emergency room, all the while knowing we haven't found the root cause and will have to circle back later with a better solution.

**Comment by dioulos** [comment]
jonnycardy is certainly right...but anyway this is how I did it DaveyDoo:

Add this code snippet in the MatterProvision.aspx at the bottom above the MatterProvision.js <script> reference:

 <script type="text/javascript">

        (function () {

           // $.getJSON('Localisation.ashx?files=Constants.resx', function (data) { oGlobalConstants = data });
         
            window.oMatterProvisionConstants = <%=OMatterProvisionConstants %>;
        })();
    </script>


Then open the MatterProvision.aspx.cs and add the following:
Add the following "using" to get the required package:
   using System.Resources;
    using System.Linq;
    using System.Collections;
    using System.Web.Script.Serialization;


then add the following property:

  // Seve hacking
        private string _oMatterProvisionConstants;
        // Seve hacking
        public String OMatterProvisionConstants
        {
            get
            {
                return _oMatterProvisionConstants;
            }
        }


And then add:

    // Seve hacking
        private void GetLocalResources(string resxFileName)
        {
            var resourceDictionary = new ResXResourceReader(Server.MapPath("~/App_LocalResources/" + resxFileName + ".resx"))
                .Cast<DictionaryEntry>()
                .ToDictionary(entry => entry.Key.ToString(), entry => entry.Value.ToString());
            var Serializer = new JavaScriptSerializer();
            var json = Serializer.Serialize(resourceDictionary);
            //var javaScript = string.Format("window.Resources = window.Resources || {{}}; window.Resources.{0} = {1};", resxFileName, json);

            _oMatterProvisionConstants = json;
        }


Then in your Page_Load add in the try section:

GetLocalResources("MatterProvision"); // Seve hacking


Use the same pattern for the oGlobalConstants

Hope it helps.

**Comment by sunnymistry** [comment]
Following are the reason why the variables are not getting initialized:
a.	Go to Microsoft.Lega.MatterCenter.Utility project. Open the Constants.resx file. In this file, check the key named "Provision_Matter_App_URL". If it contains ProvisionDMSMatter in the URL update it to https://<tenantname>.sharepoint.com/sites/<catalogname>/MatterCenter
b.	If above is correct, go to Microsoft.Legal.MatterCenter.SharepointAppWeb project. Open Web.Config and over here check the appsetting key named "HostedAppHostNameOverride". Value of this key should be only <sitename>.azurewebsites.net. It should not prefix with https://. Check this same thing in Microsoft.Legal.MatterCenter.ProviderService > Web.config

It will be beneficial if you can provide the screenshot of the error message from IE Dev Toolbar as well

**Comment by aravindmp** [comment]
I too had same issues of oGlobalconstants is not defined error throw up on my pages. It is mainly due to some incorrect values that are set in constants.resx file across the solution . Like @sunnymistry  said above , it could be that "Provision_Mater_App_Url" . In another scenario , my client id didnt get updated which resulted in refresh tokens throwing errors. The best bet would be to revisit your settings in constants.resx .

**Comment by sunnymistry** [comment]
@dioulos  wanted to check if this issue is resolved for you or are you still running into this issue?

**Comment by dioulos** [comment]
@sunnymistry  this is resolved for me thx

**Comment by sean8781** [comment]
@sunnymistry I am still having problems on page load on the MatterCenter web site. Although I've confirmed the configuration as directed above, I still receive "oGlobalConstants is not defined" in console on page load.

I can provide my solution or a screenshot, or I could also set up a call if you'd like to review live.

Thanks for your help!
