### ISSUE TITLE
Deployment Guide: Step 8a correction

### ISSUE THREAD

**Issue by MarkStokes-outlook** [Microsoft/mattercenter#629]
This text

> 3a. Open https://manage.windowsazure.com. Click Active Directory in left navigation.  Select directory (your company directory) and navigate to application in Azure AD, then select ‘applications developed by your company’ filter. Select AD application and add permissions to apps from configuration tab as below.

should read:

> _Note:  You need to use the old Azure management portal as Application cannot yet be edited in the new portal_
> 
> 8a. Open https://manage.windowsazure.com.  Click Active Directory in the left navigation.  Select the directory for your company and then click the "Applications" tab.  Then select ‘Applications my company owns’ and click the filter button. Select the Matter Center application that has just been created and add the permissions into the configuration tab as shown below.
>

**Comment by WilsonReddy** [comment]
@MarkStokes-outlook Thank Mark. I corrected step and checked-in.
