### ISSUE TITLE
Issue opening search documents

### ISSUE THREAD

**Issue by stuartcporter** [Microsoft/mattercenter#630]
clicking on document search results in this!

![screen shot 2017-01-16 at 10 29 07 pm](https://cloud.githubusercontent.com/assets/23055584/22001431/126d5010-dc3d-11e6-92cf-e4f781a0ce8f.png)

any ideas? 
it was working fine , have not made any changes to app or sharepoint and now i 'm gettin this.

stuart

**Comment by WilsonReddy** [comment]
@stuartcporter  it looks like failed to load javascript file. Can you do F12 (developers tool) and check error details?

**Comment by stuartcporter** [comment]
yes, looks like can't get
 https://cdnjs.cloudflare.com/ajax/libs/angularjs/1.5.8/angular-route.js


![screen shot 2017-01-27 at 7 28 16 pm](https://cloud.githubusercontent.com/assets/23055584/22384573/e774a498-e4c6-11e6-8bc2-1335ae5096f4.png)

**Comment by stuartcporter** [comment]
are we missing a period?

should it be 
https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular-route.js

**Comment by stuartcporter** [comment]
corrected period, redeployed web app and working as expected now :)
