### ISSUE TITLE
Settings page not opening.

### ISSUE THREAD

**Issue by allenolayiwola** [Microsoft/mattercenter#638]
Hi,
My settings page wont display even after removing permissions as per the deployment guide. It just shows the error 

"You do not have permission to access this page. If you feel you need to access this page, kindly contact your support team to grant you access. "

Please can someone offer any help?

**Comment by merill** [comment]
I'm trying to setup Matter Center in O365 and I'm seeing this error too. I confirmed that I was in the site collection admin list.

**Comment by WilsonReddy** [comment]
@allenolayiwola @merill  you need to be part of provision matter users group in order to edit settings or create matter.  Go to catalog site and add your account to provision matter users group.

**Comment by allenolayiwola** [comment]
@WilsonReddy Am already a member of that group!

**Comment by przemasd** [comment]
@WilsonReddy  I've the same issue. I'm a member of "Provision Matter Users" Group too.

**Comment by merill** [comment]
@WilsonReddy I checked and can confirm my account is in both the Matter Users group and the Provision Matter Users.
I am unable to Create a matter neither does the matter home page load on SharePoint nor on Azure (xxx.azurewebsites.net/#/matters). It keeps on showing the spinning wheel. I don't know if it is related but in all of these pages the angular-route js provided is returning a 404.
i.e. https://cdnjs.cloudflare.com/ajax/libs/angularjs/1.5.8/angular-route.js

**Comment by przemasd** [comment]
I add my user to owner group and then works ;/

**Comment by allenolayiwola** [comment]
@przemasd what owner group are you referring to?

**Comment by przemasd** [comment]
@allenolayiwola This site where you have a setting page.

**Comment by premchandpl** [comment]
@allenolayiwola @przemasd Can you check whether you are added to that site collection owners group. If not, add yourself to that site collection owners group and try. The requirement to settings page is, you should be part of site owners group of that site collection.

Check and let me know whether it solves the issue?

**Comment by allenolayiwola** [comment]
No it does not, i am an administrator across all the sites and i even added my user account to every owner site collection, still same error!

**Comment by merill** [comment]
Okay finally got past this issue by doing what @przemasd said.

- Go to the root of our tenant (i.e. https://xxx.sharepoint.com) 
- Go to Site Settings > People and Groups
- Click More on the left (under Groups) so you can see all of the groups
- Go to the 'Owners' group of the root site (there are multiple groups, one for each subsite, need to make sure you go to the right one).
- Add your account to that group.

**Comment by premchandpl** [comment]
@allenolayiwola Follow the steps that merill has mentioned and that should solve the issue. Let me know is there any other way that I can help such as skype etc

**Comment by premchandpl** [comment]
@allenolayiwola let me know whether this issue has been resolved?

**Comment by allenolayiwola** [comment]
Its resolved now, working fine. @merill suggestion worked perfectly. Thanks
