### ISSUE TITLE
Matters and documents search doesn't load. 

### ISSUE THREAD

**Issue by przemasd** [Microsoft/mattercenter#642]
Hi, 
I have issue when i try open Matters search page on azure web app. 
Start Page is fine and create matter too, but when open search matters or documents 
![image](https://cloud.githubusercontent.com/assets/25458793/22469474/6e23b562-e7cc-11e6-8b0a-5f7ae4484b8f.png)
then I get error on console
![image](https://cloud.githubusercontent.com/assets/25458793/22469346/f87b162a-e7cb-11e6-9f16-919dd9158377.png)

can someone help me?

**Comment by WilsonReddy** [comment]
@przemasd  it seems angular is failing internally. Can you delete browser cache and try? also try in different browsers. check network tab in developer tool for additional details and let us know your findings.

**Comment by przemasd** [comment]
@WilsonReddy I clear cache and try on different browsers and I have this same error ;( 

![image](https://cloud.githubusercontent.com/assets/25458793/22478314/a939b986-e7e9-11e6-91cd-ea11cb91ba2d.png)

This is screen of log form console

On Network I have 2 404 status for %7B%7BuploadedFile.documentIconUrl%7D%7D and %7B%7BattachmentInfo.iconSrc%7D%7D

![image](https://cloud.githubusercontent.com/assets/25458793/22478550/acaa6a24-e7ea-11e6-95f0-1802b6c3a3d4.png)

**Comment by WilsonReddy** [comment]
@przemasd It seems search results source id is not updated in appsettings.  refer below steps to manually update search result sourceid in application settings. 

1. Go to https://<>.sharepoint.com/_layouts/15/manageresultsources.aspx?level=sitecol and click on mattercenter. Then from url get source id. You should replace %2D in sourceid value with -. 
2. Go to azure portal -> your web site appsettings and update  the value for searchresouredid settings.

**Comment by przemasd** [comment]
@WilsonReddy Thx very much 👍 It's works, after update settings I must clear browser cache and it's fine.

**Comment by randmorimoto** [comment]
@WilsonReddy Thank you for actively answering questions on this Matter Center GitHub page, I've had a nagging problem for 3-days, finally realized there's active support responses on GitHub here and found the solution to my problem in 5 minutes!  Should have come here earlier, thank you for sharing your knowledge on problem solving!

**Comment by przemasd** [comment]
I have issue when i update matter Center azure App Service. 

`{
  "errorCode": "500",
  "message": "Object reference not set to an instance of an object.",
  "description": "Error occured in the system. Please contact the administrator",
  "isTokenValid": false,
  "stackTrace": "   at Microsoft.Legal.MatterCenter.Web.Common.MatterProvision.<GetMatters>d__23.MoveNext() in C:\\Matter Center\\tree\\master\\cloud\\src\\solution\\Microsoft.Legal.MatterCenter.Web\\Common\\MatterProvision.cs:line 276\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.Legal.MatterCenter.Service.MatterController.<Get>d__15.MoveNext() in C:\\Matter Center\\tree\\master\\cloud\\src\\solution\\Microsoft.Legal.MatterCenter.Web\\Controllers\\MatterController.cs:line 303",
  "className": "<GetMatters>d__23",
  "methodName": "MoveNext",
  "lineNumber": 276,
  "errorDate": null,
  "exception": {
    "ClassName": "System.NullReferenceException",
    "Message": "Object reference not set to an instance of an object.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at Microsoft.Legal.MatterCenter.Web.Common.MatterProvision.<GetMatters>d__23.MoveNext() in C:\\Matter Center\\tree\\master\\cloud\\src\\solution\\Microsoft.Legal.MatterCenter.Web\\Common\\MatterProvision.cs:line 276\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.Legal.MatterCenter.Service.MatterController.<Get>d__15.MoveNext() in C:\\Matter Center\\tree\\master\\cloud\\src\\solution\\Microsoft.Legal.MatterCenter.Web\\Controllers\\MatterController.cs:line 303",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nMoveNext\nMicrosoft.Legal.MatterCenter.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\nMicrosoft.Legal.MatterCenter.Web.Common.MatterProvision+<GetMatters>d__23\nVoid MoveNext()",
    "HResult": -2147467261,
    "Source": "Microsoft.Legal.MatterCenter.Web",
    "WatsonBuckets": null
  },
  "isErrror": true
}`
![image](https://user-images.githubusercontent.com/25458793/27735193-a4b93550-5d9e-11e7-80b1-c89a8f9db317.png)
