### ISSUE TITLE
Cannot create matter

### ISSUE THREAD

**Issue by merill** [Microsoft/mattercenter#643]
I get the following error when I click on the 'Create and Notify' button when trying to open a new matter.
This is my first time setup and I'm trying to get the basic system working but not having much luck.
Does anyone know of a stable version of the code that works?
<img width="1066" alt="specified argument out of range" src="https://cloud.githubusercontent.com/assets/1288081/22506762/4cabc20c-e8d6-11e6-928c-ee7934c2a76d.png">

Thanks in advance.

**Comment by WilsonReddy** [comment]
@merill  Did you give 'have full control' permission to Azure AD application as mentioned in deployment document? also ensure user has 'Have full control' permissions on client site.

**Comment by WilsonReddy** [comment]
@merill closing this issue. Reopen if you still see error.
