### ISSUE TITLE
Step 7: Getting the error below, need help!

### ISSUE THREAD

**Issue by allenolayiwola** [Microsoft/mattercenter#644]
Hi,

Am getting the error below, I need help. Please assist if you can.
![capture_error](https://cloud.githubusercontent.com/assets/1235545/22515663/28463f9a-e89b-11e6-87c6-2c6d84c85cbd.PNG)

**Comment by merill** [comment]
+1 I see the same error.

**Comment by WilsonReddy** [comment]
@merill @allenolayiwola  Have you tried deployment multiple times? Anyway, ignore these errors and continue with deployment.

**Comment by allenolayiwola** [comment]
Yes i have tried it a couple of times, but i always delete the resource container along with ll azure items created. I also recreate the client site collection, but use the same catalog site.


Thanks

**Comment by WilsonReddy** [comment]
@allenolayiwola @merill you can ignore those errors. Is application working for you now?

**Comment by merill** [comment]
Not sure what happened but I don't get these errors anymore after I downloaded the latest code.

**Comment by premchandpl** [comment]
@allenolayiwola Is this still an issue. If not we can close this issue?

**Comment by allenolayiwola** [comment]
Will download the latest code as suggested by @merill and try again tomorrow. Will update this after i do. Thanks

**Comment by premchandpl** [comment]
@allenolayiwola Let me know whether did you get a chance to work with the latest code?

**Comment by allenolayiwola** [comment]
Thanks @premchandpl, ignored the error. Cheers
