### ISSUE TITLE
Web Dashboard Error

### ISSUE THREAD

**Issue by hdmal** [Microsoft/mattercenter#647]
Hi,

I have followed all the instructions given in "Matter Center Build and Deployment Guide" and ran in to several issues. Namely,

1. SharePoint - Azure app registration step is not elaborative enough (Redirect URl is not clear).
2. Web Dashboard page is not rendering. Following is the error I get;

![pagenotfound](https://cloud.githubusercontent.com/assets/20450634/22635202/ad078b74-ec85-11e6-9b71-76d82186172c.jpg)

Then I went on and checked the deployment file structure in Azure(App Services file structure).

![azure published files](https://cloud.githubusercontent.com/assets/20450634/22635260/3034104e-ec86-11e6-8495-1c8f9d16d81c.jpg)

In which, I could not find the iFrame src that the page is looking for(Appendix A, Point 3). 

![iframeurl](https://cloud.githubusercontent.com/assets/20450634/22635337/e9f49e90-ec86-11e6-9759-048716347ccc.jpg)

Simply, I could not find "pages" folder inside "webroot" at all. Even inside the solution, there was no page called "webdashboard.aspx". Please see the following solution which I downloaded from GitHub.

![solution structure](https://cloud.githubusercontent.com/assets/20450634/22635383/4e6a5ce8-ec87-11e6-91ef-488ade7542ff.jpg)

I am wondering that whether I am following the correct deployment guide;

[Matter Center Build and Deployment Guide.docx](https://github.com/Microsoft/mattercenter/files/753722/Matter.Center.Build.and.Deployment.Guide.docx)

Please advise.

Regards,
Malaka

**Comment by WilsonReddy** [comment]
@hdmal  Appendix-A is to manually create client team.  This step is not required while do first time deployment. The deployment will create automatically based on the client information provided in MCDeploymentConfig.xlsx client_config sheet.  if you performed all other steps successfully then application should be up and running for you.

**Comment by hdmal** [comment]
Thanks Wilson. I got Matter Centre running. But how can I create a new client after completing the deployment?

How do we crate the site pages for the new client?

Regards,
Malaka.

**Comment by premchandpl** [comment]
Matter Center - Selenium solution Build and deployment guide
**This is the for the matter app developers who wants to unit test the matter web app ui**
Matter Center 2 - Jasmine solution Build and Deployment guide
**This is for the matter app developers who wants to unit test the angular application javascript code**

Need to understand how you are adding the addin to outlook?

**Comment by premchandpl** [comment]
@hdmal For adding a new client to the matter web app, the deployment guide has been updated and you can follow the steps mentioned in Appendix A of the deployment document

**Comment by hdmal** [comment]
Hi premchandpl. Thanks for your reply. I have got Matter Centre and Add-in running in Office Applications. 

Can you please let me know that, how to attach a working document to an existing matter? I know that drag and drop is possible in Outlook. But, for example, if an user creates a new Word document, how can he/she attach/save that newly created document into an existing matter using the Add-in?

![word-save into matter](https://cloud.githubusercontent.com/assets/20450634/23387325/ec7f1f70-fdaf-11e6-8d97-1a26bf9f8a14.jpg)

Regards,

**Comment by premchandpl** [comment]
@hdmal This feature is currently not available in current matter center. 
What is currently available is
     
1. In the word app open matter center add in.
2. Select the matter where you want to upload the matter
3. In the matter flyout, you can find a text box with matter document library url
4. See the below screen shot
![image](https://cloud.githubusercontent.com/assets/3001352/23388230/d234ca6a-fd15-11e6-92e0-348bc6a30548.png)
5. Copy that url and save that document to that path.
6. This way, the current document will be saved to that matter document library
7. This functionality is in the future road map and for time being this is the work around that you have use to save the document from word to matter document library

Closing this request and we will let you know once this feature is added to matter center

**Comment by hdmal** [comment]
Thanks a lot premchandpl. We can live with the workaround until we have a new release with the new feature. Thanks heaps for quick response.
