### ISSUE TITLE
Get-AzureRMStorageAccountKey : Specified argument was out of the range of valid values

### ISSUE THREAD

**Issue by viniciusdeschamps** [Microsoft/mattercenter#648]
Hi,

I'm trying to deploy MatterCenter on my Azure subscription and everything was going well until I receive the following error

```
Getting the storage key to write to key vault...
Get-AzureRmStorageAccountKey : Specified argument was out of the range of valid values.
Parameter name: accountName
At C:\mattercenter-master\tree\master\cloud\src\solution\Deployment\Scripts\Deploy-AzureResourceGroup.ps1:171 char:22
+ ... ccountKey = Get-AzureRmStorageAccountKey -Name $storageAccount_name - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmStorageAccountKey], ArgumentOutOfRangeException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Management.Storage.GetAzureStorageAccountKeyCommand
Get-AzureRmStorageAccountKey : Specified argument was out of the range of valid values.
Parameter name: accountName
At C:\mattercenter-master\tree\master\cloud\src\solution\Deployment\Scripts\Deploy-AzureResourceGroup.ps1:171 char:22
+ ... ccountKey = Get-AzureRmStorageAccountKey -Name $storageAccount_name - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmStorageAccountKey], ArgumentOutOfRangeException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Management.Storage.GetAzureStorageAccountKeyCommand

Getting the result source ID...
System.Object[]
```

**Comment by kungfulu** [comment]
I had a similar error (I can't remember if it was the same or not).  Digging into it it seemed that the version of PS I was using did not contain parameters for -keyspec.  I was running the scripts from a Windows 8 machine.  When I tried them from a Windows 10 machine I was able to get past this part.

**Comment by viniciusdeschamps** [comment]
I'm running on Windows 10, here is my PowerShell version

![image](https://cloud.githubusercontent.com/assets/25588563/22657498/dc856fea-ec7d-11e6-9183-e16447b1b8d3.png)

**Comment by WilsonReddy** [comment]
@viniciusdeschamps  Did you give correct Azure credentials prior to failing? normally it fails if user credentials are wrong.

**Comment by amitabhm21** [comment]
Is this issue still active @viniciusdeschamps?

**Comment by viniciusdeschamps** [comment]
@WilsonReddy and @amitabhm21 thanks for your replies, and yes I gave proper credentials but this issue isn't happening anymore after install AzureRM package as mentioned by @WilsonReddy in the other thread. Thanks again and sorry on the delay.

**Comment by amitabhm21** [comment]
Great!
