### ISSUE TITLE
Webdashboard Issue

### ISSUE THREAD

**Issue by SumeshKashyap** [Microsoft/mattercenter#651]
[QueryFordashboard.zip](https://github.com/Microsoft/mattercenter/files/770613/QueryFordashboard.zip)
[QueryFordashboard.pdf](https://github.com/Microsoft/mattercenter/files/770616/QueryFordashboard.pdf)

Actual code image

Image in the set  up document \ Deployment guide

Queries
There is difference in code what we see in document and what is exactly in the code file. Can you please suggest to close the difference?
It is squeryString in document but in code we see qparams
If my azure site has url https://mcddeploy.azurewebsites.net then what shall be value of oWebDashboardSPGlobal.iFrame.src = "https://mcddeploy.azurewebsites.net/#/matterdashboard?"+qParams
		
		OR 

oWebDashboardSPGlobal.iFrame.src = "https://mcddeploy.azurewebsites.net/pages/webdashboard.aspx"+qParams
And what will be changes in the Else block
else{
		oWebDashboardSPGlobal.iFrame.src = "WEB_DASHBOARD_PAGE_URL/#/matterdashboard";
            }
        	
        }
        else{
        	oWebDashboardSPGlobal.iFrame.src = "WEB_DASHBOARD_PAGE_URL/#/documentdashboard";
        }   

NOTE: Please refer the attachment for images.
[QueryFordashboard.pdf](https://github.com/Microsoft/mattercenter/files/770619/QueryFordashboard.pdf)

**Comment by premchandpl** [comment]
@SumeshKashyap The deployment document has been updated with correct steps and these steps will not be required. As part of the first deployment, the deployment script will take care of updating the urls with correct query string paramaters

These steps were there for adding a new client to the matter and these are not required now. Closing this and let me know if you want to reopen and I can guide you on that
