### ISSUE TITLE
Appendix A section 3

### ISSUE THREAD

**Issue by Ventura23** [Microsoft/mattercenter#653]
In Appendix A section 3 could I please get more information as to which URL needs to be inserted for

oWebDashboardSPGlobal.iFrame.src

The Azure web dashboard does not look anything similar to what is stated in the deployment document.

**Comment by premchandpl** [comment]
@Ventura23 Deployment document has been updated and we don't require these steps of modifying the web dashboard and settings page. If you download the latest deployment document, you can find those steps are removed

Closing this. Let us know if more information is required
