### ISSUE TITLE
Error creating a matter

### ISSUE THREAD

**Issue by hdmal** [Microsoft/mattercenter#655]
I have got Matter Centre running in our SharePoint tenant. However, when I try to create a matter I get the error "List does not exist". Even with the error, a matter is created in "AppCatalog" site under "MatterCenterMatters" list.

Any of the supporting lists relating to matter creation / provision function had not been created in the client site collection as well.

Following is the Storage Explorer View for the SPOLogTable.

![azureerrorlog](https://cloud.githubusercontent.com/assets/20450634/22922272/20f6e37e-f2f1-11e6-82f9-cac826ef5495.jpg)

"Skype Payment" is the sample Matter Name I used. 

Please advise.

Regards,
Malaka.

**Comment by premchandpl** [comment]
@hdmal I think the client site collection that has been created will be having managed columns called PracticeGroup, AreaOfLaw and SubAreaOfLaw.

Check whether those are pointing to "PracticeGroup". Check the below screen shot

![image](https://cloud.githubusercontent.com/assets/3001352/22956074/976dc0a8-f2d4-11e6-9693-53d882897a82.png)


Also this github post for more information

https://github.com/Microsoft/mattercenter/issues/124

**Comment by premchandpl** [comment]
@hdmal let me know if you want any skype call

**Comment by amitabhm21** [comment]
Is this issue still open @hdmal ? This is a clear resolution. Please feel to reopen.

**Comment by hdmal** [comment]
Your are a legend premchandpl. All good. You saved my day. Soon after pointing those columns, error went away.

Thanks  premchandpl.
