### ISSUE TITLE
Consent issue

### ISSUE THREAD

**Issue by RoberRamon** [Microsoft/mattercenter#656]
Hi all,

I have followed all steps in the deployment guide and when I try to Access to the App service I'm getting this error in all pages, it seems that it can't retrieve information from SharePoint.

Could you advice please? 

Error:
Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS65001: The user or administrator has not consented to use the application with ID 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx'. Send an interactive authorization request for this user and resource.

Thanks,

**Comment by kungfulu** [comment]
I ran into this issue in the past.  It takes the tenant admin to consent the use of the app.  When he approved the app I was able to get past this screen.

**Comment by amitabhm21** [comment]
Thanks @kungfulu. This resolution is verified.
