### ISSUE TITLE
Exchange App Add-In Error

### ISSUE THREAD

**Issue by kungfulu** [Microsoft/mattercenter#659]
I had an issue where it successfully added the Exchange App into the Tenant, but when I went into the settings it was showing 'Specific Users' and a few people couldn't see the app.  Word was working fine for everyone.  So I removed it and re-added it in and it is still working in Word, but this time it does not show in Exchange Settings at all.  When I manually add the app in Exchange I get the following error:

<img width="424" alt="exchangeapperror" src="https://cloud.githubusercontent.com/assets/24302715/23036314/5e062a76-f450-11e6-95f4-caab00c59be7.PNG">

Anyone have this issue or know of a fix?

**Comment by premchandpl** [comment]
@kungfulu Word has nothing to do with exchange settings. Exchange settings are just for outlook. The image that has been added by you is not showing up. Can you please re attach the image so that we can look into that

**Comment by kungfulu** [comment]
OK, then I think you might have just answered my question/figure out the issue.  I uploaded the one that we create in step 9 and add to the catalog site, to Exchange and got the error.  So that one is for Word, where is the one for Exchange located at?

**Comment by premchandpl** [comment]
@kungfulu 
1. Go to office.portal.com
2. Select admin from the list of apps in office portal
3. Select exchange
4. You should see an "add ins" link
5. Select that add in link
6. You should see the matter center add in. If not you can upload the outlook manifest.xml file(Microsoft.Legal.MatterCenter_Outlook.xml) and make sure that the xml file has been updated with all the required information

**Comment by kungfulu** [comment]
That was my problem all along.  I didn't realize I was trying to upload the Word manifest.xml instead of the Outlook one.  Thanks works like a charm now.
