### ISSUE TITLE
Deployment Succeeds even with errors

### ISSUE THREAD

**Issue by wauph** [Microsoft/mattercenter#663]
DEployment succeeds even -Provisioning Site Collection fails and marks as Completed creating site collection.... this is also the same case as the Create Provision Matter List step.

Is this still good deployment ? logs says Deployment Completed Successfully

<img width="691" alt="capture" src="https://cloud.githubusercontent.com/assets/25953447/23211716/58a0067c-f93e-11e6-8386-7cd547d0d660.PNG">

**Comment by premchandpl** [comment]
@wauph These are the only errors your are getting? Can you validate whether the outlook addin for matter center has been published and all the content types has been created or not?

The error you are getting is related to the client that you want to create as part of deployment. Can you verify whether you have given the correct information in the "MCDeploymentConfig.xlsx" in the sheet "Client_Config" 

If all that information is good, then this issue should not arise

**Comment by amitabhm21** [comment]
@wauph  is this issue resolved ?

**Comment by amitabhm21** [comment]
Closing this issue. Please reopen if needed.
