### ISSUE TITLE
Need clarification on the deployment elements...

### ISSUE THREAD

**Issue by dioulos** [Microsoft/mattercenter#67]
I managed to use the script to deploy the solution but there is certain part that are still not working correctly. However I must first make sure that everything are deployed where it supposed to be.

Hi All,

So I would have confirmation from those who have managed to deploy the solution and have it working FULLY. 

Do the script create the following element into your app catalog?

![image](https://cloud.githubusercontent.com/assets/11888581/12717298/d99eec2a-c8de-11e5-9e1f-a6a19250fe1d.png)

In this case "MatterCenterMatters" is the list that add items of created matters
"Matter Center" is the hosted app that open a page where you can create a new matter
"Matter Center OneDrive.." is another hosted app. In my case it does not work
and the last two "MatterCenterHelp..." are sharepoint list.

In my client site collection  (created by the script) I have the following list:

![image](https://cloud.githubusercontent.com/assets/11888581/12717390/790c4276-c8df-11e5-8643-a806ace77d15.png)

That's it. I thought that it would have a list (a calendar and other stuff) representing any created matter but this doesn't work (it might be a configuration issue).

Then have you created a site collection called MatterCenter?
Did you add the url of that site collection as the Site_Url in your constant.resx file? (What did you put as the Tenant_Url? the same then the Site_Url?)
Does that site collection contain elements that the script creates for you or did you had to create anything manually?

When you had to adjust settings did you use the resx file in the bin folder or the App_GlobalResources folder?

**Comment by DaveyDoo** [comment]
Hello!
I can answer a few of your questions, as I have Matter Center up and running on my firm's tenant.
>Do the script create the following element into your app catalog? (Matter Center One Drive Bulk Actions, Matter Center, MatterCenterHelpLinks, MatterCenterHelpSection, MatterCenterMatters)
Yes
>In this case "MatterCenterMatters" is the list that add items of created matters
Yes
>"Matter Center" is the hosted app that open a page where you can create a new matter
Yes 
>"Matter Center OneDrive.." is another hosted app. In my case it does not work
Yes. Mine opens to a blank page.
>I thought that it would have a list (a calendar and other stuff) representing any created matter 
When a new matter is created, if you check calendar (and task list, etc) it will create those.  They will show up on the site collection page for that client.
>Then have you created a site collection called MatterCenter?
No. Matter Center is not a site collection.  The individual clients have site collections.
>Did you add the url of that site collection as the Site_Url in your constant.resx file?
No. That is the tenant home, i.e. https://MYTENANT.sharepoint.com  Tenant_Url is the same.
>Does that site collection contain elements that the script creates for you or did you had to create anything manually?
There were some managed metadata mappings that the scripts didn't set correctly and there was content type publishing that had to be done manually.
>When you had to adjust settings did you use the resx file in the bin folder or the App_GlobalResources folder?
Yes. In the service's deployed bin folder's constants.resx file, I had to change the value of Provision_Matter_App_URL to https://MYTENANT.sharepoint.com/sites/catalog/MatterCenter

Hope that helps.
Dave

**Comment by dioulos** [comment]
Thanks a lot for that DaveDoo. This has helped a lot as now I know that I pretty much done everything correctly but perhaps few things...

You said that there was some content type publishing that had to be done manually...are you talking about  the republishing on the content type hub AFTER the managed metadata remapping has been done?

My case is that the matter associated lists are created  but then during the process (i.e. CreateMatter) something goes wrong and a part of the code delete these associated lists.

The only part which I am not sure if it has done it correctly is the content type republishing.

What are the steps you took to republish the content type after you remapped the metadata? How can I verify that the republishing has been done correctly?

**Comment by DaveyDoo** [comment]
Follow the steps in Appendix C of the Build and Deployment Guide.  I don't know of a way to verify that it has been done correctly. There will be a delay of 30 minutes or longer while Office 365 does its stuff on the backend.

**Comment by ctrulove** [comment]
@dioulos Pinging you to see if you have the information you need. If you are still experiencing issues, please let us know so that we can troubleshoot and resolve.

**Comment by dioulos** [comment]
thanks @ctrulove I managed to install the addin correctly. while it is a nice product I need to figure out how to make this product more seamless with our SharePoint site as currently (and this is a sharepoint addin things) the UX is totally different then the rest of the site.
