### ISSUE TITLE
Matters not appearing

### ISSUE THREAD

**Issue by tasgray** [Microsoft/mattercenter#673]
Hi,

I have an older deployment of Matter Center running version 1. Everything seems to work correctly except I am unable to see any matters when they are created. I have created a client following the steps in the deployment guide and verified that it appears in the list of clients on the Matter Center settings page (SitePages/Settings.aspx).

I've now created a few matters and everything appears to work correctly. The matter dashboard is created and I can view it without a problem. The only issue is that no matters appear on the matter center homepage (/sitepages/MatterCenterHome.aspx). Are there any documented steps for troubleshooting this problem?

Appreciate any help. Thank you.

**Comment by premchandpl** [comment]
@tasgray Matter Center has been revamped and lot of new features has been added and deployment also has been simplified a lot. Deploy the new matter center 2 and let us know if you face any issues.

I assume you have upgraded to Matter center 2. If no results are appearing in the MatterCenterHome.aspx page, can you please verify in the Azure Web AppSettings whether SearchResultSourceId is having any guid or some text. If some guid is not present, then that can be the reason the page is not loading for MatterCenterHome.aspx

**Comment by tasgray** [comment]
@premchandpl thank you for getting back to me. I am in the process of updating to version 2 and run in to an issue with the azure deployment. Deploying the web plan is taking a very long time and showing status code 429 with the following errors:

{ "error": { "code": "GatewayTimeout", "message": "The gateway did not receive a response from 'Microsoft.Web' within the specified time period." }, "Code": "429", "Message": "Cannot acquire exclusive lock to create or update this server farm. Retry the request later." }

Any ideas on what might be causing this? I suspect it is attempting to lock the SharePoint catalog site.

**Comment by tasgray** [comment]
@premchandpl Dug a little deeper in to the events (this is all new to me by the way) and found this

![image](https://cloud.githubusercontent.com/assets/5292389/23655436/15771660-0389-11e7-888d-49cef70d41fc.png)

Any help appreciated.

**Comment by tasgray** [comment]
Please disregard above. All seems to have worked :)
