### ISSUE TITLE
CSS and UI Formatting not seeming to load correctly

### ISSUE THREAD

**Issue by pjThinker** [Microsoft/mattercenter#674]
Hi guys, 

Seem to have a bit of a problem and I need to confirm what I am seeing, we have been working on an implementation of matter center, it seems perfect for what we need, but we may need some help with the UI not loading. 

After implementation the following is the interface we get for Document view and Matter listing, as well as the menu item. As you can see it would seem as if the CSS hasn't set in, or we have missed a component, if we could have some feedback on something that may just be a configuration problem this would be great.

![web1](https://cloud.githubusercontent.com/assets/17115344/23347487/cf46dcc2-fcf6-11e6-921b-a42b2415d78c.png)
![web2](https://cloud.githubusercontent.com/assets/17115344/23347488/cf734d5c-fcf6-11e6-9a3e-4f579fff1f32.png)
![web3](https://cloud.githubusercontent.com/assets/17115344/23347489/cf748546-fcf6-11e6-8b7f-209fe6bca76d.png)

**Comment by pjThinker** [comment]
This is very different to what we were expecting as seen here : 
https://www.youtube.com/watch?v=dvSo7j1_GiE

**Comment by premchandpl** [comment]
@pjThinker As discussed in the call, I assume all the issues are resolved and I am closing this. And for the video link that you have mentioned, I assume that's the old video and that is not the UI that has been developed.
