### ISSUE TITLE
MatterCenterHome.aspx

### ISSUE THREAD

**Issue by mfx0r** [Microsoft/mattercenter#677]
I have added the Content Editor web part and linked it to the MatterCenterHome.html file.
if I click on the aspx file, it will download the .html file.
However if I browse to the .aspx file in my web browser there is nothing inside of the web part except the title

**Comment by allenolayiwola** [comment]
Did not have to do this step in my latest install, might be a good idea to download the latest build and run again.

**Comment by amitabhm21** [comment]
The latest install script takes care if this, Please take the latest version of the code and deploy,
