### ISSUE TITLE
Issue in Step 6

### ISSUE THREAD

**Issue by arjunagwan** [Microsoft/mattercenter#68]
Updating Log.resx file
Message: Unable to cast object of type 'System.Xml.Linq.XComment' to type 'System.Xml.Linq.XElement'.
Stacktrace:    at Microsoft.Legal.MatterCenter.UpdateAppConfig.UpdateConfig.UpdateResourceConstants(Dictionary`2 updateL
ist, String constantElement, String constantAttribute, List`1 manifestFile)
   at Microsoft.Legal.MatterCenter.UpdateAppConfig.UpdateConfig.UpdateConstants(Dictionary`2 updateList, String folderNa
me)
Message: Failed to update app schema files
Failed to update resource files
Updating Constants.resx file
Message: Unable to cast object of type 'System.Xml.Linq.XComment' to type 'System.Xml.Linq.XElement'.
Stacktrace:    at Microsoft.Legal.MatterCenter.UpdateAppConfig.UpdateConfig.UpdateResourceConstants(Dictionary`2 updateL
ist, String constantElement, String constantAttribute, List`1 manifestFile)
   at Microsoft.Legal.MatterCenter.UpdateAppConfig.UpdateConfig.UpdateConstants(Dictionary`2 updateList, String folderNa
me)
Message: Failed to update app schema files
Failed to update resource files
Updated Web.config
2/1/2016 7:13:26 AM - Updating resource and config files in solution failed

**Comment by kkhipple** [comment]
what values do you have for Image_Document_Icon and Image_General_Document in the Microsoft.Legal.MatterCenter.SharePointAppWeb\App_GlobalResources\Constants.resx file? 

make sure these include the full path to the files.

**Comment by arjunagwan** [comment]
**https://site.azurewebsites.net/Images/MC_Documents.png** for Image_Document_Icon
and 
**https://site.azurewebsites.net/Images/**  for Image_General_Document

**Comment by arjunagwan** [comment]
**Part 1 of the issue is resolved** 
Updating Log.resx file
Message: Unable to cast object of type 'System.Xml.Linq.XComment' to type 'System.Xml.Linq.XElement'.
Stacktrace: at Microsoft.Legal.MatterCenter.UpdateAppConfig.UpdateConfig.UpdateResourceConstants(Dictionary2 updateL ist, String constantElement, String constantAttribute, List1 manifestFile)
at Microsoft.Legal.MatterCenter.UpdateAppConfig.UpdateConfig.UpdateConstants(Dictionary2 updateList, String folderNa me) Message: Failed to update app schema files Failed to update resource files.


The Solution was Under the **CloudStorageConnectionString** was not proper instead of **https** the value feed in the **MCDeploymentConfig** excel sheet and **Microsoft.Legal.MatterCenter.Utility -> Log.resx** was **http**. So when I replaced **http** with **https**, Log.resx file issue was resolved.

**But I am still struggling with Part 2 of the issue**

Updating Constants.resx file Message: Unable to cast object of type 'System.Xml.Linq.XComment' to type 'System.Xml.Linq.XElement'. Stacktrace: at Microsoft.Legal.MatterCenter.UpdateAppConfig.UpdateConfig.UpdateResourceConstants(Dictionary2 updateL
ist, String constantElement, String constantAttribute, List1 manifestFile) at Microsoft.Legal.MatterCenter.UpdateAppConfig.UpdateConfig.UpdateConstants(Dictionary2 updateList, String folderNa
me)
Message: Failed to update app schema files
Failed to update resource files
Updated Web.config

**Comment by arjunagwan** [comment]
**Part 2 of the issue is resolved**
Under **Microsoft.Legal.MatterCenter.ProviderService -> App_GlobalResources-> Constants.resx** set the value in **Common_CSS_File_Location** with **/sites/catalog/SiteAssets/common/Styles/spCommon.css** and in **Common_JS_File_Location** with **/sites/catalog/SiteAssets/common/Scripts/spCommon.js**
this reolved my issue
