### ISSUE TITLE
Issue with step 7

### ISSUE THREAD

**Issue by AdamEckroth** [Microsoft/mattercenter#684]
When running Step 7 location>>\tree\master\cloud\src\solution\Deployment\Scripts and run Deploy-AzureResourceGroup.ps1

The following errors are are seen:

-Uploading files to SharePoint Library failed
-Updating Office, Outlook and SharePoint App schema files failed
It appears pre-requisites, so they are not sure why they are getting these errors.

**Comment by allenolayiwola** [comment]
make sure the account you are using has administrative rights on the SharePoint site collection. Also make sure you are using the right credentials in powershell!

**Comment by AISDUG** [comment]
A number of issues occurred

- Need to ensure that the Log Files for the Deployment are empty before running the install

- The SearchResultResourceID was not set correctly in Appsettings. The Deployment doc will be updated to give steps on how to resolve this if encountered

- The App Service Plan in Azure subscription was set to Basic. This needs to be set to Standard. This is currently documented in the Deployment guide.

- The matter center add in when added it was set to specific users and this was causing the add in not to appear to all the users in that tenant. 

These issues have now been resolved.

**Comment by amitabhm21** [comment]
Closing this issue as this was resolved with guidance provided. Please feel free to reopen if needed.
