### ISSUE TITLE
Subsite for Client

### ISSUE THREAD

**Issue by ns8482e** [Microsoft/mattercenter#686]
Is it possible to create sub site for each client rather than creating separate site collection?

**Comment by amitabhm21** [comment]
@ns8482e would you please elaborate on this ? 
You can create up to 500,000 site collections per tenant and Up to 2,000 subsites per site collection(recommended) [Microsoft Office 365 Enterprise subscriptions (E1 – E4)].
This gives more flexibility/scale with number of clients per tenant.

**Comment by premchandpl** [comment]
@ns8482e The current matter center requires site collection features and not sub site features. You can also look into amitabh comments for more information. So having site collections for clients wont be any issue

**Comment by ns8482e** [comment]
@amitabhm21 does the site collection limit stands true for business premium plan too?

**Comment by amitabhm21** [comment]
Yes. These limits apply. These are set to make sure that there is no impact to performance,
