### ISSUE TITLE
Deployment errors - DeployAzureResourceGroup.ps1

### ISSUE THREAD

**Issue by tasgray** [Microsoft/mattercenter#693]
Hi guys,

I've managed to deploy most of Matter Center successfully, but this particular powershell script has been difficult. Is it possible to run the script again and have it begin from where it last failed? Deploying the resources takes a very long time and all it takes it a simple error to then have to redeploy everything. Very frustrating!! :)

On to my real issue - I've progressed deployment pretty far now but cannot past these errors - the log doesn't give me much detail, so any help would be appreciated.

![image](https://cloud.githubusercontent.com/assets/5292389/23704696/3ff511d6-045a-11e7-856b-fb6fe0ed886d.png)

The limited information available in the log shows

8/03/2017 11:50:58 PM - Upload files to SharePoint Library
8/03/2017 11:51:37 PM - Uploading files to SharePoint Library failed
8/03/2017 11:51:37 PM - Step : Update Office, Outlook and SharePoint App schema files
8/03/2017 11:51:38 PM - Updating Office, Outlook and SharePoint App schema files failed

**Comment by ns8482e** [comment]
Can you share the log file?

**Comment by AISDUG** [comment]
Please ensure that the log files located at the below location have been deleted or moved and rerun the deployment. 
...\tree\master\cloud\src\solution\Deployment\Scripts\Logs

**Comment by sbammer** [comment]
Was this ever resolved?  The log files at the above location tell me absolutely NOTHING about why this error is occurring.  The log is just output from the powershell session.

**Comment by sbammer** [comment]
I figured it out in case anyone has this issue.  The path above MUST be empty before starting the script.  If it is not the script will fail no matter what.
