### ISSUE TITLE
CreateSampleData Script Issue

### ISSUE THREAD

**Issue by Vasanth1981** [Microsoft/mattercenter#695]
Hi Team,

I'm getting below error while running the CreateSampleData script, any idea What I'm missing here?

Message: Cannot access a disposed object.
Stacktrace:    at System.Security.SecureString.ToBSTR()
   at System.Runtime.InteropServices.Marshal.SecureStringToBSTR(SecureString s)
   at Microsoft.SharePoint.Client.Idcrl.SharePointOnlineAuthenticationProvider.FromSecureString(SecureString value)
   at Microsoft.SharePoint.Client.Idcrl.SharePointOnlineAuthenticationProvider.GetAuthenticationCookie(Uri url, String username, SecureString password)
   at Microsoft.SharePoint.Client.SharePointOnlineCredentials.GetAuthenticationCookie(Uri url, Boolean refresh)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.SetupRequestCredential(ClientRuntimeContext context, HttpWebRequest request)
   at Microsoft.SharePoint.Client.SPWebRequestExecutor.GetRequestStream()
   at Microsoft.SharePoint.Client.ClientContext.GetFormDigestInfoPrivate()
   at Microsoft.SharePoint.Client.ClientContext.EnsureFormDigest()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.Legal.MatterCenter.CreateSampleData.TermStoreOperations.GetClientDetails(Dictionary`2 configVal)
   at Microsoft.Legal.MatterCenter.CreateSampleData.Program.Main(String[] args) occurred at 3/10/2017 2:41:32 PM

**Comment by premchandpl** [comment]
@Vasanth1981 Can you ensure that excel file is closed? If not close the same and try again

**Comment by Vasanth1981** [comment]
Yes Prem. The Excel file closed.

**Comment by premchandpl** [comment]
@Vasanth1981 In the excel file, dont enter any data in the sample_data sheet and can you try?

**Comment by Vasanth1981** [comment]
No luck, same exception.

**Comment by premchandpl** [comment]
@Vasanth1981 In the help utilities solution, there will be a project called Microsoft.Legal.MatterCenter.CreateSampleData. Can you debug that project alone by updating the values in app.config

**Comment by Vasanth1981** [comment]
Yes. I did it. 
I'm getting the same exception on below line at GetClientDetails method in TermStoreOpertions.cs file.
// 2. Create taxonomy session
 TaxonomySession taxonomySession = TaxonomySession.GetTaxonomySession(clientContext);
 clientContext.Load(taxonomySession.TermStores);
 clientContext.ExecuteQuery();

Please let me know if you need further info.

Thanks,
Vasanth.

**Comment by premchandpl** [comment]
@Vasanth1981 Have you updated the term store admin with the account that you are using to execute the powershell script?

**Comment by Vasanth1981** [comment]
Yes. I'm part of Term Store Administrators group.

**Comment by premchandpl** [comment]
@Vasanth1981 ping me at premchand_76 skype call

**Comment by premchandpl** [comment]
@Vasanth1981 The create data script is longer used and we dont have any utility for bulk uploading matters. If any available in the future we will let you know that. Closing this as of now

**Comment by Vasanth1981** [comment]
Here is the fix on method GetClientContext() in MatterProvisionHelperUtility Class. The object was disposed while calling it in main().

internal static ClientContext GetClientContext(string siteURl, Dictionary<string, string> configVal)
        {
            string login = configVal["Username"];
            string password = configVal["Password"];
            bool isDeployedOnAzure = Convert.ToBoolean(configVal["IsDeployedOnAzure"], CultureInfo.InvariantCulture);

            /* Updated by Vasanth to fix the "Cannot access disposed object issue" */
            using (var securePassword = new SecureString())
            {
                if (!string.IsNullOrWhiteSpace(login) && !string.IsNullOrWhiteSpace(password) && !string.IsNullOrWhiteSpace(siteURl))
                {
                    foreach (char character in password)
                    {
                        securePassword.AppendChar(character);
                    }
                    using (ClientContext clientContext = new ClientContext(siteURl))
                    {
                        object onlineCredentials;
                        if (isDeployedOnAzure)
                        {
                            onlineCredentials = new SharePointOnlineCredentials(login, securePassword);
                            clientContext.Credentials = (SharePointOnlineCredentials)onlineCredentials; // Secure the credentials and generate the SharePoint Online Credentials                    
                        }
                        else
                        {
                            onlineCredentials = new NetworkCredential(login, securePassword);
                            clientContext.Credentials = (NetworkCredential)onlineCredentials; // Assign On Premise credentials to the Client Context
                        }
                        clientContext.ExecuteQuery();
                        return clientContext;
                    }
                }
                return null;
            }
            //Old logic
            #region  Commented
            /*ClientContext clientContext = null;
            try
            {
                using (clientContext = new ClientContext(siteURl))
                {
                    using (var securePassword = new SecureString())
                    {
                        foreach (char c in password)
                        {
                            securePassword.AppendChar(c);
                        }
                        object onlineCredentials;
                        if (isDeployedOnAzure)
                        {
                            onlineCredentials = new SharePointOnlineCredentials(login, securePassword);
                            clientContext.Credentials = (SharePointOnlineCredentials)onlineCredentials; // Secure the crdentials and generate the SharePoint Online Credentials                    
                        }
                        else
                        {
                            onlineCredentials = new NetworkCredential(login, securePassword);
                            clientContext.Credentials = (NetworkCredential)onlineCredentials; // Assign On Premise credentials to the Client Context
                        }
                    }
                }
            }
            catch (Exception exception)
            {
                Utility.DisplayAndLogError(Utility.ErrorFilePath, "Message: " + exception.Message + "\nStacktrace: " + exception.StackTrace);
            }
            return clientContext;*/
            #endregion
        }
