### ISSUE TITLE
Update labels for matter center gives an error

### ISSUE THREAD

**Issue by mcpsmith** [Microsoft/mattercenter#697]
I get see an  error in the console when loading the matter center admin page and pop up error/console error when clicking on the link to update labels for the matter center.

On loading, this error appears in the console:
 Warning: "Office.js is loaded outside of Office client (see image for more details)"

On clicking the "Update labels for matter center" link:
Popup: "Network issue. Unable to get the response from the server."
Console:

![image](https://cloud.githubusercontent.com/assets/26168907/23960461/6ddff894-097e-11e7-8493-f50e498c9679.png)

**Comment by premchandpl** [comment]
@mcpsmith The code for this issue has been checked in and if you pull or take latest code, this issue could have been resolved. Even though you got the error, the work has been done by the code and its only the json response that we are sending from the server is wrong. You can discard the error and you can continue and the app will work with out any issues

**Comment by mcpsmith** [comment]
@premchandpl the app is not working. Every link (Matters, Documents, etc) just hangs.

**Comment by mcpsmith** [comment]
I following instructions specified in https://github.com/Microsoft/mattercenter/issues/642
and it seems to be working a little better now. Thank you.

**Comment by premchandpl** [comment]
@mcpsmith The problem might be  your search results source is wrong in your azure web app settings. Go to your azure web app settings and check what value is there for SearchResultSourceId. If the value is System.Object.String, then it is wrong. This value needs to be updated with GUID which you can obtain from the root site collection

1. Goto root site collection
2. Go to settings page of site collection
3. Under Site Collection Administration, click on "Search Result Sources"
4. Click on "_MatterCenter"
5. Copy the URL from the browser into some editor
6. Take the value of Sourceid and replace %2d with "-" and copy that value to "SearchResultSourceId" in azure app settings
7. Save it

This should solve the issue. Let me know if you still face some issues and you can ping me at premchand_76 on skype

**Comment by premchandpl** [comment]
@mcpsmith See the below steos for more information

1. https://<>.sharepoint.com/_layouts/15/manageresultsources.aspx?level=sitecol and click on mattercenter. 
2. Then from url get source id. You should replace %2D in sourceid value with -.
3. Go to azure portal -> your web site appsettings and update the value for searchresouredid settings.

**Comment by mcpsmith** [comment]
@premchandpl  - thank you that worked.
