### ISSUE TITLE
Step 10 - Azure credentials for Azure Resource Management

### ISSUE THREAD

**Issue by lisataka** [Microsoft/mattercenter#71]
Hello,

I'm getting the following error in Login-AzureRmAccount, is there a workaround for this? The script continues after throwing this exception. 
Is this really an error, or can it be ignored?

2/8/2016 1:34:46 PM - Step 10: Publishing files to Azure/IIS
2/8/2016 1:34:46 PM - Please enter your Azure credentials for Azure Resource Management
Login-AzureRmAccount : The term 'Login-AzureRmAccount' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again.
At C:\Customers\mattercenter\mattercenter-master\deployments\Scripts\PublishOnAzure.ps1:143 char:4
+ if(Login-AzureRmAccount)
+    ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Login-AzureRmAccount:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
2/8/2016 1:34:46 PM - Please enter your Azure credentials for Azure service management
2/8/2016 1:35:29 PM - Publishing web service on Azure
2/8/2016 1:35:39 PM - Publishing web site on Azure
2/8/2016 1:35:49 PM - Updating App settings for website
2/8/2016 1:36:04 PM - Updating App settings for web service

**Comment by aravindmp** [comment]
Did you install the latest azure powershell sdk in your machine ?

**Comment by lisataka** [comment]
Yes, I did.
I have a question regarding that.  I run the script in the Windows Powershell ISE.  Should I launch the ISE from Azure PowerShell rather than from Windows Powershell?

Thanks,
Lisa

**Comment by lisataka** [comment]
Hello Aravind,

I downloaded and installed the Azure Powershell from the Build and Deployment guide.
Here are the list of cmdlets, which looks like the Login-AzureRmAccount is missing.
Where is the SDK? Or the latest Azure Powershell.

Import-AzurePublishSettingsFile   Cmdlet    Azure
Import-AzureSiteRecoveryVaultS... Cmdlet    Azure
Import-AzureStorSimpleLegacyAp... Cmdlet    Azure
Import-AzureStorSimpleLegacyVo... Cmdlet    Azure
Import-AzureVM                    Cmdlet    Azure
Invoke-AzureHDInsightHiveJob      Cmdlet    Azure
Invoke-AzureRemoteAppSessionLo... Cmdlet    Azure
Move-AzureDeployment              Cmdlet    Azure
New-AzureAclConfig                Cmdlet    Azure
New-AzureAffinityGroup            Cmdlet    Azure
New-AzureApplicationGateway       Cmdlet    Azure
New-AzureAutomationAccount        Cmdlet    Azure
New-AzureAutomationCertificate    Cmdlet    Azure
New-AzureAutomationConnection     Cmdlet    Azure

**Comment by lisataka** [comment]
I installed Azure-Powershell.1.2.1.msi and it issue was resolved. you can find the .msi at the following link  https://github.com/Azure/azure-powershell/releases

**Comment by Kandarp2516** [comment]
Hey, I installed Azure powershell 3.2.0 on windows server 2012 rs and getting the same issue. Seems like the Login-AzureRMAccount is not in the list of available cmdlets.
[http://stackoverflow.com/questions/41050880/login-azurermaccount-and-select-azurermsubscription](url)

any suggestions. 
Thanks

**Comment by PHBeagle** [comment]
The issue with the PowerShell install still remains.  I ran into the issue today installing on a VM with Windows Server 2012R2 Datacenter.  

I was able to resolve by installing Azure PowerShell from Lisa's link, though I used version 3.3.0.
[https://github.com/Azure/azure-powershell/releases](url)

**Comment by WilsonReddy** [comment]
@PHBeagle  Deploy from Windows 10 or windows server 2016.  Deployment is not compatible with with other windows OS.
