### ISSUE TITLE
Word Online unable to connect to catalog

### ISSUE THREAD

**Issue by mcpsmith** [Microsoft/mattercenter#710]
I get the following error when trying to add the Matter Center Add in through Word-online. 

![image](https://cloud.githubusercontent.com/assets/26168907/24710025/d69d09b4-19e9-11e7-9a7c-398de598851e.png)

**Comment by premchandpl** [comment]
@mcpsmith Can you verify your office manifest file and check whether all the things are properl yset or not

**Comment by mcpsmith** [comment]
Where can I find the office manifest file? What settings should I look for? Thank you.

**Comment by premchandpl** [comment]
@mcpsmith can we connect tomorrow and I will help you to resolve the issue. My skype id is: premchand_76@hotmail.com

**Comment by WilsonReddy** [comment]
In deployment folder you can find it. We are updating manifest file during development. You can also find manifest file in solution, but you need to update url before publishing office app.

Sent from my Windows Phone
________________________________

**Comment by mcpsmith** [comment]
@premchandpl @WilsonReddy  
It appears to be working now. Thank you.
