### ISSUE TITLE
String was not recognized as a valid Boolean.

### ISSUE THREAD

**Issue by przemasd** [microsoft/mattercenter#711]
When I try upload document by web explorer I get the error server 500 "String was not recognized as a valid Boolean."

![obraz](https://cloud.githubusercontent.com/assets/25458793/24747951/4fb7ed62-1abe-11e7-8e82-2a55e3a9514f.png)

this error is only when I try upload document form my computer using darg and drop.

**Comment by premchandpl** [comment]
@przemasd I need to analyze the request payload that you are sending when you are uploading the files from the desktop. You can get that information from the developer tools of the web browser

**Comment by przemasd** [comment]
In UploadFiles method in DocumentController a properties "AllowContentCheck" of Form in Request is  undefined... Somebody know how fix it ?
