### ISSUE TITLE
Renaming Matter Center Beta Outlook AddIn

### ISSUE THREAD

**Issue by mcpsmith** [Microsoft/mattercenter#712]
Is there a way to rename the Outlook Addin, it installed correctly and works, I would like to remove the "Beta" from the name of the add in. Thanks

**Comment by premchandpl** [comment]
@mcpsmith 

1. Open MS Matter Outlook manifest file            tree\master\cloud\src\solution\Microsoft.Legal.MatterCenter_Outlook\Microsoft.Legal.MatterCenter_OutlookManifest\Microsoft.Legal.MatterCenter_Outlook.xml
2. Edit both DisplayName and Description xml nodes (Line 8 and 9)
3. Delete existing outlook addin from Office 365 portal
5. Upload the new manifest file
6. Restart your outlook

**Comment by mcpsmith** [comment]
@premchandpl  - Can you provide some more details on how to delete the add in and upload the new manifest file? Thank you!

**Comment by mcpsmith** [comment]
I have turned off the add-in, and uploaded the edited file, but the Add In still shows up as Matter Center Beta.

![image](https://cloud.githubusercontent.com/assets/26168907/24930023/1020cc34-1ed6-11e7-88a6-2cbe2e386e72.png)

**Comment by premchandpl** [comment]
@mcpsmith let me know if we can have skype call premchand_76@hotmail.com

**Comment by mcpsmith** [comment]
@premchandpl - hello premchand - I have sent you a skype meeting if you are available - thank you!

**Comment by mcpsmith** [comment]
Thank you @premchandpl - I had to edit the Add-in by going into Admin->Admin centers->Exchange->Organization->add in to delete and readd the add-in.
