### ISSUE TITLE
Angular Error on Matter page

### ISSUE THREAD

**Issue by SteveClements** [Microsoft/mattercenter#715]
Hi, I have a new installation of MC, everything looks ok, except when I browse to the matters or documentation page (within SP so /SitePages/MatterCenterHom.aspx?section=1) I get 2 errors in the console. 

The first is a 404...
`https://<webname>.azurewebsites.net/%7B%7BuploadedFile.documentIconUrl%7D%7D 404 (Not Found)`

The second is an angular resource error.
`
angular.js:13920 Error: [$resource:badcfg] http://errors.angularjs.org/1.5.8/$resource/badcfg?p0=ErrorNaNn%20resource%configuration%for%20action%20%60%7B0%7D%60.%20Expected%20response%20to%contain%20an%20%7B1%7D%20but%20got%20an%20%7B2%7D%20(Request%3A%20%7B3%7D%20%7B4%7D)&p1=get&p2=array&p3=object&p4=POST&p5=%2Fapi%2Fv1%2Fmatter%2Fget
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:6:412
    at https://cdnjs.cloudflare.com/ajax/libs/angular-resource/1.5.8/angular-resource.js:777:25
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:131:20
    at m.$eval (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:145:347)
    at m.$digest (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:142:420)
    at m.$apply (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:146:113)
    at l (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:97:322)
    at J (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:102:34)
    at XMLHttpRequest.t.onload (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:103:4)`

Any ideas?

I can get to the settings page ok.

I cannot create a matter either...it gets to step 2/3 then throws these errors.
List Does Not exist, Item does not exist.
`POST http://<weburl>.azurewebsites.net/api/v1/matter/assigncontenttype 400 (Bad Request)
ai.0.js:1 POST http://<weburl>.azurewebsites.net/api/v1/matter/assignuserpermissions 500 (Internal Server Error)
ai.0.js:1 POST http://<weburl>.azurewebsites.net/api/v1/matter/createlandingpage 500 (Internal Server Error)`

Any ideas?

**Comment by SteveClements** [comment]
I have just spotted what I think was the issue with the matters and documents.
In Azure, application settings, SearchResultSourceID was in as an array of object System.Object[], I didn't actually look to see if there were any values in there.
I renamed that key and created a new one with the result source id that was created during provisioning "Matter Center" and now at least the pages load.

I still get the 404 errors looking for `row.entity.documentIconUrl` etc.

But more of an issue, I still am unable to create a matter.  I get different errors, assigning content type.
The latest is this ... "Matter 1 is the name I have given the matter I'm trying to create" - should this process be creating a list with that name?
I am SC admin and in the owners group!

> MessageList:    'Matter 1' does not exist at site with URL 'https://xxx.sharepoint.com/teams/steve365'.
ErrorCode   500
MethodName:   ConfigureXMLCodeOfWebParts

**Comment by premchandpl** [comment]
@SteveClements 

You can ignore the error "I still get the 404 errors looking for row.entity.documentIconUrl etc."

For the error you are getting in step 2/3, can you verify the same for me:

I think the client site collection (that you might be using for creating a matter) that has been created will be having 3 managed columns called PracticeGroup, AreaOfLaw and SubAreaOfLaw.

1. Go to client site collection
2. Click on site settings
3. Click on "Site Columns"
4. Check whether PracticeGroup, AreaOfLaw and SubAreaOfLaw. managed site columns are pointing to "PracticeGroup" term
5. If not, set all the above managed columns to that practicegroup term and save the same
6. After that try to create a matter

Check whether those are pointing to "PracticeGroup". Check the below screen shot

![image](https://cloud.githubusercontent.com/assets/3001352/24967167/0d055faa-1f5e-11e7-8425-97b26d63c0bb.png)

Also this github post for more information

https://github.com/Microsoft/mattercenter/issues/124

**Comment by SteveClements** [comment]
@premchandpl 
That was it, all up and running now, thanks!
