### ISSUE TITLE
Not ready for Visual Studio 2017

### ISSUE THREAD

**Issue by mjlally07** [Microsoft/mattercenter#720]
I tried to build and deploy from VS 2017 Enterprise which required Nuget package updates -- publish succeeded eventually but wep app wouldn't load.  Opened up VS 2015 Pro and re-cloned -- publish and web app now working.

**Comment by premchandpl** [comment]
Matter center application is not ready for VS 2017. Once Matter center is ready we will announce the same. Closing this request for time being
