### ISSUE TITLE
More Info on Permission Levels

### ISSUE THREAD

**Issue by Vasanth1981** [Microsoft/mattercenter#721]
Hi,
Can you please explain the below permission groups,

In App Catalog site:
Matter Center Users
Provision Matter Users

In Matter Center Site Collection:
Matter Center Interfaces

Also, How these permissions are associated with below group,
Matter Center Site Visitors, Members and Owners

-Vasanth.

**Comment by premchandpl** [comment]
@Vasanth1981 
**Provision Matter Users** - Only the users in this group will have permissions to create a matter (Create matter link will be visible)
**Matter Center Users** - If the users are not present in this group, then he may not access the catalog site collection resources such as master pages, site assets etc and the matter landing page and document details page will not be rendered properly
**Matter Center Interfaces** - In V2 we are not using this group and I think this group is not much useful in V2 and I am not aware how this has been used in V1
**Matter Center Site Owners** - People in this group only can access settings page. If the login user is not in this group, and when they accsess settings page, the user will get access denied page
**Matter Center Site Visitors and  Matter Center Site Members** are not used in V2 also in V1, these groups will be having less significance and these groups will get created automatically when we create a site collection
