### ISSUE TITLE
Can't create matter Step 3/3 fails

### ISSUE THREAD

**Issue by mwtall** [Microsoft/mattercenter#722]
I am still unable to create matter after I have spent weeks deploying the Office 365 Matter Center. I ran into multiple errors in deployment as well as in creating matter...however, this final error I can't get past.

I'm getting a "Error occurred while updating the matter metadata: Incorrect Inputs" on Step 3/3. See screenshot.

![capture](https://cloud.githubusercontent.com/assets/8932359/25187023/e2bc4bf4-24ef-11e7-8e4d-b461ecc5530c.PNG)

Any thoughts on what is going on?

Thanks,
Matt

**Comment by premchandpl** [comment]
@mwtall We need to see the developer tool of the browser and need to check which api is throwing 500 internal error and we need to see the error response of that api. Can you share that information to me

**Comment by amitabhm21** [comment]
@mwtall is this issue still open ?

**Comment by premchandpl** [comment]
@mwtall I will help you to resolve the issue on this one. Let me know what is the best way to contact you on this. Let me know whether skype will help you or not?

**Comment by premchandpl** [comment]
@mwtall my skype id is premchand_76@hotmail.com

**Comment by premchandpl** [comment]
@mwtall No response on this thread for a long time and closing the same. Reopen the same and I will help you to resolve the issue for you
