### ISSUE TITLE
Error at step 10. ErrorCode: 500 ClassName: SPOAuthorization

### ISSUE THREAD

**Issue by shijov** [Microsoft/mattercenter#730]
Getting an error at step 10, when I open the /#/admin URL of the web app

DescriptionError occured in the system. Please contact the administrator
MessageOne or more errors occurred.
ErrorCode500
MethodNameGetClientContext
ClassNameSPOAuthorization
LineNumber 80
StackTrace at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
 at Microsoft.Legal.MatterCenter.Utility.SPOAuthorization.GetClientContext(String url) in C:\mattercenter-master\tree\master\cloud\src\solution\Microsoft.Legal.MatterCenter.Service\Microsoft.Legal.MatterCenter.Utility\Authorization\SPOAuthorization.cs:line 80
 at Microsoft.Legal.MatterCenter.Repository.SPList.CheckPermissionOnList(Client client, String listName, PermissionKind permission) in C:\mattercenter-master\tree\master\cloud\src\solution\Microsoft.Legal.MatterCenter.Service\Microsoft.Legal.MatterCenter.Repository\SharePointInfo\SPList.cs:line 500
 at Microsoft.Legal.MatterCenter.Service.MatterController.CanCreateMatter(Client client) in C:\mattercenter-master\tree\master\cloud\src\solution\Microsoft.Legal.MatterCenter.Web\Controllers\MatterController.cs:line 526

Followed Step 8 and 9 as mention in #694 but it did not resolve my issue.

The only thing we might be doing wrong is that we are using a Microsoft Bulk Credit subscription. The offer name is Unknown(azure screenshot below). Will this still make the SSL to work incorrectly as mentioned in reply to #694?

![image](https://cloud.githubusercontent.com/assets/28421764/25731543/bb6635c4-3179-11e7-8e96-f232963d1f58.png)

**Comment by premchandpl** [comment]
@shijov I think there is some issue in setting up your azure active directory for azure app and sharepoint online. Some how the token that is getting passed to sharepoint online is wrong and that's the reason you might be getting that error

**Comment by shijov** [comment]
@premchandpl Below is my configuration for the app from azure active directory.

![image](https://cloud.githubusercontent.com/assets/28421764/25732097/a9473640-317e-11e7-8375-8dcd77fc49c1.png)

![image](https://cloud.githubusercontent.com/assets/28421764/25732111/cef5a2be-317e-11e7-9d23-4044e9909286.png)

![image](https://cloud.githubusercontent.com/assets/28421764/25732125/f8b5bbd4-317e-11e7-824b-d0c7a8dd8b4b.png)

 I have updated the AD Application Key and ClientID using the KeyVaultSecret.ps1

**Comment by premchandpl** [comment]
@shijov I assume both Azure and Office 365 are using same tenant

**Comment by premchandpl** [comment]
@shijov can we have live meeting or skype meeting to resolve the issues

**Comment by shijov** [comment]
Yes. Both are in the same tenant

**Comment by premchandpl** [comment]
@shijov can we connect using skype. My skype id is premchand_76@hotmail.com

**Comment by shijov** [comment]
I might have provided the wrong app catalog URL while the resource group was created. I will retry the steps, will connect if I am still unable to resolve the issue. @premchandpl  Thanks for your skype contact mate.

**Comment by shijov** [comment]
@premchandpl It was an issue with the AppCatalog site URL in step 7, $CentralRepositoryUrl. It works now.
Thanks for the support.

**Comment by meemakwana** [comment]
@shijov , I am facing the same issue. I have verified all the config values mentioned are correct. Could you please help me resolving this issue ?
