### ISSUE TITLE
Azure Deploy Errors

### ISSUE THREAD

**Issue by yizharm** [Microsoft/mattercenter#748]
Hello,
I tried to build and deploy to Azure, but getting many errors.
I went through the installation guide several times, and sill getting Server Error 500.

I noticed that the "appsettings.json" file isn't updated after running PS1 files.
I would appreciate if anyone could help.

Thanks,

Yizhar

**Comment by premchandpl** [comment]
@yizharm I am eager to help you on this. Let me know how should I contact you on this? My skype id is premchand_76@hotmail.com

**Comment by yizharm** [comment]
@premchandpl - Thank you very much.
I've sent you Skype request.
