### ISSUE TITLE
Step 7. Deployment Issue 

### ISSUE THREAD

**Issue by allenolayiwola** [Microsoft/mattercenter#757]
Hi @premchandpl,

Tried the suggestions above, still getting the same error. See screenshots before and after trying the above step. Kindly assist.

![capture 1](https://user-images.githubusercontent.com/1235545/27612912-49e56152-5b88-11e7-91c0-f7cdbfecfa87.PNG)
![capture 2](https://user-images.githubusercontent.com/1235545/27612911-49e1d4b0-5b88-11e7-9cc1-ad9542ed4509.PNG)

Thanks

**Comment by premchandpl** [comment]
@allenolayiwola Need to check whether Set-AzureRmWebApp cmd let has been changed. I will revisit this and will get back to you in a day or two. Currently busy with some other work

**Comment by gustavnavar** [comment]
Just modify KeyVault-Config.ps2 script and remove Tenant info from appSettings in line 181:
$appSettings = @{ `
				"General:SiteURL" = $SiteURL; `
				"General:CentralRepositoryUrl" = $CentralRepositoryUrl; `
				"General:KeyVaultURI" = $kvSettings.VaultUri; `
				"General:KeyVaultClientID" = $ADApplicationId; `
				"General:KeyVaultCertThumbPrint" = $global:thumbPrint;`
				"Search:SearchResultSourceID" = $SearchResultSourceId.ToString();`
				"WEBSITE_LOAD_CERTIFICATES" = $global:thumbPrint;`
			}

**Comment by tstojecki** [comment]
#774 
I think this is the same issue. My suggestion is to change the assignment of global:TenantName from $global:TenantName = $subsc.Context.Tenant.Domain to $global:TenantName = $subsc.Context.Tenant.Directory

Removing it all together might work too, I haven't tried that.
