### ISSUE TITLE
Search Matters don't work after update Azure App Service to newest version

### ISSUE THREAD

**Issue by przemasd** [Microsoft/mattercenter#759]
I have issue when i update matter Center azure App Service. 

`{
  "errorCode": "500",
  "message": "Object reference not set to an instance of an object.",
  "description": "Error occured in the system. Please contact the administrator",
  "isTokenValid": false,
  "stackTrace": "   at Microsoft.Legal.MatterCenter.Web.Common.MatterProvision.<GetMatters>d__23.MoveNext() in C:\\Matter Center\\tree\\master\\cloud\\src\\solution\\Microsoft.Legal.MatterCenter.Web\\Common\\MatterProvision.cs:line 276\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.Legal.MatterCenter.Service.MatterController.<Get>d__15.MoveNext() in C:\\Matter Center\\tree\\master\\cloud\\src\\solution\\Microsoft.Legal.MatterCenter.Web\\Controllers\\MatterController.cs:line 303",
  "className": "<GetMatters>d__23",
  "methodName": "MoveNext",
  "lineNumber": 276,
  "errorDate": null,
  "exception": {
    "ClassName": "System.NullReferenceException",
    "Message": "Object reference not set to an instance of an object.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at Microsoft.Legal.MatterCenter.Web.Common.MatterProvision.<GetMatters>d__23.MoveNext() in C:\\Matter Center\\tree\\master\\cloud\\src\\solution\\Microsoft.Legal.MatterCenter.Web\\Common\\MatterProvision.cs:line 276\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.Legal.MatterCenter.Service.MatterController.<Get>d__15.MoveNext() in C:\\Matter Center\\tree\\master\\cloud\\src\\solution\\Microsoft.Legal.MatterCenter.Web\\Controllers\\MatterController.cs:line 303",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nMoveNext\nMicrosoft.Legal.MatterCenter.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\nMicrosoft.Legal.MatterCenter.Web.Common.MatterProvision+<GetMatters>d__23\nVoid MoveNext()",
    "HResult": -2147467261,
    "Source": "Microsoft.Legal.MatterCenter.Web",
    "WatsonBuckets": null
  },
  "isErrror": true
}`

![image](https://user-images.githubusercontent.com/25458793/27735193-a4b93550-5d9e-11e7-80b1-c89a8f9db317.png)

![image](https://user-images.githubusercontent.com/25458793/27735495-35ca1dec-5da0-11e7-8e8f-05a632c23e6e.png)

**Comment by premchandpl** [comment]
@przemasd Can we have a skype meeting for this and I will help you to resolve the issue for you

**Comment by premchandpl** [comment]
my skype id is premchand_76@hotmail.com

**Comment by przemasd** [comment]
this error was in mapping matter on service method "GetMatter" in MatterProvision 

`if (key.ToString().ToLower() == searchSettings.ManagedPropertyMatterDefaultContentType.ToLower())
                        {
                            ServiceUtility.AddProperty(matterData,
                                configuration.GetSection("Search").GetSection("SearchColumnsUIPickerForMatter").GetSection("matterDefaultContentType").Key,
                                searchResult[key].ToString());
                        }`

searchResult[key] is null for key equals searchSettings.ManagedPropertyMatterDefaultContentType.

I fixed this error adding ? before .ToString()

**Comment by premchandpl** [comment]
@przemasd Can you make a pull request of this change? Also we made a change in the search schema and that is causing the issue. 

Need to add a new managed property called "MCMatterDefaultContentType". See the below screen shot for the same

![image](https://user-images.githubusercontent.com/3001352/27974862-a1400d6a-6314-11e7-97a3-643a5d16aed9.png)

1. Search for any empty refinable string. In the above screen shot, I have used "RefinableString112" and  we have used alias "MCMatterDefaultContentType" and mapped to crawled property called "MatterCenterDefaultContentType" and this will also solve the issue.

If the issue has been solved, can I mark it has closed?

**Comment by premchandpl** [comment]
@przemasd I am closing this issue. Let me know if this is still an issue
