### ISSUE TITLE
Error when creating a matter - step 2

### ISSUE THREAD

**Issue by sbammer** [Microsoft/mattercenter#761]
Hi - when creating a matter I receive the following error during step 2 of matter creation.  I tried unchecking the send email box - same result.  Where do I look for the cause of this?  Not much to go on here.  I don't know where to begin to figure this out.

[2017-07-14_7-33-40.pdf](https://github.com/Microsoft/mattercenter/files/1148370/2017-07-14_7-33-40.pdf)

**Comment by premchandpl** [comment]
@sbammer can you look into the github issues - https://github.com/Microsoft/mattercenter/issues/715 and check whether that solution is going to solve your issue. If not let me know

**Comment by sbammer** [comment]
Hi premchandpl - I checked and all three of those columns have Practice Groups in the MatterCenterTerms Taxonomy.  That is not the cause of the error in my case.

**Comment by premchandpl** [comment]
@sbammer Can we have a skype call and we can debug the issue. My skype id is premchand_76@hotmail.com

**Comment by sbammer** [comment]
Sure – we have skype for business so I don’t think that will work.  Is there a web based one?

Steve           Bammer

SharePoint Administrator

Kemper Corporate Services
One Tower Lane, Lower Level     ,       Oakbrook Terrace        ,       IL              60181


630.368.8063<tel:630.368.8063>   /      +1 6307884782<tel:+1%206307884782>       Cell

sbammer@kemper.com<mailto:sbammer@kemper.com>
www.kemper.com<http://www.kemper.com/>

[cid:image912363.jpg@81BD5DE8.6E2FA81C]

**Comment by sbammer** [comment]
Hello,

I've made a group on Skype for us to chat, share and collaborate.
Join by click the link https://join.skype.com/AJTSqbjj5nhS


Steve           Bammer

SharePoint Administrator

Kemper Corporate Services
One Tower Lane, Lower Level     ,       Oakbrook Terrace        ,       IL              60181


630.368.8063<tel:630.368.8063>   /      +1 6307884782<tel:+1%206307884782>       Cell

sbammer@kemper.com<mailto:sbammer@kemper.com>
www.kemper.com<http://www.kemper.com/>

[cid:image859531.jpg@99AC8F0F.0C839EFF]

**Comment by sbammer** [comment]
Here's what I'm seeing in the logs when attempting to create a matter.

[2017-07-14_14-51-38.pdf](https://github.com/Microsoft/mattercenter/files/1149539/2017-07-14_14-51-38.pdf)

**Comment by premchandpl** [comment]
@sbammer Let me know when can we have skype chat to resolve the issue
