### ISSUE TITLE
Azure CSP

### ISSUE THREAD

**Issue by gustavnavar** [Microsoft/mattercenter#762]
Hi,

I tried to install Matter Center in a CSP subscription, but I couldn't because this kind of subscriptions are 100% ARM. 

All script commands are ARM, except 3 that create a web job in the Create-MatterCenterWebJob.ps1 script, that are ASM (e.g. New-AzureWebsiteJob ...). Is there any plan to support CSP subscriptions? Do you know any workaround for this?

By the way, what is this job for?

**Comment by premchandpl** [comment]
@gustavnavar The web job is for sending notifications to the users associated to the matter that is getting created. We haven't tested the matter using the CSP subscription. If we job creation is giving problem during deployment, you can comment that code and you can manually created web job after all the deployments are successfully completed
