### ISSUE TITLE
Matter Center Access

### ISSUE THREAD

**Issue by Variel07** [Microsoft/mattercenter#764]
Is anyone experiencing any issues accessing Matter Center?  The option to "create a new matter" is gone and none of the links are working.  Thanks

**Comment by premchandpl** [comment]
@Variel07 Have you taken new code and deployed to your tenant? Whether all the deployment steps has been executed properly? The option to create a new matter is based on the sharepoint permissions. If the sharepoint permissions has not been set properly, then that link wont appear.

For the create new matter link to appear in matter home page:

1. There will be a list called "ProvisionMatterList" in sharepoint catalog site collection
2. Permissions for this list are broken
3. There will be a sharepoint group called "Provision Matter Users" and this group should have "Contribute" permissions
4. The login user should be part of that group

Also check the browser developer tool and see if there are any console log errors
Also go to the network tab and check if there are any errors for matter center api

**Comment by Variel07** [comment]
@premchandpl Hi! Thanks for the response.  I haven't changed anything.  I was informed by Microsoft that I need to submit a ticket to Github for assistance.  :)

**Comment by premchandpl** [comment]
@Variel07 This is the environment issue in your tenant and something messed up over there. Since you have taken latest code, try to deploy the latest code and if you still face the same issue, let me know the same and I am closing this issue
