### ISSUE TITLE
Cannot Access Matter Center

### ISSUE THREAD

**Issue by Variel07** [Microsoft/mattercenter#765]
I cannot access Matter Center.

**Comment by premchandpl** [comment]
@Variel07 Can you let me know what is the problem? You are not able to access matter center code in git hub or you are not able to access matter center in your tenant?

**Comment by Variel07** [comment]
I am not able to access matter center as a tenant.  I posed the issue to Microsoft but they were unable to help me resolve the issue. They suggested I submit a ticket to GitHub. I can access Sharepoint but not Matter Center. Is there a way you can logon to my computer tomorrow to see what the issue may be? Thanks 

    On Thursday, July 27, 2017 4:44 PM, premchandpl <notifications@github.com> wrote:
 

 @Variel07 Can you let me know what is the problem? You are not able to access matter center code in git hub or you are not able to access matter center in your tenant?—

**Comment by Variel07** [comment]
I am available now if you want to jump on my computer to see what the issue is. Thanks

**Comment by premchandpl** [comment]
@Variel07 Will be available after 11:30 PM PST. Let me know how can I connect with you?

**Comment by Variel07** [comment]
Can you call my office number - 713-351-0307.  Thanks so much.  

    On Friday, July 28, 2017 12:07 PM, premchandpl <notifications@github.com> wrote:
 

 @Variel07 Will be available after 11:30 PM PST. Let me know how can I connect with you?—

**Comment by premchandpl** [comment]
@Variel07 sorry 11":30 AM PST

**Comment by premchandpl** [comment]
@Variel07 I will call to that number once I reach office

**Comment by Variel07** [comment]
That time works for me.  Thank you! 

    On Friday, July 28, 2017 12:21 PM, premchandpl <notifications@github.com> wrote:
 

 @Variel07 sorry 11":30 AM PST—

**Comment by premchandpl** [comment]
@Variel07 I am closing this issue. If you still face the issue with new matter center code reopen the same and I will help you on the same
