### ISSUE TITLE
Errors while running Deploy.ps1 "exe not recognized as the name of a cmdlet"

### ISSUE THREAD

**Issue by mcpsmith** [Microsoft/mattercenter#770]
I got many *.exe is not recognized as the name of a cmdlet" messages while running Deploy.ps1. Says Deployment completed successfully but I'm not seeing anything created in Sharepoint. Please assist. Thanks.

![image](https://user-images.githubusercontent.com/26168907/29535713-eba0bdcc-8688-11e7-8b06-3b5ecd07caa4.png)

![image](https://user-images.githubusercontent.com/26168907/29535752-1b484b62-8689-11e7-831f-0bffa50e49c1.png)

Got this message in Step 7 for all clients specified:
The remote server returned an error: (404) Not Found.<ClientName> 

![image](https://user-images.githubusercontent.com/26168907/29535803-4ae09140-8689-11e7-98da-6aba89009d93.png)

**Comment by premchandpl** [comment]
@mcpsmith 

1. Can you please check whether the deployment excel file has been closed? (MCDeploymentConfig.xlsx)
2. Also, can you please verify have you build Microsoft.Legal.MatterCenter.HelperUtilities.sln

**Comment by mcpsmith** [comment]
Yes Excel sheet was closed. I am able to build solution. I tried choosing Rebuild and get this error msg. How can I confirm the build was successful? Thanks

![image](https://user-images.githubusercontent.com/26168907/29537985-c60930cc-8691-11e7-9e19-cc26c9549998.png)

**Comment by mcpsmith** [comment]
Rebooted and reran, works now.
