### ISSUE TITLE
Failure in Deploy-AzureResourceGroup.ps1 with an empty global:TenantName

### ISSUE THREAD

**Issue by tstojecki** [Microsoft/mattercenter#774]
I am getting an error in KeyVault-Config.ps1 which is called by Deploy-AzureResourceGroup.ps1 when calling

`Set-AzureRmWebApp -Name $WebAppName -ResourceGroupName $ResourceGroupName -AppSettings $appSettings`

> Set-AzureRmWebApp : Cannot validate argument on parameter 'AppSettings'. Object reference not set to an instance of an object.

After debugging, the issue appears to be with the way global:TenantName is being set in Deploy-AzureResourceGroup.ps1

`$global:TenantName = $subsc.Context.Tenant.Domain`

Looking at the $subsc object it appears that it should be Directory as opposed to Domain. Please confirm whether I am on the right track and if so let me know if I should submit a PR.

**Comment by premchandpl** [comment]
@tstojecki Closing this as you have found out the issue. I will review it and will merge the same in the master
