### ISSUE TITLE
Script finished without errors, but lists are missing

### ISSUE THREAD

**Issue by tstojecki** [Microsoft/mattercenter#776]
I have gone through the deployment process per the deployment doc, it created the site collection under /teams/client and provisioned a site in azure under https://<...>.azurewebsites.net. However everything is failing now as the lists appear to be missing even through the deploy.ps1 didn't report any errors. 

Here is the snippet of the console output when running .\Deploy.ps1:

> 8/30/2017 8:53:18 PM - Completed updating search configuration file
> 8/30/2017 8:53:18 PM - Step 5: Activating SharePoint Server Publishing Infrastructure at Catalog site collection
> 8/30/2017 8:53:18 PM - Enabling the Feature with GUID
> 
> 
> DefinitionId       :
> Context            : Microsoft.SharePoint.Client.ClientContext
> Tag                :
> Path               : Microsoft.SharePoint.Client.ObjectPathMethod
> ObjectVersion      :
> ServerObjectIsNull :
> TypedObject        : Microsoft.SharePoint.Client.Feature
> 
> 8/30/2017 8:53:20 PM - Activated SharePoint Server Publishing Infrastructure Feature
> 8/30/2017 8:59:21 PM - Step 6: Creating Site Collection(s)
> 8/30/2017 8:59:21 PM - Provisioning Site Collection
> Creating site collection at https://[tenant].sharepoint.com/teams/microsoft
> Loading.
> ......Site Collection: https://[tenant].sharepoint.com/teams/microsoft is created successfully
> Creating Matter Center Interfaces group.
> Created Matter Center Interfaces group successfully
> Adding users to group: Microsoft Owners
> Successfully added users to group: Microsoft Owners
> Adding users to group: Microsoft Visitors
> Successfully added users to group: Microsoft Visitors
> 8/30/2017 9:02:54 PM - Completed creating site collection
> 8/30/2017 9:02:54 PM - Step 7: Update site collection view with fields
> 
> Updating View for site collection Microsoft
> Microsoft site collection view updated with field
> 8/30/2017 9:02:59 PM - Update site collection view with fields successfully
> 8/30/2017 9:02:59 PM - Step 8: Create Provision Matter List
> Creating Provision Matter List...8/30/2017 9:03:03 PM - Deployment completed successfully
> 8/30/2017 9:03:03 PM - Ended Deployment at: 08/30/2017 21:03:03

![image](https://user-images.githubusercontent.com/1306272/29890570-55c33400-8dc8-11e7-91ca-d9b2d61c30fd.png)

![image](https://user-images.githubusercontent.com/1306272/29890499-1404da64-8dc8-11e7-9c2d-99ebd6a36871.png)

Any idea what might be missing? I have checked under the top level site in the /teams/microsoft site collection and none of the lists are there.

**Comment by tstojecki** [comment]
I debugged configurelists.exe and found that the lists are being deployed to the app catalog site. Here is the line from ConfigureLists.cs/Main that determines that based on the value from excel:

`string targetSite = listval["CatalogSiteURL"]; // Get the URL of site collection`

Is that the right location for the lists? If so, is there something that copies the lists over to a specific matter site? In my case the scripts expect the lists to be under https://[tenant].sharepoint.com/teams/microsoft

**Comment by tstojecki** [comment]
Per @premchandpl response in issue #764 I have checked the following:

- [x] There will be a list called "ProvisionMatterList" in sharepoint catalog site collection
- [x] Permissions for this list are broken
- [x] There will be a sharepoint group called "Provision Matter Users" and this group should have "Contribute" permissions
- [x] The login user should be part of that group

So all of that checks out. I do not see any buttons where I am able to add/provision matters though and I said above the lists are not in the /teams/microsoft site collection which is the only client I had specified in excel. 

Please suggest next steps to troubleshoot.

**Comment by premchandpl** [comment]
@tstojecki Can we have skype meeting so that we can close this issue. I am in PST zone and my skype id is premchand_76@hotmail.com

We can discuss tomorrow at 10 AM PST

**Comment by tstojecki** [comment]
That would be great @premchandpl 
I will coordinate the meeting w/ you through email.

**Comment by tstojecki** [comment]
Hi @premchandpl 
I sent you two emails, waiting to hear back so we can follow-up. Please let me know if you got them.

**Comment by premchandpl** [comment]
@tstojecki  Today is a holiday over here and I am busy tomorrow. Can we have this meeting on Wednesday?

**Comment by tstojecki** [comment]
Yes, Wednesday is fine. I can meet at either 9 or 10 am PST, please let me
know what works for you.

Thanks,
Tomek

**Comment by premchandpl** [comment]
@tstojecki  9 AM PST is fine

**Comment by premchandpl** [comment]
@tstojecki Closing as the issue has been resolved.
