### ISSUE TITLE
Matter Center installed, pages do not load

### ISSUE THREAD

**Issue by mcpsmith** [Microsoft/mattercenter#777]
I installed Matter Center without error. The Sharepoint site never fully loads, it just displays the "Please wait while Matters load" screen. I was able to successfully create a Matter but when I click on Matters from the Azure site it simply shows the loading animation and never finishes loading

![image](https://user-images.githubusercontent.com/26168907/30133320-7369e68a-9321-11e7-8fef-d669ba3a0e7d.png)

**Comment by premchandpl** [comment]
@mcpsmith Can we have skype meeting to discuss this issue. My skype id is - premchand_76@hotmail.com

**Comment by tstojecki** [comment]
@mcpsmith can you bring up a dev console (F12) and look for errors there?

**Comment by mcpsmith** [comment]
@tstojecki 
Errors on the Sharepoint Site:
![image](https://user-images.githubusercontent.com/26168907/30167249-c3bd164c-93b3-11e7-817b-44ef929821f7.png)

**Comment by mcpsmith** [comment]
@tstojecki 
Similar Errors on Matter Center Azure Site:
![image](https://user-images.githubusercontent.com/26168907/30167292-e622e388-93b3-11e7-9510-361ac6cc6c79.png)

**Comment by mcpsmith** [comment]
@premchandpl  yes I am available on Skype - can we meet at 12:30pm EST?

**Comment by tstojecki** [comment]
@mcpsmith @premchandpl  I see the same exact errors in my console, if you guys end up getting to the bottom of this issue, please respond back

**Comment by premchandpl** [comment]
@mcpsmith We can meet on Monday 9:30 AM PST

**Comment by tstojecki** [comment]
@mcpsmith @premchandpl 
This appears to have something to do with the latest commit "Code changes to show the default values of additional content type col values" https://github.com/Microsoft/mattercenter/pull/756/commits/5dabc333bdc773f1c705d435ac7cdce83aabd9e0

I haven't been able to track it down further, but it looks like it throws a null reference exception in MatterProvision.cs when it runs this code
`//Added MatterDefault Content type to part of Matter Search results. `
`if (key.ToString().ToLower() == searchSettings.ManagedPropertyMatterDefaultContentType.ToLower())`
`{`
                            `ServiceUtility.AddProperty(matterData,
                                configuration.GetSection("Search").GetSection("SearchColumnsUIPickerForMatter").GetSection("matterDefaultContentType").Key,
                                searchResult[key].ToString());`
`}`

You can also see the error details by inspecting the GET request to /api/v1/matter/get
![image](https://user-images.githubusercontent.com/1306272/30207464-e5f28274-948f-11e7-8233-5975ad506eef.png)

@mcpsmith can you check the network tab in your dev console after reloading the page to see if you get the same error?

**Comment by mcpsmith** [comment]
@premchandpl  Thank you! I Can we push it back a half hour to 10amPST/1pm EST on Monday ?

**Comment by mcpsmith** [comment]
@tstojecki - yes I am seeing the same error in the response for /api/v1/matter

**Comment by premchandpl** [comment]
@tstojecki @mcpsmith Call you look into this github issue where solution has been provided

https://github.com/Microsoft/mattercenter/issues/759

**Comment by mcpsmith** [comment]
@premchandpl @tstojecki  - this worked! Thank you! Matters page and Sharepoint page both load now.
