### ISSUE TITLE
Rename matter center azure site so date is not in site name

### ISSUE THREAD

**Issue by mcpsmith** [Microsoft/mattercenter#779]
How do I rename the Azure site after deploying? Matter Center deployment appends a date string to the site name as part of the deployment. I would like to update the site name so the date does not appear.  How will this affect the backing sharepoint site/storage, etc.

**Comment by gustavnavar** [comment]
You should modify the Deploy-AzureResourceGroup.ps1 script, line 41 has  to be commented:
#$WebAppName = $WebAppName + ((Get-Date).ToUniversalTime()).ToString('MMddHHmm')

After that,  could do a fresh installation with no other issues.

**Comment by premchandpl** [comment]
@mcpsmith Let me know if @gustavnavar suggestion will work for you.

**Comment by mcpsmith** [comment]
@premchandpl  @gustavnavar  thank you this worked
