### ISSUE TITLE
Access Denied while provisions Settings.aspx and MatterCenterHome.aspx

### ISSUE THREAD

**Issue by Koroush7** [Microsoft/mattercenter#780]
I am getting Access Denied error during the provisioning of the above two pages. DocumentDetails.aspx page does get provisioned without any issues. The account I am using in Azure and Office 365 are the same account that has full control both in Azure (it is the Account Administrator) and Office 365 and SharePoint Online. It has full control at https://yourcompany.sharepoint.com/ and https://yourcompany.sharepoint.com/sites/catalog. I have also made sure this account is a site collection administrator on both sites.

I have seen the other ticket with the same error but unfortunately the suggestions there do not seem to address this issue. Anyone else encountering this problem?

Any ideas or suggestions as to what might be incorrect here?

Is it correct that both MatterCenterHome.aspx and Settings.aspx have to end up under

https://yourcompany.sharepoint.com/sitepages/

and that DocumentDetails.aspx would end up under

https://youcompany.sharepoint.com/sites/catalog/sitepages/

**Comment by premchandpl** [comment]
@Koroush7 In order to access settings.aspx page, the login user should be part of owners group of root site collection. Let me know if this one solves the issue

**Comment by Koroush7** [comment]
Hi premchandpl,

Thank you for the feedback. I do confirm that the user is in the Owners group both on the root site collections as we as the catalog site collection and yet I still get the access denied error.

https://yourcompany.sharepoint.com/
https://yourcompany.sharepoint.com/sites/catalog

**Comment by premchandpl** [comment]
@Koroush7 Can we do skype meeting premchand_76@hotmail.com

**Comment by Koroush7** [comment]
Sure, I emailed you yesterday but it may have gone to your spam folder. We just need to schedule a time or I can just reach out to you over Skype. Thank you for offering to help with this.

**Comment by Koroush7** [comment]
I ran step 5 (Deploy.ps1) and then tried for the 50th time. The deployment went all the way to the end without any issues. I got the 500 error after publishing but that might be a question for a different ticket.

**Comment by walidelrifai** [comment]
hi @Koroush7 could you assist me with deploying matter center  if you got it to work properly.

**Comment by Koroush7** [comment]
Hi,
I am sorry but that was a few years ago and I don't have that environment setup any more. I wish I could be of more help.
Koroush
    On ‎Friday‎, ‎October‎ ‎23‎, ‎2020‎ ‎04‎:‎57‎:‎16‎ ‎AM‎ ‎PDT, walidelrifai <notifications@github.com> wrote:  
 
 


hi @Koroush7 could you assist me with deploying matter center if you got it to work properly.
