### ISSUE TITLE
New architecture and update on the project

### ISSUE THREAD

**Issue by tstojecki** [Microsoft/mattercenter#781]
Please do not take this as criticism, just my honest assessment after spending a couple of weeks deploying it, fixing some issues and trying to help through the PRs that were submitted.

I see two issues with the new architecture:
1. Cost of running it in Azure for dev/demo scenarios
2. Complexity likely affecting contributions

1) I have gone through a number of issues (along with other users) in trying to deploy it, which can be seen in Issues. I got help which I appreciate and the matter center is more of less functional, however I can't keep it up as it ate up most of my azure resources, mostly due to Redis and Azure Web Plan. I have hardly used the matter center outside of trying to deploy it. To make it worse, you can't disabled/pause these services. The only one I was able to stop was the app service, but I am still being charged for Redis, Web Plan, Scheduler Job even though I am not accessing the matter center at all. Unless you're deploying this for a large client, this I think will be a very hard sell for demo/dev scenarios. Services like Redis should be pluggable (optional) and we need to be able to pause it while the solution isn't being used.

2) The re-architecture took the complexity to a whole new level IMO, which makes it a lot harder for others to contribute. This is a massive solution with a lot of pieces that have to come together for everything to work. The docs do not seem complete. The PRs are sitting there for a long time, I am not sure why, other than there is not many people working on this. Can the core maintainers please provide an update on who is supporting this project? Are the contributors listed in the readme still working on this project?

**Comment by beardiedog** [comment]
Did you get any response to your points?  as somebody just starting to look into this project these are both very valid points and I was not considering that I'd be consuming much in the way of Azure resources in addition to my Office 365 subscription.

**Comment by tstojecki** [comment]
@beardiedog No response

**Comment by premchandpl** [comment]
@beardiedog @tstojecki 

Matter center application leverages both office 365 and azure for development and deployment.

From Azure perspective, the following resources has been used

1. Azure web app - For deploying the web site
2. Azure Key vault - For storing connection strings related to Azure AAD, Blobs, Redis Cache connection
3. Blobs - For Application logs, For storing matter center data to send notifications
4. Azure Redis Cache - for storing term store data. Term store look up will be a costly operation and so once we get the data from term store, we are storing in azure redis cache. If you don't want redis cache, you have to tweak the code a little bit in taxonomycontroller.cs file. Redis cache has been used only in that file
5. Azure AAD - For user authentication and app permissions to SharePoint Online, Graph, Exchange Online


From Office 365, the following resources has been used

1. SharePoint online
2. Exchange Online for Matter Center add in. If you don't want the outlook add-in, you may not require Exchange add in and lot of features of Matter Center will be missing if you don't use Exchange online


Matter center application is a massive application and there are lot of integration pieces. Do let me know if you want any demo on the matter center with all the features. Hope this clarifies some of your questions.

Reach out to me if you need any calrification or information on matter center

**Comment by tstojecki** [comment]
Thanks for the pointers around Redis @premchandpl . It still sounds like this is a bit of an overkill given the cost. 

Any idea what is holding up the PRs? These are the well known bug fixes. The way the PRs are being handled is a bit discouraging. 

Can you give an update on the roadmap? Is this project in maintenance mode at this point?

**Comment by beardiedog** [comment]
Hi @premchandpl  I think a demo and discussion would be great if it's not too much bother.

**Comment by premchandpl** [comment]
@beardiedog Can we have this demo coming Monday at around 2 PM PST

**Comment by beardiedog** [comment]
If you send an email we can sort a good time darren.baldwin at tr.com

**Comment by nikthakur** [comment]
Hi @premchandpl can I join the demo if possible or will it be possible to setup a separate demo? I am on PST time zone.

Thanks

**Comment by premchandpl** [comment]
This is my skype id - premchand_76@hotmail.com. Just ping me to that skypeid

**Comment by nikthakur** [comment]
I added your Hotmail ID to my Skype. Its awaiting your approval.

**Comment by premchandpl** [comment]
@nikthakur I haven't got any request
