### ISSUE TITLE
Exception while launching the Azure web site after successful deployment

### ISSUE THREAD

**Issue by nikthakur** [Microsoft/mattercenter#782]
Hello everyone,

I was able to successfully deploy the various artifacts to SharePoint sites and also Azure. However when I try to navigate to the Azure web site I am getting the following expection:

An error occurred while starting the application.
TypeLoadException: Inheritance security rules violated by type: 'System.Net.Http.WebRequestHandler'. Derived types must either match the security accessibility of the base type or be less accessible.
Microsoft.Rest.ServiceClient.CreateRootHandler()
TypeLoadException: Inheritance security rules violated by type: 'System.Net.Http.WebRequestHandler'. Derived types must either match the security accessibility of the base type or be less accessible.
Microsoft.Rest.ServiceClient.CreateRootHandler()
Microsoft.Azure.KeyVault.KeyVaultClient..ctor(ServiceClientCredentials credentials, DelegatingHandler[] handlers)
Microsoft.Legal.MatterCenter.Web.Common.KeyVaultHelper.retrieveSecrets(bool cert) in KeyVaultHelper.cs
Microsoft.Legal.MatterCenter.Web.Common.KeyVaultHelper.GetKeyVaultSecretsCerticate() in KeyVaultHelper.cs
Microsoft.Legal.MatterCenter.Web.Startup.ConfigureServices(IServiceCollection services) in Start4up.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

I have updated the System.Net.Http nuget package to the current latest version 4.3.2 which did not help fix the expection.

Any suggestions appreciated.

Thank you.

**Comment by premchandpl** [comment]
@nikthakur I think this is some what related to Keyvault where all your credentials, connections strings are stored

Look into this post for more information on this

https://github.com/dotnet/corefx/issues/11100

**Comment by premchandpl** [comment]
@nikthakur Let me know if you are still facing the issue

**Comment by nikthakur** [comment]
Hi @premchandpl 

Thanks for checking in. Yes I was able to fix the issue by creating the Client secret which was not correctly generated before.

Cheers!

**Comment by premchandpl** [comment]
@nikthakur Can we close this issue now?

**Comment by nikthakur** [comment]
Yes you may close this issue.
