### ISSUE TITLE
VS 2015 & 2017 issues

### ISSUE THREAD

**Issue by kungfulu** [Microsoft/mattercenter#784]
If I build and run in VS 2015 it gives me a .NET Core tools error saying it is only preview for VS 2015.  If I build it in VS 2017 I don't get that issue and it build fine, yet when it comes to publishing it I get an error that it is missing dependency's.  I have no problems working on steps 1-8 with no errors until I get to the publishing.  Anyone have these issues?

**Comment by premchandpl** [comment]
@kungfulu The matter center application should compile with vs 2015. We haven't tested with VS 2017 and the new .Net Core version. I think it is compatible with .Net Core 1.0

**Comment by kungfulu** [comment]
The links on the main page under "Installation & Build" point to .NET Core 2.0.

**Comment by premchandpl** [comment]
@kungfulu If you see the project.json file, you can see that .Net Core version that has been used was 1.0.0.

Just for reference from web project.json file

"Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
