### ISSUE TITLE
Error Step 7: Provisioning Web dashboard error, already a global admin and site collection admin

### ISSUE THREAD

**Issue by mcpsmith** [Microsoft/mattercenter#786]
Getting the following error at Step 7: Exception while Provisioning Matter Center page: Access denied. You do not have permission to perform this action or access this resource.

User is a global admin, term store admin and site collection admin on the app catalog. 

What other kind of admin do I need to be? Can I install the Web Dashboard manually, without running through the entire Deploy-AzureResourceGroup.ps1 script again? Everything else in the script has been successful. Thank you!

![image](https://user-images.githubusercontent.com/26168907/30817912-222c6f24-a1e8-11e7-8186-c62e67321912.png)

**Comment by mcpsmith** [comment]
Did not mean to close, this is the only remaining error with Step 7. Please assist. Thank you!

**Comment by mcpsmith** [comment]
Hello @premchandpl  - do you have any ideas on how to resolve this and if this step can be done manually without running through the entire Deploy-AzureResourceGroup.ps1 script again? Thanks.

**Comment by premchandpl** [comment]
@mcpsmith I think  the documentdetails.aspx will will be provisioned in the root site in the page library. Here are the things you can check:

1. Check whether the publishing site collection feature has been enabled for that root site
2. Also the login credentials you are using in the powershell scipt, should have full permissions to the root site collection

**Comment by Koroush7** [comment]
Even though you have run deploy.ps1 from an earlier step trying running it again just before this step. I had this issue and what resolved it for me was to run deploy.ps1. Once I did that I was able to complete this step without any issues.

**Comment by mcpsmith** [comment]
@Koroush7  @premchandpl  - thank you, rerunning deploy.ps1 seems to have resolved this issue.
