### ISSUE TITLE
Can WebJob resources be moved to the main Matter Center Resource Group

### ISSUE THREAD

**Issue by mcpsmith** [Microsoft/mattercenter#788]
The Deploy-AzureResourceGroup.ps1 script created a Resource Group (cs-WestUS-scheduler) for the web jobs that differs from the Resource Group created for the other Matter Center Resources (RG-LegalMatters - this was one of the inputs requested at the start of the script).  

Do the web jobs need to be in their own resource group or can they be moved to the the same resource group as the other matter center resources (key vault, reddis cache, etc)?

**Comment by premchandpl** [comment]
The azure web job is used for sending email notifications. We havent tested the azure web job to be in another resource group and all other resources in another resource group. We have tested the functionality be placing all the resources in the same resource group

**Comment by mcpsmith** [comment]
@premchandpl  - ok great, so it sounds like it is safe to move them all to the same resource group? The deployment scripts created two resource groups (one for the scheduled jobs, one for all other resources)

**Comment by premchandpl** [comment]
@mcpsmith I am not sure why the scripts created two resource groups.

**Comment by mcpsmith** [comment]
@premchandpl  ok thanks, I will proceed with moving them to the other resource group.
