### ISSUE TITLE
Cannot login to azure site, are address and reply address case sensitive?

### ISSUE THREAD

**Issue by mcpsmith** [Microsoft/mattercenter#789]
Everything appears to have run, web app is published but I get the following error when trying to login to the Azure site: 

Sorry, but we’re having trouble signing you in.
We received a bad request.
The reply address 'http://xxxxx.azurewebsites.net/' does not match the reply addresses configured for the application: 'xxx'

Is the address case sensitive? 

![image](https://user-images.githubusercontent.com/26168907/30884391-79f6e892-a2dd-11e7-9904-3d360cf8feb8.png)

![image](https://user-images.githubusercontent.com/26168907/30884386-72c212ae-a2dd-11e7-8016-062537f11d7e.png)

**Comment by nikthakur** [comment]
I fixed this issue by adding the mentioned reply addresses in the Reply URLs settings in Azure Active directory's App registrations. Not sure if that the best way to handle this issue. Currently we are evaluating the solution.

**Comment by premchandpl** [comment]
@mcpsmith Can you check whether the reply url in the azure active directly points to your azure web site. Can you also check whether the azure web site that has been there in the reply url is http or https in the azure active directory.

Also try to access your azure web site using https and not http.

By seeing the screen shot, I see that you are trying to access your web site using http and not https.

Let me know if this is going to solve your issue

**Comment by mcpsmith** [comment]
@premchandpl  @nikthakur  - I switched to access the site via https and that worked, the reply url in Azure AD App Registraitons was https not http.

**Comment by rmanjhi** [comment]
[#[](url)](url
![untitled](https://user-images.githubusercontent.com/30716153/50132959-9c84ec00-02af-11e9-8ea1-ca9699e97e56.png)
)
@nikthakur  can you help to solve this problem,I have tried to solve it. many time.
