### ISSUE TITLE
Briefcase functionality issue

### ISSUE THREAD

**Issue by SjoerdV** [Microsoft/mattercenter#79]
Hi there,

I noticed that the briefcase functionality is somewhat diminished compared to all the demonstrations. The new OneDrive UI removes the ECB function (of course you can switch to classic for the time being) and also within a matter landing page the ECB is just like the default. Is this a correct observation or am I missing something?

When using the briefcase function from within the file preview dialog in the MatterCenterHome page I get this logged:
**PartitionKey**: BriefcaseHelperFunction
**Errorcode**: -2146233088
**LogMessage**: List 'Documents' does not exist at site with URL 'https://[tenant]-my.sharepoint.com/personal/mcadmin_[tenant]_onmicrosoft_com'.
**MethodName**: UploadtoBriefcase

Has someone encountered this and knows how to fix it?

**Comment by sunnymistry** [comment]
The observation is correct and on point. 

The possible cause of the issue is with new version of OneDrive for Business the doc. library structure is updated because of which existing code is unable to find the Document library so that user to copy files.

**Comment by SjoerdV** [comment]
OK thanks, so this probably has to be rewritten to use the REST interface, as stated in the roadmap?

**Comment by lkuhn65** [comment]
Just FYI...
Here’s the latest guidance on OD4B webpage and document library customizations that came out last week:  https://support.microsoft.com/en-us/kb/3140381

Going forward OD4B webpage customizations aren’t supported

**Comment by stefvanhooijdonk** [comment]
Maybe "we" can still keep part of the briefcase feature working: having a convenience copy in your OD4B  for on the go.
Of/and we add a Page in the App where you can check the files in your briefcase?
p.s. the error is related to the fact your Documents DocLib has a non english Title. The Code looks for this DocLib by Title in the english spelling. See #83
