### ISSUE TITLE
Webdashboard seems to be missing 

### ISSUE THREAD

**Issue by nikthakur** [Microsoft/mattercenter#792]
The matter center seems to be working for the most part. However I noticed that webdashboard page is not deployed. 

Is this a manual step? Can someone share instructions to deploy the webdashboard page.

Thanks,

-Nik

**Comment by premchandpl** [comment]
@nikthakur Need to check your SPO environment. Let me know if we can have skype call for the same. premchand_76@hotmail.com

**Comment by nikthakur** [comment]
Yes we can, I am available now till 10:30 am PST. Otherwise we can meet between 1-2 pm PST.

Thanks,

**Comment by premchandpl** [comment]
@nikthakur I am available at 10:30 PM PST

**Comment by nikthakur** [comment]
ok 10:30 PM, not AM? I am not able to add you to my skype for some reason. I have added you and the status is pending.

**Comment by premchandpl** [comment]
@nikthakur Sorry 10:30 AM. Its ok for me

**Comment by premchandpl** [comment]
@nikthakur Can I get your skype id to that email and I will add the same to my contacts

**Comment by nikthakur** [comment]
I will send you an email your Hotmail address
