### ISSUE TITLE
File Path Limit

### ISSUE THREAD

**Issue by CBlaize** [Microsoft/mattercenter#795]
`Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not write lines to file "obj\Debug\Microsoft.Legal.MatterCenter.CreateContentTypes.csproj.CoreCompileInputs.cache". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.	Microsoft.Legal.MatterCenter.CreateContentTypes			
`

Long Path limit issue when cloned down project and attempted to build HelperUtilities.

**Comment by premchandpl** [comment]
@CBlaize Try to clone the code not into your deep directory folder structure. The File path limit is windows restriction. In my step up, I cloned like this:
**C:\projects\mc** 

Let me know if this helps

**Comment by CBlaize** [comment]
@premchandpl Thanks for the quick response, that is exactly what I ended up doing and it worked for me.  Still working through issues with the deployment scripts.
