### ISSUE TITLE
Matter center page hangs

### ISSUE THREAD

**Issue by nikthakur** [Microsoft/mattercenter#796]
Hi,

I have deployed Matter center in a separate tenant. For most part the Matter center features works where I can create a new matter and it creates all the relevant artifacts, etc. 

The matter page which list all the matters keeps on spinning. In the console following exceptions are displayed:

Failed to load resource: the server responded with a status of 404 (Not Found)
%7B%7BattachmentInfo.iconSrc%7D%7D Failed to load resource: the server responded with a status of 404 (Not Found)
angular.min.js:118 Error: [$resource:badcfg] http://errors.angularjs.org/1.5.8/$resource/badcfg?p0=ErrorNaNn%20resource%configuration%for%20action%20%60%7B0%7D%60.%20Expected%20response%20to%contain%20an%20%7B1%7D%20but%20got%20an%20%7B2%7D%20(Request%3A%20%7B3%7D%20%7B4%7D)&p1=get&p2=array&p3=object&p4=POST&p5=%2Fapi%2Fv1%2Fmatter%2Fget
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:6:412
    at https://cdnjs.cloudflare.com/ajax/libs/angular-resource/1.5.8/angular-resource.js:777:25
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:131:20
    at m.$eval (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:145:347)
    at m.$digest (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:142:420)
    at m.$apply (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:146:113)
    at l (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:97:322)
    at J (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:102:34)
    at XMLHttpRequest.t.onload (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:103:4)
(anonymous) @ angular.min.js:118

The site columns such are Practice groups etc are pointing to the correct term set "Practice Groups". 

Any suggestions why matter center is not loading list of matters?

Thanks,

-N

**Comment by mcpsmith** [comment]
Hello @nikthakur  - I was getting a similar error (issue #777) and followed the solution in issue #759.  759  walks through the steps of adding a new managed property called "MCMatterDefaultContentType".  This may resolve your problem

**Comment by nikthakur** [comment]
Thanks @mcpsmith yesterday I followed the steps to add managed property and that resolved the issue with Matter center page. I will close the issue.
