### ISSUE TITLE
Error when accessing any Matter Center page

### ISSUE THREAD

**Issue by JohnLeeNJ** [Microsoft/mattercenter#80]
I finally got Matter Center to install (O365 and Azure) after several tries and several errors.  A site was created for the Client in my Excel Config file, but none of the Matters from that file were created.
Also, when I try to access the Matter Center site I get this error:
>
An unexpected error has occured while performing your last action. Please try again. If this issue persist, please contact your administrator.
>
Error Code: -2146233079
>
Timestamp: 02-15-2016 22:49:43:5579834

I acknowledge the error and the page displays.  However, if I try to create a new Matter, the "waiting" spinner never stops and the page never loads completely.  Same thing if I go to the Matter Search page.  And, the same error appears every time I go to a new page.

Can anyone guide me on how to go about troubleshooting this?

Thanks.
John

**Comment by sunnymistry** [comment]
I would recommend checking out #62 for troubleshooting steps. 

Following are the reason why you are getting these errors:
 a. Go to Microsoft.Lega.MatterCenter.Utility project. Open the Constants.resx file. In this file, check the key named "Provision_Matter_App_URL". If it contains ProvisionDMSMatter in the URL update it to https://.sharepoint.com/sites//MatterCenter
 b. If above is correct, go to Microsoft.Legal.MatterCenter.SharepointAppWeb project. Open Web.Config and over here check the appsetting key named "HostedAppHostNameOverride". Value of this key should be only .azurewebsites.net. It should not prefix with https://. Check this same thing in Microsoft.Legal.MatterCenter.ProviderService > Web.config

**Comment by amitabhm21** [comment]
Closing this as the solution is posted. Please re-open if this is still an issue,

**Comment by DaveyDoo** [comment]
I just re-deployed using the most recent build and still get this error.  Checking the key named "Provision_Matter_App_URL" and, if it contains ProvisionDMSMatter in the URL, updating it to https://.sharepoint.com/sites//MatterCenter resolves the issue.

**Comment by muradhaider5** [comment]
@sunnymistry : i am getting the same problem. My "Provision_Matter_App_URL" in Constants.resx file in Microsoft.Lega.MatterCenter.Utility project  is like "https://tenant.sharepoint.com/sites/AppCatalog/MatterCenter" if its not correct then how should i write it??
also i rechecked web.configs that u mentioned. Key "HostedAppHostNameOverride" got the values in correct syntax. please help
