### ISSUE TITLE
Are the Scheduler Job Collections used to send notifcations?

### ISSUE THREAD

**Issue by mcpsmith** [Microsoft/mattercenter#802]
There are two Scheduler Job Collections that are created in the Resource Group. What do they do? They are both scheduled with an end-by date of 2015.  Is this the reason Matter Center notifications do not work? 

![image](https://user-images.githubusercontent.com/26168907/31614443-71c214e0-b254-11e7-899f-f0628095bea6.png)

**Comment by premchandpl** [comment]
@mcpsmith The web job work is to send notifications. I haven't observed the end date issue as I have stopped this job in my matter center application.

If no emails are coming, try to extend the expiry date and you can check the same.

**Comment by mcpsmith** [comment]
@premchandpl  I have set the end to "Never" and still do not get any emails when creating matter.

**Comment by premchandpl** [comment]
@mcpsmith Can you check web job log details and see whether any exceptions are logged?

**Comment by mcpsmith** [comment]
@premchandpl  - I have checked the activity log for the job in azure.poral.com and do not see any errors
