### ISSUE TITLE
Republishing Web project has broken Matter Center, pulling from multiple tenants

### ISSUE THREAD

**Issue by mcpsmith** [Microsoft/mattercenter#806]
I tried to update some links in appsettings.json (sites/catalog to sites/ourCatalogName) to resolve the issue described in #804. After publishing the web project, the matter center pages are completely broken and appear to be trying to access data from a different tenant.
![image](https://user-images.githubusercontent.com/26168907/31681535-85d4c6de-b345-11e7-93d3-23fd5f015303.png)

**Comment by premchandpl** [comment]
@mcpsmith Can you whether all mattercenter javascript files are there in your root spo collection

**Comment by mcpsmith** [comment]
Yes they are there (see image below).  The problem is that the url was wrong because our app catalog is called "apps" and not "catalog". I updated per #804, republished and I am not sure why it is trying to pull from a different tenant now.

![image](https://user-images.githubusercontent.com/26168907/31684745-b79ae76c-b34e-11e7-9aa8-43838adaa024.png)

**Comment by premchandpl** [comment]
@mcpsmith Need to check your and we can do some skype meeting for the same. We can do this tomorrow. My skype id is premchand_76@hotmail.com

**Comment by premchandpl** [comment]
@mcpsmith I mean your site collection

**Comment by mcpsmith** [comment]
@premchandpl  thank you! What time will work for you? I am available after 10am EST

**Comment by premchandpl** [comment]
@mcpsmith will be available at 11:30 AM PST

**Comment by mcpsmith** [comment]
@premchandpl  - ok, I will reach out to you at 11:30AM PST

**Comment by mcpsmith** [comment]
hi @premchandpl  - I am mpandarakalam@shawmut.com - trying to IM you on skype now. Thanks.

**Comment by premchandpl** [comment]
@mcpsmith stuck in some meeting. Will join in 15 min. Will that be ok?

**Comment by mcpsmith** [comment]
@premchandpl  - yes thank you!

**Comment by mcpsmith** [comment]
Had to make updates to spcommon.js, matterlanding.js, appsettings.json.
