### ISSUE TITLE
Adding a new user to Matter Center

### ISSUE THREAD

**Issue by wgrizzle** [Microsoft/mattercenter#81]
after performing the steps below. The user was unable to see or access Matter Center add-in from the app bar in Outlook or any MS. Office app. 

**Please let me know what is missing from my steps below.**

Adding users to Matter Center 
1.	Add uses to App Catalog after you create the catalog
2.	Sharepoint admin page
3.	Choose app/app catalog/site settings/site permissions
4.	Enter user from the above process

Note: This would only be needed if not pulling users and or group from AD
Adding Users to Site collection
1.	Adding users to site collection (This MUST be done before starting Step 1.)
2.	Admin/click on  https://wbmmcpoc.sharepoint.com
3.	Site settings/site permission/team site visitors
4.	Modification to matter MUST also be in site owners		
5.	Navigate to Administrative Page/Site Collection

Adding Users to Client Collection
1.	Admin page/site selection/site settings
2.	Site permission on Visitors group (remove send email option) do this for all client
3.	Users modifying matter MUST be added to Owners group

**Comment by MKrupskiy** [comment]
If I understand the problem correctly, this might help. Please take a look at this [MSDN article](https://msdn.microsoft.com/en-us/library/office/fp123517.aspx)

> After you upload add-in manifests to the Office Add-ins catalog, users can access the add-ins by doing the following:
> In the Office application, go to File > Options > Trust Center > Trust Center Settings > Trusted Add-in Catalogs.
> Specify the URL of the parent SharePoint site collection of the add-in catalog. For example, if the URL of the Office Add-ins catalog is:
> https://domain/sites/AddinCatalogSiteCollection/AgaveCatalog
> Specify just the URL of the parent site collection:
> https://domain/sites/AddinCatalogSiteCollection
> Close and reopen the Office application. The add-in catalog will be available in the Office Add-ins dialog box.

**Comment by ctrulove** [comment]
@wgrizzle Pinging you to see if you have the information you need. If you are still experiencing issues, please let us know so that we can troubleshoot and resolve.

**Comment by sramangit** [comment]
I'm having trouble with this step too. I set up matter center using a global admin account; I can see and use matter center under that account when I log into Outlook web access.

However, when I login with a different global admin account, I am unable to see the Matter Center addin within outlook web access. I ensured that I explicitly forced the add-in to be enabled under the Exchange settings too, but it only seems to be be visible for account I used to set up Matter Center. How do I make it available to all users?

**Comment by ctrulove** [comment]
Can you go to the following URL and let me know what you see?

https://outlook.office.com/owa/?path=/options/manageapps

**Comment by ctrulove** [comment]
It should look like this:
![image](https://cloud.githubusercontent.com/assets/9450534/15436137/576cc686-1e8e-11e6-8428-678d05b0b946.png)

**Comment by sramangit** [comment]
It appears to be turned on. This is what I see:
![image](https://cloud.githubusercontent.com/assets/15724045/15439278/c9861982-1e95-11e6-8792-526269b2c1a7.png)

When I log in as the admin account that I used to set up Matter center, I see this in my webmail:
![image](https://cloud.githubusercontent.com/assets/15724045/15439341/1b9008aa-1e96-11e6-8d7f-26150cbf46aa.png)

However, when I log in as any other user (even if it's a tenant admin and a site collection admin), I don't see the Matter Center add-in in webmail:
![image](https://cloud.githubusercontent.com/assets/15724045/15439381/52cca6fc-1e96-11e6-91ab-d6c8c109278b.png)

**Comment by wgrizzle** [comment]
Please close this issue. This issue was resolved. My apologies for not updating.

**Comment by sramangit** [comment]
Hi @wgrizzle, did you have a similar issue as mine with the Exchange add-in, and if so, how did you resolve it? Sorry, i didn't mean to hijack your thread, but I've been running into issues with opening up Matter Center to the users in my tenant. Can you share your resolution?

**Comment by wgrizzle** [comment]
Hi Sramangit

My problem was not with allowing access or having users access Matter Center but adding new users to Matter Center after it was up and running.

Questions for you: Are you implementing into a production tenant or trial tenant?
Are all the users listed in the groups in the Excel spreadsheet?
Did you receive any errors during the setup process?

Note: All users will meet to have rights to the Matter Center app in SharePoint. Users must have rights to the site collection and term store.
