### ISSUE TITLE
Failing to set SPcontext 

### ISSUE THREAD

**Issue by pratapkkk** [Microsoft/mattercenter#82]
Hi All,

Matter center app is failing to set context token at below code and it is failing. So please let me know the possible cause for this error and resolution ASAP. 

Your help is much appreciated. Thanks in Advance !!!

it fails in TokenHelper.cs 

=================================================================
  bool validationSuccessful = false;
            string realm = Realm ?? token.Realm;
            foreach (var audience in acceptableAudiences)
            {
                string principal = GetFormattedPrincipal(ClientId, audience, realm);
                if (StringComparer.OrdinalIgnoreCase.Equals(token.Audience, principal))
                {
                    validationSuccessful = true;
                    break;
                }

  if (!validationSuccessful)
            {
                throw new AudienceUriValidationFailedException(
                    String.Format(CultureInfo.CurrentCulture,
                    "\"{0}\" is not the intended audience \"{1}\"", String.Join(";", acceptableAudiences), token.Audience));
            }
      ========================================================
public static string GetRefreshToken(string contextToken)
        {
            string refreshToken = string.Empty;
            if (!string.IsNullOrWhiteSpace(contextToken))
            {
               ` SharePointContextToken contextTokenData` = TokenHelper.ReadAndValidateContextToken(contextToken);
                refreshToken = null != contextTokenData ? EncryptionDecryption.Encrypt(contextTokenData.RefreshToken) : string.Empty;
            }
            return refreshToken;
        }

Thanks,
Pratap

**Comment by sunnymistry** [comment]
Following are the cases where this can happen:
a. Client ID and Client Secret values used in the configuration file might be incorrect
b. The AppRedirect URL formed will be having issues because of which Tokens returned by SharePoint are not being read by the class

**Comment by amitabhm21** [comment]
I am assuming this issue is resolved, Closing to clean up issues list.
