### ISSUE TITLE
Deploy.ps1 script issue 

### ISSUE THREAD

**Issue by Good-Kamalpandey** [Microsoft/mattercenter#824]
I'm trying to run Deploy script from PowerShell ISE and PS command prompt  both times get issue 

![2018_01_09_12_24_05_administrator_windows_powershell_ise](https://user-images.githubusercontent.com/14984405/34733966-276c4060-f538-11e7-825c-0190e1af8fc1.png)

Thanks !

**Comment by premchandpl** [comment]
@Good-Kamalpandey Can you please check deployment excel file and the data has been properly filled in

**Comment by ArnoHarteveld** [comment]
The error occurs if there is a parsing error with the configuration data in the excel file.

**Comment by Good-Kamalpandey** [comment]
setup was not correct
