### ISSUE TITLE
Access denied when running ProvisionWebDashboard

### ISSUE THREAD

**Issue by Alen-Mrkalj** [Microsoft/mattercenter#825]
When running ProvisionWebDashboard utility I get "Access denied" error while executing the first clientContext.ExecuteQuery statement in CreateMatterCenterPage method. 

The strange thing about it is that I have all the permissions on the SharePoint site where I am trying to provision the pages with ProvisionWebDashboard utility. In this case my account is the site administrator.

The exception message:
"Access denied. You do not have permission to perform this action or access this resource."

Did you guys ever run in such exception?
Thanks in advance for any help.

**Comment by anoop7181** [comment]
Hi @Alen-Mrkalj ,

Most of the items i got this exception is when site url entry in config excel is wrong or user didn't have the owner permissions on the site.

Regards
Anoop

**Comment by Alen-Mrkalj** [comment]
Thanks @anoop7181 
Actually something completely different caused this issue in my case. I will share it if anyone else has this issue. The issue was that custom site scripting was not allowed on my site. To allow custom scripts the following PowerShell command can be used:

 Set-SPOSite <Site URL> -DenyAddAndCustomizePages 0

This setting can also be changed from UI (SharePoint admin center > settings > custom scripts), but there is latency before the change has effect.  With PowerShell commandlet it works immediately.
