### ISSUE TITLE
Need to edit Outlook plugin to point to correct application

### ISSUE THREAD

**Issue by tgarmon** [Microsoft/mattercenter#827]
Needless to say we have had a few issues with deploying this solution. One of which was self inflicted. I installed two separate matter center applications on azure and deleted one. However, the one I deleted was the more recent of the installs, which left Sharepoint pages with the wrong application ID address. I have managed to fix the Sharepoint issues by editing the pages after exporting, editing, and re-importing the corrected file. The plugin is looking for mattersweb02041909.azurewebsites.net’s and it says "server IP address could not be found." So, I need to edit the plugin's settings to correct the address for the current application. Any help on this is greatly appreciated. I cannot figure out how to make these edits to the add-in. 

![image](https://user-images.githubusercontent.com/26411605/36395926-419a076a-1581-11e8-814f-b6267259df78.png)

**Comment by anoop7181** [comment]
Hi @tgarmon ,

Did you try to change in the outlook manifest file and upload it manually into add in template in office 365 ?

Regards
Anoop

**Comment by tgarmon** [comment]
Tried all of that. We could not get the original plugin to remove from the system. I was on the phone for an hour with an Office 365 expert and we tried everything; so i setup a new separate tenant account and we have deployed there, but still having issues, new issues. Error 500.
