### ISSUE TITLE
Non US O365 Tenants and the Briefcase

### ISSUE THREAD

**Issue by stefvanhooijdonk** [Microsoft/mattercenter#83]
In the Briefcase Service, the code assumes the Library Title and URL are the same for the Personal Documents.
My dutch tenant, my Document Library in my OneDrive is called Documenten and the URL is Documents.

There are 2 places in the BriefCaseHelper methods, where this needs to be changed.

**Comment by SwapnilM92** [comment]
It seems you are referring to initial version of Matter Center codebase

The OneDrive document library title is referred from resource file (Constants.resx) present in ProviderService.

![image](https://cloud.githubusercontent.com/assets/16336925/20485865/7c6d911e-b023-11e6-9591-53b3f8e91f5d.png)

As you have tenant configured in dutch language, this document library name need to be updated to 'Documenten' to ensure Lists.GetByTitle() work as expected

**Comment by premchandpl** [comment]
@stefvanhooijdonk. We are not supporting this version of matter center. We have upgraded Matter center with new set of features and we are calling this as Matter Center V2. Install V2 and let us know if you face any more issues
