### ISSUE TITLE
Services project needs dependentAssembly entry in web.config for "Newtonsoft.Json"

### ISSUE THREAD

**Issue by stefvanhooijdonk** [Microsoft/mattercenter#84]
<dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30AD4FE6B2A6AEED" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-7.0.0.0" newVersion="8.0.0.0"/>
   </dependentAssembly>

**Comment by ctrulove** [comment]
@stefvanhooijdonk Can you expand upon the issue you resolved by adding this to the web.config? I do not have this entry in my web.config and am having no issues.
