### ISSUE TITLE
WebDashboardSPTemplate.html not included in solution

### ISSUE THREAD

**Issue by DaveyDoo** [Microsoft/mattercenter#86]
The latest Build and Deployment Guide Appendix A adds a reference to a file WebDashboardSPTemplate.html, which is to be added as a Web Part to a new webdashboard.aspx page, but there is no such file in the solution/Html Chunk folder.

**Comment by amitabhm21** [comment]
This is a typo on the documentation it should be WebDashboardSP.html. This will be updated in the doc as part of some other fixes that are in queue.

**Comment by amitabhm21** [comment]
Closed in error.

**Comment by ctrulove** [comment]
@amitabhm21 I believe this can be closed as the file is not called WebDashboardSPTemplate.html in both the documentation and in the solution.

**Comment by amitabhm21** [comment]
Thanks for the follow up !
