### ISSUE TITLE
Error when adding Microsoft.Legal.MatterCenter_Outlook.xml App to Exchange

### ISSUE THREAD

**Issue by shak3800** [Microsoft/mattercenter#87]
Hello everyone!

I've been struggling to install matter center the last couple of days . It is deployed but none of the links work and I keep getting errors that 'oGlobalConstants' is undefined.

Regarding the SendMail list , do we have to manually create that one and place it under the catalog/MatterCenter site ? I've create a simple custom list SendMail with a default title column, there are no instructions on how to create it .

I still haven't figured out why this is happening , but when I run the deploy script I noticed that I get an error when I try to add the Outlook.xml app to exchange.

GetExchangeActAsUserTokenHandler needs to be set to support X-RF cases
    + CategoryInfo          : InvalidOperation: (<my username>...4f-2c628b704f58:AppId) [New-App], OwaExtensionOpera
   tionException
    + FullyQualifiedErrorId : [Server=DB5PR08MB0566,RequestId=b2a77371-acdb-4553-9e2d-9f328fda4231,TimeStamp=2/23/2016
    8:56:51 AM] [FailureCategory=Cmdlet-OwaExtensionOperationException] A06CD57D,Microsoft.Exchange.Management.Extens
  ion.NewApp
    + PSComputerName        : ps.outlook.com

Does anyone have any idea why this is happening and how can I fix it ? Is it related with the oGlobalConstants error ?

If anyone could help me out I would be grateful

Thanks !

**Comment by amitabhm21** [comment]
@shak3800 Would you please look at this thread: https://github.com/Microsoft/mattercenter/issues/62 ?

**Comment by shak3800** [comment]
@amitabhm21 Thanks for the response. I have already check that thread and my provision web url is ok . 

I ll write the values if you please kindly tell me if I've done anything wrong.
SharePointAppWeb Constants.resx

App_Redirect_Url: https://smartgeekseu.sharepoint.com/sites/catalog/_layouts/15/appredirect.aspx
this url doesn't work for some reason

Application_Insight_App_Id : I've used the instrumentation key for this , but I would prefer not to use an application insight app id. Is there a way not to use this one?

Central_Repository_Url: https://<tenant>.sharepoint.com/sites/catalog


MatterCenterProviderService Constants.resx

Matter_Landing_Page_CSS_File_Name: /sites/catalog/SiteAssets/{0}/Styles/MatterLanding.css 
this one I don't know which style it gets. There is no directory like this on my catalog site collection

Matter_Landing_Page_jQuery_File_Name: the same

Site_Url: https://<tenant>.sharepoint.com : Is this correct?? Or should I use my catalog site?

Anyone can help please?
