### ISSUE TITLE
SendMail list is not created nor MatterCenter site

### ISSUE THREAD

**Issue by shak3800** [Microsoft/mattercenter#89]
Hello !

It seems that SendMail list is not created by using the Deploy.ps script . I tried at first I got an error message that MatterCenter site below the catalog is not created . I created that manually but then I got an error when it tries to updating list permissions of SendMail because sendmail list doesn't exist.

How can I fix this ?

This is the message I get 

2/26/2016 12:25:14 PM - Status: Installing
2/26/2016 12:25:19 PM - Matter Center has been successfully loaded and installed
2/26/2016 12:25:19 PM - Disabling SideLoading feature on site https://matteruirall.azurewebsites.net
2/26/2016 12:25:20 PM - SideLoading disabled on site https://rallonline.sharepoint.com/sites/catalog
Updating permissions for SendMail list....................
Message: SendMail list was not created successfully at https://rallonline.sharepoint.com/sites/catalog/MatterCenter
2/26/2016 12:35:34 PM - Adding and installing apps to SharePoint and Office failed

MatterCenter App is loaded and installed but the SendMail list doesn't exist

Thanks

**Comment by shak3800** [comment]
It seems that each time I run the script , it changes the provision matter url to ProvisionDMSMatter even though I had it change in the bin folder in the deployment folder to MatterCenter.

**Comment by SwapnilM92** [comment]
This is because helper utilities still have ProvisionDMSMatter in app.config

**Comment by shak3800** [comment]
@SwapnilM92  Thanks for the response. Does this affect the deployment procedure? Any ideas why the SendMail list is not created?

**Comment by SwapnilM92** [comment]
Yes, this will affect the deployment procedure as App domain name is different from the one present in the solution.

While updating permission on SendMail list deployment script forms URL based on the app domain name which is present in App.config of that solution.

To resolve this issue update the app.config file as mentioned in the above comment.

**Comment by shak3800** [comment]
@SwapnilM92  thanks again. I've found app.config file in Microsoft.Legal.MatterCenter.UpdateAppConfig and Microsoft.Legal.MatterCenter.UpdateListPermissions and changed the values . Now I have to build this solution ? And move the files to the deployment folder? Build fails when I try to do that.

**Comment by shak3800** [comment]
Still no luck. I've updated the values in "Microsoft.Legal.MatterCenter.UpdateAppConfig.exe.config, Microsoft.Legal.MatterCenter.UpdateListPermissions.exe.config in deployment folder , I've updated the values of Constants.resx in Service Publish and Web Publish , still the list is not created even though the matter center app is installed successfully . I'm out of ideas

**Comment by shak3800** [comment]
problem is solved which unfortunately raised another issue.

Solution was to fix all the files required , and the MatterCenter Site is created automatically using the script. Afterwards the sendmail list is created successfully .
