### ISSUE TITLE
Feature Request: Add Helper Utilities source to solution

### ISSUE THREAD

**Issue by DaveyDoo** [Microsoft/mattercenter#90]
It would have helped me to work through issues such as adding a new user, adding a new client, or provisioning the web dashboard if the code in the deployments/Scripts/Helper Utilities folder was added to the solution.  While it has been helpful to debug the PowerShell scripts, this is not possible to step through the exe's called by the scripts.

**Comment by sunnymistry** [comment]
Helper Utilities source are now available. You can find them over here: https://github.com/Microsoft/mattercenter/tree/master/tree/master/cloud/src/Helper%20Utilities

**Comment by DaveyDoo** [comment]
Thanks! This will be helpful.
