### ISSUE TITLE
Setup Help

### ISSUE THREAD

**Issue by rolandon** [Microsoft/mattercenter#91]
Hello- i am new to matters center. i am using the deployment guide however when i get to section 5

"Open the main Matter Center solution and update the files listed in Appendix F using the example provided in the code."

It gets confusing am i suppose to do the deployment using scripts?? is there a sample script? is there a video deployment guide?

**Comment by DaveyDoo** [comment]
In the various files, xml and resx, you will see comments that will help you know what to enter to make Matter Center point to your environment.
Yes, the deployment scripts will do the bulk of the deployment.  I think some have tried to deploy the whole thing manually, but I don't know if they were successful.

**Comment by amitabhm21** [comment]
@rolandon there are currently no video deployment guide. The deployment mainly contained within the PowerShell scripts that are part of the solution. https://github.com/Microsoft/mattercenter/tree/master/tree/master/cloud/src/deployments/Scripts

The edits needed to the code as mentioned on Appendix F are contextual to the particular tenant you are deploying this to. Could you please elaborate on what you need specific help on ?

**Comment by amitabhm21** [comment]
Please re-open if this is still an issue.
