### ISSUE TITLE
Shell was not found on server error when adding app to Exchange

### ISSUE THREAD

**Issue by shak3800** [Microsoft/mattercenter#93]
Hello!

I just got a new issue regarding Exchange . 

WARNING: Your connection has been redirected to the following URI: "https://ps.outlook.com/PowerShell-LiveID?PSVersion=5.0.10586.63 "
New-PSSession : [ps.outlook.com] Processing data from remote server ps.outlook.com failed with the following error message:
[ClientAccessServer=AM3PR04CA0041,BackEndServer=sn1pr14mb0384.namprd14.prod.outlook.com,RequestId=ab09686b-7b6f-41f3-b484-28d47d955f81,TimeStamp=2/29/2016 7:38:18 AM]
[FailureCategory=WSMan-InvalidShellID] The request for the Windows Remote Shell with ShellId 69A74821-25A0-401C-BCFF-807D5B3E7C74 failed because the shell was not found on the server.
Possible causes are: the specified ShellId is incorrect or the shell no longer exists on the server. Provide the correct ShellId or create a new shell and retry the operation. For more
information, see the about_Remote_Troubleshooting Help topic.
+ ...  $session = New-PSSession -ConfigurationName Microsoft.Exchange -Conn ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:RemoteRunspace) [New-PSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : CannotConnectTargetSessionDoesNotExist,PSSessionOpenFailed
2/29/2016 9:38:04 AM - Error in creating session... Connection to Exchange failed...

Any ideas ?

**Comment by shak3800** [comment]
Ok guys I found the solution . I opened the deploy script with PowerShell ISE and it worked

**Comment by Kazzan** [comment]
Yeah, it looks like a regression of https://support.microsoft.com/en-my/help/3090768/invalidshellid-error-in-rps-in-office-365-dedicated-itar
