### ISSUE TITLE
Pre-import check Content type name 'Medical Device' conflict  

### ISSUE THREAD

**Issue by shak3800** [Microsoft/mattercenter#99]
Hello everyone!

I get this error in publishing error log each time I publish the content types from the content type hub to the site collections.

I get errors for each content type and field .

Proxy Taxonomy_4BLQTxDzt3+F9JB2YxRRiQ== error

Content type name 'Automotive' conflict 

Anyone knows why ?

Thanks!

**Comment by amitabhm21** [comment]
@shak3800 . This is very specific to your SPO instance and how the Taxonomy is created. As this is not a Matter Center code issue we are closing this.
